### ISSUE TITLE
More readable styling for chart tooltips

### ISSUE THREAD

**Issue by sc1f** [finos/perspective#1006]
### Description of Problem:

When looking at tooltips on charts, the decimal point between floats are unclear and hard to read at a glance:

![Screen Shot 2020-04-06 at 6 35 53 PM](https://user-images.githubusercontent.com/13220267/78611782-b3997580-7835-11ea-831c-50f7e51bafb8.png)

### Potential Solutions:

Tooltips should be styled with a clear differentiation/highlight on the number, or the bold styling should be removed as it seems to (at least for me) hinder quick at-a-glance readability.

**Comment by NickSneo** [comment]
I am new to the open-source world, so can I take this issue. Also, I just need to add monospace font for the hypergrid, right?

**Comment by Nitish0777** [comment]
Increased Font Size: Enlarge the font size of the tooltip text to make it more prominent and easier to read.

Bold Decimal Points: Make the decimal points in the float values bold to help them stand out from the rest of the text.

**Comment by texodus** [comment]
This is not an actionable change and is attracting the ChatGPT crowd, closing.
