### ISSUE TITLE
Segmentation fault due to TBB when > 8 clients are connected to a Python table

### ISSUE THREAD

**Issue by sc1f** [finos/perspective#1007]
Marking this up as a reference:

When a server-hosted Perspective Table in Python has multiple simultaneous connections (I've seen it with > 8 connections) and 2-sided views are created, there are _sometimes consistent_ segfaults resulting from parallel calls to `notify_context` that drill all the way down to `build_strand_table_phase_1` in `sparse_tree.cpp`.

I've isolated it down to TBB by using a build of `perspective-python` that does not have TBB enabled, and the exact same test script (run 5x over 10 instances) works fine, whereas the TBB-enabled version segfaults around 8/9 clients during the first script iteration. 

Logs posted here for reference: https://gist.github.com/sc1f/98ed12e55386433a74eefc08d11d5e50

**Comment by timkpaine** [comment]
I think we might want to eliminate TBB and implement our own threading, @texodus should comment as well given webassembly threads now available. TBB is only used now for naive for loop parallelization, whereas we can probably do smarter stuff.

**Comment by sc1f** [comment]
10 Puppeteer browser instances running the [test script](https://github.com/sc1f/perspective-stresstest/blob/master/viewer_test.js) **with TBB**:

![Screen Shot 2020-04-06 at 6 57 21 PM](https://user-images.githubusercontent.com/13220267/78613829-d5e1c200-783a-11ea-96c9-f8374367c671.png)

10 Puppeteer browser instances running the same test script **without TBB**:

![Screen Shot 2020-04-06 at 6 56 33 PM](https://user-images.githubusercontent.com/13220267/78613832-d67a5880-783a-11ea-8cc2-ff22da8ef660.png)

I will need to do proper benching to figure out the cost of removing TBB, especially in large datasets - these results are interesting though. Gonna reinstall a non-TBB build and try running more stuff just to make sure I didn't mess up the benching somehow.

**Comment by texodus** [comment]
WebAssembly thread support for Perspective.js will likely involve entirely rewriting the entire WASM loader, as Emscripten's current support for control the WebWorker loading which we've extensively customized.

However, in principle, were we to accomplish this and refactor our parallel `for` loops to use a custom threadpool backed by `pthread`, this would "just work".  Will need some research into the current feature robustness in Emscripten, I think>

**Comment by texodus** [comment]
I believe this issue has bit-rotted, closing (though feel free to re-open if further evidence turns up).
