### ISSUE TITLE
Readability in DataManipulator.ts  email -  /ezeaninewton1@gmail.com/

### ISSUE THREAD

**Issue by ezeanic** [finos/perspective#1019]
I would help new users better to read if, it was renamed to be:

const priceRatio = priceABC / priceDEF;

and then later on having:
 ratio: priceRatio,

export class DataManipulator {
  static generateRow(serverRespond: ServerRespond[]): Row {
    const priceABC = (serverRespond[0].top_ask.price + serverRespond[0].top_bid.price) / 2; 
    const priceDEF = (serverRespond[1].top_ask.price + serverRespond[1].top_bid.price) / 2; 
    const priceRatio= priceABC / priceDEF; 
    const upperBound = 1 + 0.05; 
    const lowerBound = 1 - 0.05;
    return {
      price_abc: priceABC,
      price_def: priceDEF,
      ratio: priceRatio,
      timestamp: serverRespond[0].timestamp > serverRespond[1].timestamp ? 
        serverRespond[0].timestamp : serverRespond[1].timestamp,
      upper_bound: upperBound,
      lower_bound: lowerBound,
      trigger_alert: (priceRatio> upperBound) || ((priceRatio< lowerBound)) ? priceRatio: undefined,
    };
  }
}

**Comment by texodus** [comment]
This does not seem to be related to perspective at all - are you sure you have the correct repository?
