### ISSUE TITLE
Chart Readability

### ISSUE THREAD

**Issue by ezeanic** [finos/perspective#1020]
Looking at the chart, the attributes of the lines are not visible because the lines are covering and moving around them. The fact that the attributes are sitting there might also block useful data.

![image](https://user-images.githubusercontent.com/46737359/79845986-db3b2280-838b-11ea-8e57-740d96809b1a.png)

### Potential Solutions:
It could be modified that the chart will have a different component, that allows those attributes to be visible there, rather than staying in the same space with the lines.

**Comment by texodus** [comment]
Legends in `@finos/perspective-viewer-d3fc` are movable, resizable and even _persistent_ in these properties view the `plugin-config` attribute - did you try dragging it someplace else?
