### ISSUE TITLE
Difficulty installing perspective python

### ISSUE THREAD

**Issue by MisterAwesome23** [finos/perspective#1025]
### Description of Problem:
I am trying to install perspective using python which is turning out to be real haywire. Downgrading pip version, changing wheels, not working in virtual environment, PEP 517 errors, upgrading python from 3.6 to 3.7 and so on. 

### Potential Solutions:
Make a requirement.txt or setup an installed virtualenv which some can use onto go or something on those lines.

**Comment by sc1f** [comment]
Try installing with `pip install -v perspective-python`, and post the logs here as well as the platform/OS you're installing on.

It is likely that your problem stems from not having the right build environment setup; we do not dist wheels at the moment for `perspective-python`, so you should follow the [Developer Docs
](https://perspective.finos.org/docs/md/development.html#system-specific-instructions) to perform an install.

At the very least, make sure that the [System Dependencies](https://perspective.finos.org/docs/md/development.html#system-dependencies) are installed.

**Comment by MisterAwesome23** [comment]
>pip install -v perspective-python

Gives-
ERROR: Could not build wheels for perspective-python which use PEP 517 and cannot be installed directly

I could not find any requirement.txt or requirement-dev.txt in python perspective folder so I added my own from the setup.py file-
```requirement.txt
ipywidgets>=7.5.1
future>=0.16.0
numpy>=1.13.1
pandas>=0.22.0
pyarrow==0.15.1
python-dateutil>=2.8.0
six>=1.11.0
traitlets>=4.3.2
```
Also, 
```requirements-dev.txt
Faker>=1.0.0
flake8>=3.7.8
mock
pybind11>=2.4.0
pytest>=4.3.0
pytest-cov>=2.6.1
pytest-check-links
pytz>=2018.9
Sphinx>=1.8.4
sphinx-markdown-builder>=0.5.2
```
I get the same PEP 517 error while trying to install requirements for "pyarrow" specifically. (requirements-dev all installed)

Platform: Windows 10 OS
Python 3.7.3

Link to relevant error log for PEP 517-
https://pastebin.com/zQ2emz8G

**Comment by timkpaine** [comment]
@MisterAwesome23 we do not support 32 bit, it looks like you're using a 32 bit build of python.

**Comment by MisterAwesome23** [comment]
That's weird because I am running on a x64 platform. May I know how did you figure that out and any suggested solution to that? Also, thanks for catering this issue so quickly and at a priority.

Also, can I use docker to avoid all the setup?

**Comment by timkpaine** [comment]
@MisterAwesome23 your platform is probably x64, but you have installed 32bit python:
C:\Users\adman\AppData\Local\Programs\Python\Python37-**32**

Try installing a 64-bit python

**Comment by MisterAwesome23** [comment]
I confirm I've installed a 32 bit version :/
Don't know how but it never troubled me yet- i'll move to x64 and try it out. Thank you ;)

**Comment by timkpaine** [comment]
@MisterAwesome23 feel free to make a new issue or we can reopen this one if you hit issues.

**Comment by MisterAwesome23** [comment]
C:\Users\adman>python
Python 3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32

Changed to 64bit-
Error log- https://pastebin.com/zJH9MJQ9
Same with and without "-v" flag
