### ISSUE TITLE
Register as widget on jupyter.org

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#1026]
https://github.com/jupyter/jupyter.github.io

**Comment by THE-VR7** [comment]
Hello. I am new to perspective and would love to contribute.
I would like to fix this issue, if no one is already on it.

**Comment by timkpaine** [comment]
@THE-VR7 sure! theres nothing to do in this repository really, you'll need to add an entry for perspective [over in the widget listings](https://github.com/jupyter/jupyter.github.io/blob/master/widgets.html#L39) and include links to perspective.finos.org and this page

**Comment by Kartiksingh565** [comment]
@timkpaine I just completed the VI intership and would love to contribute on perspective.

**Comment by timkpaine** [comment]
commented inline, just change name to just "Perspective" and it looks good

**Comment by timkpaine** [comment]
resolved, thanks @ruthussanketh !
https://jupyter.org/widgets
