### ISSUE TITLE
@finos/perspective-jupyterlab fails auto procurement due to 2 dependency issues

### ISSUE THREAD

**Issue by telamonian** [finos/perspective#1036]
## Bug Report
Currently, I cannot use @finos/perspective-jupyterlab in my work environment since it fails our auto procurement routine. This is due to issues in two dependencies:

- papaparse@4.6.3
  - security vulnerability
  - https://snyk.io/vuln/SNYK-JS-PAPAPARSE-564258

- tslib@1.11.2
  - unknown license: 0BSD
    - that's the number zero followed by "BSD"

### Steps to Reproduce:
run jpmorgan's auto procurement on @finos/perspective-jupyterlab@0.4.8

### Expected Result:
auto procurement of @finos/perspective-jupyterlab works

### Actual Result:
auto procurement of @finos/perspective-jupyterlab fails

**Comment by timkpaine** [comment]
@telamonian papaparse upgraded https://github.com/finos/perspective/pull/1033

**Comment by telamonian** [comment]
hmm, when I run `yarn audit` on master, I don't see the `papaparse` vuln. There's some other vulns, but I think they're all in dev dependencies.

Is it possible this is already at least partially fixed in master?

**Comment by texodus** [comment]
I believe this was fixed by @zemeolotu yesterday in #1033, can you confirm?  If so this will be in the next Perspective release.

**Comment by telamonian** [comment]
I think I've figured out the tslib license issue. tslib changed its license to BSD zero clause [just 20 days ago](https://github.com/microsoft/tslib/commit/11b9a947a793a4125f1edb08dd9b81d8658d3de7#diff-61e0bdf7e1b43c5c93d9488b22e04170), and then did the first release of tslib (1.11.2) with the new license [only yesterday](https://github.com/microsoft/tslib/releases/tag/1.11.2)

**Comment by texodus** [comment]
Thanks for the report!

Closing, as there's not much functional purpose to the report as we've discovered the root cause and its unaddresable by a PR.
