### ISSUE TITLE
can't read property 'column_paths' of undefined & <g> attribute transformed "expected number"

### ISSUE THREAD

**Issue by mehulsatardekar** [finos/perspective#1038]
### Steps to Reproduce:
 1. ...select X bar chart...
 2. ...select abc name checkbox...
 3. ...view error in console box...

![Screenshot from 2020-05-07 11-30-13](https://user-images.githubusercontent.com/36101139/81325241-1153f400-9066-11ea-96ce-34e95386f19d.png)

### Expected Result:
...expected number but it's showing undefined...

### Environment:
![Screenshot from 2020-05-07 13-46-44](https://user-images.githubusercontent.com/36101139/81327442-4150c680-9069-11ea-950a-5cce3968f814.png)

### Bug demo

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/36101139/81328393-cee0e600-906a-11ea-8154-e3ef77fb7874.gif)

**Comment by texodus** [comment]
Thanks for the detailed bug report!

While the console errors aren't pretty - this isn't really a bug per se, as we can't really make a bar valid bar chart for a `string` column - I suppose we could make the Y-axis a category axis as we do for e.g. scatter charts, but the length of the bar from the X-axis will be a completely arbitrary number, so prob worth a description of what we're expecting *in the context of a specific a data visualization*, e.g. what the bars themselves should mean.

Adding a row-pivot, or using a chart type that supports category axes (like `xy-scatter`) will show a category chart which respect sort order.

I'll leave this open for now, as there's certainly some room for improvement here - ideally `perspective-viewer` would disallow nonsensical charts, or at least provide some feedback for the user about why the chart is blank - and should certainly absorb the console errors.

**Comment by THE-VR7** [comment]
Hello. I am new to perspective and would love to contribute.
I would like to fix this issue, if no one is already on it.

**Comment by texodus** [comment]
Nobody else has volunteered that I am aware :)

Our [developer docs](https://perspective.finos.org/docs/md/development.html) are a good place to get started.  I think the easiest starting place would be to construct a repro of the console errors (perhaps by using the [superstore example](https://github.com/finos/perspective/blob/master/examples/simple/superstore.html)) from a locally built version of `perspective-viewer`.  If you're having problems, please open a new issue with the specifics of where you're stuck, or add me as a code reviewer on a fork if you have changes you'd like help with.

**Comment by texodus** [comment]
This has bit-rotted, closing. While we still have some `d3fc` log noise, I'm not aware of any actual functionality break here.
