### ISSUE TITLE
I keep getting error column_path not defined, can anyone help me please 

### ISSUE THREAD

**Issue by stevedanOgochu** [finos/perspective#1049]
I keep getting this error and I don't know why, I tried comparing it with the example to see where the possible error could be but could not find a solution. Can someone assist me please. 
```
utils.js:217 TypeError: Cannot read property 'column_paths' of undefined
    at HTMLElement.draw (scroll_panel.js:377)
    at HTMLElement.r.value (utils.js:215)
    at HTMLElement.update (index.js:60)
    at perspective_element.js:318
```

**Comment by timkpaine** [comment]
Hey, theres not enough information here to do anything, please see https://stackoverflow.com/help/how-to-ask for tips on how to ask a question and include a minimum reproducible example.
