### ISSUE TITLE
Streaming issue

### ISSUE THREAD

**Issue by stevedanOgochu** [finos/perspective#1050]
How can I fix the x axis to a particular length and after updating the table refresh the view at once because I keep getting the problem that the new data is not totally aligned and creates the effect shown in the image to the right. 
![stream_error_data](https://user-images.githubusercontent.com/61468301/82239061-89f56300-9938-11ea-8cd5-c1b0b7aa2b67.png)

Thank you very much

**Comment by timkpaine** [comment]
Hey, theres not enough information here to do anything, please see https://stackoverflow.com/help/how-to-ask for tips on how to ask a question and include a minimum reproducible example.
