### ISSUE TITLE
issue running tests on Windows 7

### ISSUE THREAD

**Issue by patricio-mancini** [finos/perspective#1051]
### Steps to Reproduce:
 1. yarn test

### Expected Result:
Tests run successfully

### Actual Result:
`yarn run v1.22.4
$ node scripts/test.js
lerna info version 2.11.0
lerna info scope @finos/*
lerna info version 2.11.0
lerna info scope @finos/perspective-viewer-highcharts
$ rimraf "screenshots/**/*.@(failed|diff).png"
lerna success run Ran npm script 'clean:screenshots' in packages:
lerna success - @finos/perspective-viewer-highcharts
'node_modules' is not recognized as an internal or external command,
operable program or batch file.

Command failed: node_modules/.bin/lerna exec -- mkdir -p dist/umd
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Then, if a run "node_modules/.bin/lerna exec -- mkdir -p dist/umd", I got the following error:

`lerna info version 2.11.0
The syntax of the command is incorrect.
lerna ERR! exec Errored while executing 'mkdir -p dist/umd' in '@finos/perspective-webpack-plugin'
lerna ERR! execute callback with error
lerna ERR! Error: spawn mkdir ENOENT
lerna ERR!     at notFoundError (xxxxx\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:11:11)
lerna ERR!     at verifyENOENT (xxxxx\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:46:16)
lerna ERR!     at ChildProcess.cp.emit (xxxxx\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:33:19)
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
The syntax of the command is incorrect.
lerna ERR! exec Errored while executing 'mkdir -p dist/umd' in 'perspective-python-internal'
Error: spawn mkdir ENOENT
    at notFoundError (xxxxx\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (xxxxx\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (xxxxx\node_modules\lerna\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn mkdir',
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'mkdir -p dist/umd',
  timedOut: false,
  exitCode: 1
}
`

### Environment:
Windows 7. Using git bash console.

**Comment by texodus** [comment]
Closing in the Advent Era of Perspective Weekly Builds.
