### ISSUE TITLE
Chart Scrolling feature and overlapping chart labels

### ISSUE THREAD

**Issue by sakshisaxena12** [finos/perspective#1066]
**Feature Request**

**Description of Problem**
There should be a scrollable solution for the displaying chart within the tools. While displaying the charts, the axis values and labels tend to overlap sometimes. Found it while working on sales and stock predicting modules, where we had moving charts.

**Potential Solutions**
The user interface could be improved making it more user-friendly for handling. Axis labels and values need to be adjusted accordingly to make the chart more accessible and visual-oriented.

**Comment by texodus** [comment]
Duplicate #1039
