### ISSUE TITLE
Warnings in Command Prompt caused by the cmd 'npm install'

### ISSUE THREAD

**Issue by Dwaragesh** [finos/perspective#1073]
I recently completed the Virtual Experience of JPMC Software Engineering Virtual Experience. I was satisfied with the completion of all the given tasks. Yet, I was unable to configure why it kept giving me warning when I entered 'npm install' in the command prompt. The issue is shown below:

![image](https://user-images.githubusercontent.com/48896734/83319912-f9f0cc80-a207-11ea-8f0f-98fe4e9c57ad.png)

I just wanted to know the cause of this issue, and what can be done for it to be resolved. I tried to remove the node_modules that they gave me, replacing it completely with the new, downloaded file, in the pdf file that JPMC gave me. I also tried using the command 'npm audit fix', yet it failed to do so since I still have to manually fix and update my node_modules file.

Therefore, any thoughts or insights upon this issue that could potentially help others who could face this issue, and at the same, help us learn more about npm and its structure?

**Comment by rajatmudgil** [comment]
Dear @Dwaragesh 
Its not the issue that you are facing when you entered ' npm install '  as when we are going to type npm install it will redirected in a way that it will try to configure the node modules and your npm package along with its dependencies . 
So basically while this process is going on i.e install npm it will try to get you familiar with the outdated packages and dependencies in form of warnings that tell us  -:
 - which version is going to be use currently 
 - either it should require any peer dependencies or not
 - it consists of any vulnerablilites or not 
 - deprecates the packages if not configured as per our requirement 
 - if any package or module got renamed

So basically this is for your convenience . Like if i will show you after typing -: 

**npm install** 

![NPM_INSTALL_ERROR](https://user-images.githubusercontent.com/37063652/83353042-633e2000-a36d-11ea-84bc-2c4ab94c1951.PNG)

So if you want to install npm without having these warnings you can able to use a command -:

**npm install --silent** 

It will going to install npm without giving you warnings and loaded them very fast in your project or system . Here's the implementation of the code -:

**(1) Window cmd -:**

![NPM_INSTALL_ISSUE_RESOLVE](https://user-images.githubusercontent.com/37063652/83353127-faa37300-a36d-11ea-8990-e4c99b69b151.PNG)

**(2) Project IDE terminal -:**

![NPM_ISSUE_INSTALL_RESOLVED](https://user-images.githubusercontent.com/37063652/83353129-fbd4a000-a36d-11ea-8b6a-e2ea0ef5a0b6.PNG)

I hope this will going to help with your issue and also resolved .Its my pleasure to give this contribution as per my knowledge and experience .
Thanks

**Comment by rajatmudgil** [comment]
> I recently completed the Virtual Experience of JPMC Software Engineering Virtual Experience. I was satisfied with the completion of all the given tasks. Yet, I was unable to configure why it kept giving me warning when I entered 'npm install' in the command prompt. The issue is shown below:
> 
> ![image](https://user-images.githubusercontent.com/48896734/83319912-f9f0cc80-a207-11ea-8f0f-98fe4e9c57ad.png)
> 
> I just wanted to know the cause of this issue, and what can be done for it to be resolved. I tried to remove the node_modules that they gave me, replacing it completely with the new, downloaded file, in the pdf file that JPMC gave me. I also tried using the command 'npm audit fix', yet it failed to do so since I still have to manually fix and update my node_modules file.
> 
> Therefore, any thoughts or insights upon this issue that could potentially help others who could face this issue, and at the same, help us learn more about npm and its structure?



Dear @Dwaragesh 
Its not the issue that you are facing when you entered ' npm install '  as when we are going to type npm install it will redirected in a way that it will try to configure the node modules and your npm package along with its dependencies . 
So basically while this process is going on i.e install npm it will try to get you familiar with the outdated packages and dependencies in form of warnings that tell us -:
 - which version is going to be use currently 
 - either it should require any peer dependencies or not
 - it consists of any vulnerablilites or not 
 - deprecates the packages if not configured as per our requirement 
 - if any package or module got renamed

So basically this is for your convenience . Like if i will show you after typing -: 

npm install 

![NPM_INSTALL_ERROR](https://user-images.githubusercontent.com/37063652/83353042-633e2000-a36d-11ea-84bc-2c4ab94c1951.PNG)

So if you want to install npm without having these warnings you can able to use a command -:

npm install --silent 

It will going to install npm without giving you warnings and loaded them very fast in your project or system . Here's the implementation of the code -:

(1) Window cmd -:
![NPM_INSTALL_ISSUE_RESOLVE](https://user-images.githubusercontent.com/37063652/83353127-faa37300-a36d-11ea-8990-e4c99b69b151.PNG)
(2) Project IDE terminal -:
![NPM_ISSUE_INSTALL_RESOLVED](https://user-images.githubusercontent.com/37063652/83353129-fbd4a000-a36d-11ea-8b6a-e2ea0ef5a0b6.PNG)

I hope this will going to help with your issue and also resolved .Its my pleasure to give this contribution as per my knowledge and experience .
Thanks

**Comment by Dwaragesh** [comment]
Thank you, @rajatmudgil. I can understand the cause behind the warnings.

**Comment by texodus** [comment]
Glad y'all figured this out

**Comment by rajatmudgil** [comment]
It's my pleasure too on contributing (in terms of code too ) to J.P. Morgan Chase & Co. perspective .

**Comment by rajatmudgil** [comment]
Dear @texodus , its my plesure too on contributing in J.P. Morgan Chase & Co. open soure perspective .
