### ISSUE TITLE
perspective-click event on perspective-viewer-datagrid

### ISSUE THREAD

**Issue by BarCatFigaro** [finos/perspective#1076]
Hi guys,

Unless I am mistaken, the `perspective-click` event is not supported with `perspective-viewer-datagrid`, as it was previously with `perspective-viewer-hypergrid`. I tried searching for references to `perspective-click` in the repo and also confirmed it with replacing the hypergrid script with datagrid in one of the [linked examples](https://bl.ocks.org/texodus/08fb5f1afccbd33e333453dc70db88ea).

Should [the docs](https://perspective.finos.org/docs/md/js.html#click-events) be updated accordingly (as it might be misleading to new users, considering hypergrid is legacy) or should a similar change to [this PR](https://github.com/finos/perspective/pull/1023) be made?

Thanks :)

**Comment by timkpaine** [comment]
that PR is adding the event to datagrid
