### ISSUE TITLE
Scroll Position Lock While Streaming Data for Datagrid

### ISSUE THREAD

**Issue by choandrew** [finos/perspective#1081]
### Description of Problem:
While streaming data in the datagrid and sorting rows by most recently added, examining a specific row is very hard as the rows are moving down collectively.

### Potential Solutions:
Create an optional toggle that would allow one to "lock" the scroll position when one is not at the top/bottom of the grid, so that any rows in view would stay in view, even if more rows are being added to the top.
If one is at the top/bottom of the grid, the rows can be added normally.

**Comment by timkpaine** [comment]
I'm a big +1 on this as a variant could also let you stay at the middle in a book view (e.g. pivot by bid/ask and sit the view in the middle)
