### ISSUE TITLE
Incorrect Values Rendered with uint8 Column on Datagrid

### ISSUE THREAD

**Issue by BarCatFigaro** [finos/perspective#1084]
### Steps to Reproduce:
 1. Create an arrow file that includes a uint8 column
 2. Pass the `ArrayBuffer` data to `perspectiveViewer.update(...)`

### Expected Result:
Rendered datagrid should be equivalent to what is printed with its `pd.Dataframe` and `pa.Table` equivalents. The first two sections show the `pd.Dataframe` values, `pa.Table` slots, and `pa.Table.schema`:

```
<Dataframe.info(memory_usage='deep')>
    col_0       col_1      col_2       col_3     col_4  col_5
0   2020-05-19  name         0           0         0      0
1   2020-05-19  name         0           0         0      0
2   2020-05-19  name         0           0         0      0
3   2020-05-19  name         0           0         0      0
4   2020-05-19  name         0           0         0      0
5   2020-05-19  name         0           0         0      0
6   2020-05-19  name         0           0         0      0
7   2020-05-19  name         0           0         0      0
8   2020-05-19  name         0           0         0      0
9   2020-05-19  name         0           0         0      0
10  2020-05-19  name         0           0         0      0
11  2020-05-19  name         0           0         0      0
12  2020-05-19  name         0           0         0      0
13  2020-05-19  name         0           0         0      0
14  2020-05-19  name         0       13966    -13966      1
15  2020-05-19  name         0           0         0      0
16  2020-05-19  name         0           0         0      0
17  2020-05-19  name         0           1        -1      0
18  2020-05-19  name         0           0         0      0
19  2020-05-19  name         0      -39421     39421      1
--------------------------------------------------------------------
[<pyarrow.lib.ChunkedArray object at 0x7f7d540c8d68>
[[...]],
<pyarrow.lib.ChunkedArray object at 0x7f7d540c8368>
[[...]],
<pyarrow.lib.ChunkedArray object at 0x7f7d540c8818>
[[...]],
<pyarrow.lib.ChunkedArray object at 0x7f7d540c8c28>
[[...]],
<pyarrow.lib.ChunkedArray object at 0x7f7d540c8bd8>
[[...]],
<pyarrow.lib.ChunkedArray object at 0x7f7d540c89a8>
[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1]]
]
column_0: date32[day]
column_1: string
column_2: int32
column_3: int32
column_4: int32
column_5: uint8
```

### Actual Result:
What the last section shows what is rendered on the browser-side. Notice `col_5` has a difference in values in multiple rows (eg. row 4 and row 5), compared to above:

![bug_report](https://user-images.githubusercontent.com/22532640/84505374-9ba5fe00-ac8b-11ea-8142-d269af379a9d.PNG)

### Environment:
Running `Perspective` webpack plugin, datagrid, and d3fc on the latest (0.5.0).

### Additional Context

From briefly looking over the source code, could this be a casting issue (ie. in `emscripten.cpp`)?

**Comment by sc1f** [comment]
Hi - thanks for the detailed report! I generated an arrow file exactly as the one in your example and was not able to reproduce the error:

![Screen Shot 2020-06-12 at 11 35 07 AM](https://user-images.githubusercontent.com/13220267/84520281-4ecd2200-aca1-11ea-83ca-bd656f4b7714.png)

I'm pretty sure the dataframe/arrow I generated is to the spec of the one in your report, although I may have slipped up somewhere:

![Screen Shot 2020-06-12 at 11 36 00 AM](https://user-images.githubusercontent.com/13220267/84520379-7c19d000-aca1-11ea-974b-4281c8512d63.png)

![Screen Shot 2020-06-12 at 11 36 11 AM](https://user-images.githubusercontent.com/13220267/84520384-7fad5700-aca1-11ea-8b4c-6352cf75738c.png)

![Screen Shot 2020-06-12 at 11 36 16 AM](https://user-images.githubusercontent.com/13220267/84520409-8936bf00-aca1-11ea-97e1-03ee51f199a1.png)

Out of curiosity, what happens if you just print the output from the Table itself without going through the viewer? Something like:

```javascript
import {table} from "@finos/perspective";
console.log(table(arrow).view().to_columns());
```

**Comment by BarCatFigaro** [comment]
Hi Jun, without going through the viewer:

```
import perspective from "@finos/perspective";
const resp = await req;
const buffer = await resp.arrayBuffer();
const worker = perspective.shared_worker();
const table = worker.table(buffer);
const view = table.view();
console.log(view.to_columns());
```

I can verify the columns look correct:

![console_report](https://user-images.githubusercontent.com/22532640/84527852-a58c2900-acac-11ea-9c9e-8d63a3dd39df.PNG)

**Comment by BarCatFigaro** [comment]
If I pass the `response.arrayBuffer()` directly into `perspectiveViewer.update(...)`, the values seem to get corrupted; `temp2` is created from `document.getElementsByTagName("perspective-viewer")[0].view.to_columns()`. If I create a new table and pass that instead (`temp1`), the values produced are correct.

<img width="402" alt="corrupted" src="https://user-images.githubusercontent.com/22532640/84672259-576a6600-aef6-11ea-8c4d-371071990e8d.PNG">

**Comment by BarCatFigaro** [comment]
I've also tried passing the array buffer into `perspectiveViewer.load(...)`, rather than `perspectiveViewer.update(...)` which seems to produce the correct results. Is this an issue with my setup?

I initially load a schema and call update on any new data received. `col_6` is mapped to an `integer` data type.

**Comment by sc1f** [comment]
Ah - I can reproduce the issue now in Javascript and in `perspective-python`. It's only happening when updating a table from schema, which means the `update` is trying to fill a column defined internally as an `int32` with `uint8`. This isn't happening when the table is created from the arrow, as the column type internally would be a `uint8`, so there would be no corruption.

The `integer` type in `perspective.js` and `perspective-python` reflects a 32-bit integer. If you feel like poking around in the C++ internals, the problem will be somewhere inside `arrow_loader.cpp`, whose `fill_table` method gets called by `make_table` in `emscripten.cpp`. If you plan on taking a look, feel free to ask any questions you have in this thread and we can help you out.

I'll also take a look at the issue  - it's consistent and reproducible so there will be a regression test added for it as well. Thanks!
