### ISSUE TITLE
Table.Clear() Usage

### ISSUE THREAD

**Issue by BarCatFigaro** [finos/perspective#1088]
## Support Question

Hey!

I just wanted to clarify the usage of `table.clear()` and whether it frees up column data for GC. I understand `table.delete()` explicitly mentions that in the documentation, but could not find any information about `table.clear()`.

I am trying to understand the performance of my table when loaded with large and specific datasets. One benchmark I am consulting is the memory footprint in Chrome Task Manager. After updating my table of 4 columns with ~1.5 million rows, the memory footprint spikes to ~2.6GB. However, once I clear the table and update it with ~16,000 rows, the memory footprint remains at a similar size. Similarly, taking heap snapshots also show the same result.

**Comment by timkpaine** [comment]
Clear empties without reclaiming memory, while delete does both.

**Comment by timkpaine** [comment]
closing, feel free to ask additional questions or reopen if there are specific issues/concerns
