### ISSUE TITLE
Large Dataset OOM when Aggregating by String Type

### ISSUE THREAD

**Issue by BarCatFigaro** [finos/perspective#1089]
## Support Question

I am trying to load an arrow dataset of ~1.8 million rows with the webassembly runtime (0.5.0), but am running into memory issues.

The arrow dataset schema is as follows:
```
category: dictionary<values=string, indices=int8, ordered=0>
pnl_1: int32
pnl_2: int32
pnl_3: int32
trade_date: dictionary<values=string, indices=int8, ordered=0>
```
The `category` column contains a single repeating string, while the `trade_date` column is year-to-date enumerated.

I am trying to group the table by `trade_date`, with `category` aggregated by count, `pnl_1`, `pnl_2`, and `pnl_3` aggregated by sum.

On data load with no aggregation initially set (group by `trade_date` is after the table updates), the heap seems to grow unbounded until the page runs OOM:

<img width="723" alt="unbounded2" src="https://user-images.githubusercontent.com/22532640/84808951-66751500-afd7-11ea-8edb-16040655f60d.PNG">

If I load the data with `trade_date` already configured to be grouped by, there seems to be no large issues with memory performance:

<img width="735" alt="normal2" src="https://user-images.githubusercontent.com/22532640/84808969-6bd25f80-afd7-11ea-9143-10b78662b7c0.PNG">

Is there a distinction between these two workflows and performance of the engine?

**Comment by BarCatFigaro** [comment]
I've also taken performance timelines on the two workflows:

<img width="888" alt="unbounded_timeline" src="https://user-images.githubusercontent.com/22532640/84808119-3a0cc900-afd6-11ea-9b46-bba9364ff934.PNG">

and

<img width="884" alt="bounded_timeline" src="https://user-images.githubusercontent.com/22532640/84808130-3e38e680-afd6-11ea-9295-3a9d6cbcf3f4.PNG">

**Comment by sc1f** [comment]
Can you define what you mean by "after the table updates"? From what I'm reading it seems that you're loading the 1.8 million rows and then streaming new updates to it? Or is it that you're creating the table from schema and then updating it with the 1.8 million rows?

**Comment by sc1f** [comment]
FWIW I created a repro dataframe and profiled the memory after I applied a pivot in the UI, with a 10k row append every 2 seconds and not interacting with the UI at all:

![Screen Shot 2020-06-19 at 9 50 22 AM](https://user-images.githubusercontent.com/13220267/85140740-ad4f4e80-b213-11ea-87f9-1d500347a553.png)

I also profiled applying a pivot after the table has loaded, with no additional tick updates or interaction with the UI:

![Screen Shot 2020-06-19 at 10 01 41 AM](https://user-images.githubusercontent.com/13220267/85140921-fbfce880-b213-11ea-9795-17f6a46418b3.png)

The memory profiles here look relatively stable, and GC is getting called. The presence of those repeated empty strings in your heap snapshot are a little concerning, but I could not repro that either. Do you have any other code that might be keeping references to the dataset/anything updating the table? If the table isn't being updated with new ticks, then memory usage should remain relatively stable.

#1037 has some discussion on this topic as well.

Repro schema:

![Screen Shot 2020-06-19 at 9 59 08 AM](https://user-images.githubusercontent.com/13220267/85141028-2353b580-b214-11ea-965f-086638a5eeed.png)

**Comment by TimeWanderer** [comment]
Hello,

@sc1f I added new findings on #1037 which may also help with this issue.
