### ISSUE TITLE
date columns with 'unique' aggregate breaks datagrid plugin 

### ISSUE THREAD

**Issue by panda311** [finos/perspective#1097]
### Steps to Reproduce:
 In Perspective superstore example, adding Ship Date to the columns list and making column's 
 aggregate 'unique' and minimize configurations, this breaks the datagrid component and Scroll 
 also.

The console gives invalid time value Error, This might be possible that the associated function might not be able to able to handle value as null.

**Comment by sc1f** [comment]
Thanks for the report! We are aware of the issue (#1068) - it should be fixed in the next major update to datagrid as Perspective is ported to use [regular-table](https://github.com/jpmorganchase/regular-table).
