### ISSUE TITLE
Failed to install visual  C++ Build tools for Virtual Internship InsideSherpa task 2

### ISSUE THREAD

**Issue by jaygaud10** [finos/perspective#1099]
While setting up the environment for the Virtual Internship InsideSherpa task 2 . I have successfully setup python 3.7 environment and run the server3.py file.After that I installed nvm install v11.0.0 and run nvm use 11.0.0. My node and npm are properly set up but for getting the things going, I have to install Visual C++ Build Environment after downloading and install that, I  run the commands npm install and npm install but they are giving errors.

After trying a lot of things I scroll down in the pdf and  found a solution that I have to download the nodemodules folder from the below given drive link and keep it in the 
Task folder.
Drive Link :-
  https://drive.google.com/file/d/1ML6nECK18J0jM3hhfJdSCRtCNLssruYQ/view
So it will be better if we put this nodemodules folder already in the Task Folder .

**Comment by texodus** [comment]
You need to install the project with the `yarn` (or `npm install`) commands.
