### ISSUE TITLE
Expanding Perspective as an educational tool for better understanding of finance.

### ISSUE THREAD

**Issue by AgnivarnaTrivedi** [finos/perspective#1100]
### Description of Problem:
Currently there is no option to pause the real time data changes in the perspective viewer to study and understand stalks.
When we try to pause the display whether in Datagrid or Y-line graph, it doesn't pause long enough and begins to run at erratic speed and timing.This doesn't give the viewer a window of time long enough to analyse the stock prices or spot any anomaly.

### Potential Solutions:
Want to enable the viewer with a click or a button to stop for as long as they please ,at a particular stock exchange at a particular instance to pause and study the stock exchange or any anomaly.
This will empower any non finance background client to understand the stocks and enable them to take a deeper dive in the money business at their ease.

**Comment by texodus** [comment]
This can be done at the API level, and probably should in most practical cases as the engine cannot have enough knowledge to prevent a significant memory leak in this case (as it must prepare for being un-paused at any time).

As Perspective is moving away from direct control over the data engine, for now this is out-of-scope, closing.
