### ISSUE TITLE
Feature addition (Range of dates)

### ISSUE THREAD

**Issue by mugdhakolhe** [finos/perspective#1102]
Currently there is no facility for user to choose the start date and end date for plotting the graph. The graph is plotted according to data in .csv file. However additional feature of choosing the range of dates can be provided at run time.

**Comment by sc1f** [comment]
Use filters:

<img width="1677" alt="Screen Shot 2020-06-21 at 11 54 55 AM" src="https://user-images.githubusercontent.com/13220267/85229133-18d12180-b3b6-11ea-85a1-e78bd624ba82.png">
