### ISSUE TITLE
Serious security vulnerability in dependency: highcharts < 8.1.1

### ISSUE THREAD

**Issue by telamonian** [finos/perspective#1106]
A serious XSS vulnerability was reported in highcharts a couple of weeks ago: https://snyk.io/vuln/SNYK-JS-HIGHCHARTS-571995. The recommended mitigation is to upgrade to at least highcharts@8.1.1. Currently, the `@finos/perspective-viewer-highcharts` package has the dependency:

https://github.com/finos/perspective/blob/7b319b7896e58d5860b72bd8756997976f9a7722/packages/perspective-viewer-highcharts/package.json#L59

**Comment by timkpaine** [comment]
closing, highchairs deprecated in favor of d3fc
