### ISSUE TITLE
does it need default imports of perspective-viewer 

### ISSUE THREAD

**Issue by Madasamy26** [finos/perspective#1107]
Hi,
While importing perspective-viewer..getting this message in browser like registering some of other widgets

How can we prevent this registering except  perspective-viewer? or other widgets needed for perspective-viewer ?

`Registered`
 `perspective-row`
`Registered perspective-autocomplete-widget`
` Registered perspective-expression-editor`
 `Registered perspective-computed-expression-widget`
`Registered perspective-viewer`

**Comment by sc1f** [comment]
These are internal viewer components that are automatically imported as part of the viewer.

**Comment by Madasamy26** [comment]
Ok @sc1f  thanks.
