### ISSUE TITLE
cannot import name 'Table' from 'perspective'

### ISSUE THREAD

**Issue by wayjeeair** [finos/perspective#1111]
Ran a 1 liner script on jupyterlab
> from perspective import Table

![Screenshot 2020-07-06 at 7 54 04 PM 1](https://user-images.githubusercontent.com/36558780/86590736-c6e9e780-bfc2-11ea-8b08-6cb504439122.png)

**Comment by sc1f** [comment]
We don’t have a Mac build for conda - you’re most likely pulling in the Linux distribution (that’s just my assumption based on #1108)

What do your install logs look like when you try to install through conda? What does perspective.__dict__ show?

**Comment by wayjeeair** [comment]
Yup, I installed on a Mac. Didn't have an issue installing via pip install. However, when running via CLI, I ran into C++ binding issues mentioned in the issues opened. Attempted to skip through the binding issue by using jupyter lab.

Here is the install log on the re-installation of the python package. I guess there is no way around the binding issue even while using jupyterlab?

Requirement` already satisfied: perspective-python in ./anaconda3/lib/python3.7/site-packages (0.4.1)
Requirement already satisfied: psutil>=5.4.8 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (5.6.7)
Requirement already satisfied: pyarrow==0.15.1 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (0.15.1)
Requirement already satisfied: zerorpc>=0.6.1 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (0.6.3)
Requirement already satisfied: traitlets>=4.3.2 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (4.3.3)
Requirement already satisfied: numpy>=1.13.1 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (1.18.1)
Requirement already satisfied: python-dateutil>=2.8.0 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (2.8.1)
Requirement already satisfied: ipywidgets>=7.5.1 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (7.5.1)
Requirement already satisfied: pandas>=0.22.0 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (1.0.1)
Requirement already satisfied: six>=1.11.0 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (1.14.0)
Requirement already satisfied: gevent>=1.1 in ./anaconda3/lib/python3.7/site-packages (from zerorpc>=0.6.1->perspective-python) (1.4.0)
Requirement already satisfied: future in ./anaconda3/lib/python3.7/site-packages (from zerorpc>=0.6.1->perspective-python) (0.18.2)
Requirement already satisfied: pyzmq>=13.1.0 in ./anaconda3/lib/python3.7/site-packages (from zerorpc>=0.6.1->perspective-python) (18.1.1)
Requirement already satisfied: msgpack>=0.5.2 in ./anaconda3/lib/python3.7/site-packages (from zerorpc>=0.6.1->perspective-python) (0.6.1)
Requirement already satisfied: ipython-genutils in ./anaconda3/lib/python3.7/site-packages (from traitlets>=4.3.2->perspective-python) (0.2.0)
Requirement already satisfied: decorator in ./anaconda3/lib/python3.7/site-packages (from traitlets>=4.3.2->perspective-python) (4.4.1)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in ./anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.5.1->perspective-python) (7.12.0)
Requirement already satisfied: ipykernel>=4.5.1 in ./anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.5.1->perspective-python) (5.1.4)
Requirement already satisfied: widgetsnbextension~=3.5.0 in ./anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.5.1->perspective-python) (3.5.1)
Requirement already satisfied: nbformat>=4.2.0 in ./anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.5.1->perspective-python) (5.0.4)
Requirement already satisfied: pytz>=2017.2 in ./anaconda3/lib/python3.7/site-packages (from pandas>=0.22.0->perspective-python) (2019.3)
Requirement already satisfied: greenlet>=0.4.14 in ./anaconda3/lib/python3.7/site-packages (from gevent>=1.1->zerorpc>=0.6.1->perspective-python) (0.4.15)
Requirement already satisfied: backcall in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.1.0)
Requirement already satisfied: appnope; sys_platform == "darwin" in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.1.0)
Requirement already satisfied: setuptools>=18.5 in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (46.0.0.post20200309)
Requirement already satisfied: jedi>=0.10 in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.14.1)
Requirement already satisfied: pygments in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (2.5.2)
Requirement already satisfied: pickleshare in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.7.5)
Requirement already satisfied: pexpect; sys_platform != "win32" in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (4.8.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (3.0.3)
Requirement already satisfied: tornado>=4.2 in ./anaconda3/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->perspective-python) (6.0.3)
Requirement already satisfied: jupyter-client in ./anaconda3/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->perspective-python) (5.3.4)
Requirement already satisfied: notebook>=4.4.1 in ./anaconda3/lib/python3.7/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (6.0.3)
Requirement already satisfied: jupyter-core in ./anaconda3/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.5.1->perspective-python) (4.6.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in ./anaconda3/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.5.1->perspective-python) (3.2.0)
Requirement already satisfied: parso>=0.5.0 in ./anaconda3/lib/python3.7/site-packages (from jedi>=0.10->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.5.2)
Requirement already satisfied: ptyprocess>=0.5 in ./anaconda3/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.6.0)
Requirement already satisfied: wcwidth in ./anaconda3/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.1.8)
Requirement already satisfied: Send2Trash in ./anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (1.5.0)
Requirement already satisfied: terminado>=0.8.1 in ./anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.8.3)
Requirement already satisfied: jinja2 in ./anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (2.11.1)
Requirement already satisfied: prometheus-client in ./anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.7.1)
Requirement already satisfied: nbconvert in ./anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (5.6.1)
Requirement already satisfied: attrs>=17.4.0 in ./anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5.1->perspective-python) (19.3.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in ./anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5.1->perspective-python) (1.5.0)
Requirement already satisfied: pyrsistent>=0.14.0 in ./anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5.1->perspective-python) (0.15.7)
Requirement already satisfied: MarkupSafe>=0.23 in ./anaconda3/lib/python3.7/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (1.1.1)
Requirement already satisfied: bleach in ./anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (3.1.0)
Requirement already satisfied: entrypoints>=0.2.2 in ./anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.3)
Requirement already satisfied: pandocfilters>=1.4.1 in ./anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (1.4.2)
Requirement already satisfied: defusedxml in ./anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.6.0)
Requirement already satisfied: mistune<2,>=0.8.1 in ./anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.8.4)
Requirement already satisfied: testpath in ./anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.4.4)
Requirement already satisfied: zipp>=0.5 in ./anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5.1->perspective-python) (2.2.0)
Requirement already satisfied: webencodings in ./anaconda3/lib/python3.7/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.5.1)

**Comment by sc1f** [comment]
Yeah, if you hit the binding issue it means you won't be able to import anything except `PerspectiveWidget`, which you should then be able to run in "client mode" as described [here](https://perspective.finos.org/docs/md/python.html#perspectivewidget).

If you run `import perspective` in Jupyterlab it'll give you the same error message as the one you saw in the CLI. We are in the process of distributing OSX wheels and fixing the conda build for Mac and Windows - what happens when you run `pip install -v perspective-python`? I can narrow down the issue from those logs and fix your build for now.

Sorry about the trouble installing!

**Comment by wayjeeair** [comment]
I had not much of an issue installing in the anaconda env. despite that, I am unable to import. hope my log would be helpful to you! would defo love to use the product in node, but im not too familiar with javascript. no worries, hope this works out!

Non-user install because site-packages writeable
Created temporary directory: /private/var/folders/0k/pl94dcf93gx0kc4s7hwtn9q40000gn/T/pip-ephem-wheel-cache-yzjbx54w
Created temporary directory: /private/var/folders/0k/pl94dcf93gx0kc4s7hwtn9q40000gn/T/pip-req-tracker-xdw3hafo
Initialized build tracking at /private/var/folders/0k/pl94dcf93gx0kc4s7hwtn9q40000gn/T/pip-req-tracker-xdw3hafo
Created build tracker: /private/var/folders/0k/pl94dcf93gx0kc4s7hwtn9q40000gn/T/pip-req-tracker-xdw3hafo
Entered build tracker: /private/var/folders/0k/pl94dcf93gx0kc4s7hwtn9q40000gn/T/pip-req-tracker-xdw3hafo
Created temporary directory: /private/var/folders/0k/pl94dcf93gx0kc4s7hwtn9q40000gn/T/pip-install-230flqn6
Requirement already satisfied: perspective-python in ./anaconda3/lib/python3.7/site-packages (0.4.1)
Requirement already satisfied: psutil>=5.4.8 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (5.6.7)
Requirement already satisfied: python-dateutil>=2.8.0 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (2.8.1)
Requirement already satisfied: six>=1.11.0 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (1.14.0)
Requirement already satisfied: traitlets>=4.3.2 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (4.3.3)
Requirement already satisfied: zerorpc>=0.6.1 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (0.6.3)
Requirement already satisfied: ipywidgets>=7.5.1 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (7.5.1)
Requirement already satisfied: pyarrow==0.15.1 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (0.15.1)
Requirement already satisfied: pandas>=0.22.0 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (1.0.1)
Requirement already satisfied: numpy>=1.13.1 in ./anaconda3/lib/python3.7/site-packages (from perspective-python) (1.18.1)
Requirement already satisfied: decorator in ./anaconda3/lib/python3.7/site-packages (from traitlets>=4.3.2->perspective-python) (4.4.1)
Requirement already satisfied: ipython-genutils in ./anaconda3/lib/python3.7/site-packages (from traitlets>=4.3.2->perspective-python) (0.2.0)
Requirement already satisfied: gevent>=1.1 in ./anaconda3/lib/python3.7/site-packages (from zerorpc>=0.6.1->perspective-python) (1.4.0)
Requirement already satisfied: msgpack>=0.5.2 in ./anaconda3/lib/python3.7/site-packages (from zerorpc>=0.6.1->perspective-python) (0.6.1)
Requirement already satisfied: future in ./anaconda3/lib/python3.7/site-packages (from zerorpc>=0.6.1->perspective-python) (0.18.2)
Requirement already satisfied: pyzmq>=13.1.0 in ./anaconda3/lib/python3.7/site-packages (from zerorpc>=0.6.1->perspective-python) (18.1.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in ./anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.5.1->perspective-python) (3.5.1)
Requirement already satisfied: ipykernel>=4.5.1 in ./anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.5.1->perspective-python) (5.1.4)
Requirement already satisfied: nbformat>=4.2.0 in ./anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.5.1->perspective-python) (5.0.4)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in ./anaconda3/lib/python3.7/site-packages (from ipywidgets>=7.5.1->perspective-python) (7.12.0)
Requirement already satisfied: pytz>=2017.2 in ./anaconda3/lib/python3.7/site-packages (from pandas>=0.22.0->perspective-python) (2019.3)
Requirement already satisfied: greenlet>=0.4.14 in ./anaconda3/lib/python3.7/site-packages (from gevent>=1.1->zerorpc>=0.6.1->perspective-python) (0.4.15)
Requirement already satisfied: notebook>=4.4.1 in ./anaconda3/lib/python3.7/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (6.0.3)
Requirement already satisfied: jupyter-client in ./anaconda3/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->perspective-python) (5.3.4)
Requirement already satisfied: appnope; platform_system == "Darwin" in ./anaconda3/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->perspective-python) (0.1.0)
Requirement already satisfied: tornado>=4.2 in ./anaconda3/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->perspective-python) (6.0.3)
Requirement already satisfied: jupyter-core in ./anaconda3/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.5.1->perspective-python) (4.6.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in ./anaconda3/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.5.1->perspective-python) (3.2.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (4.8.0)
Requirement already satisfied: setuptools>=18.5 in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (46.0.0.post20200309)
Requirement already satisfied: backcall in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.1.0)
Requirement already satisfied: jedi>=0.10 in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.14.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (3.0.3)
Requirement already satisfied: pickleshare in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.7.5)
Requirement already satisfied: pygments in ./anaconda3/lib/python3.7/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (2.5.2)
Requirement already satisfied: jinja2 in ./anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (2.11.1)
Requirement already satisfied: nbconvert in ./anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (5.6.1)
Requirement already satisfied: Send2Trash in ./anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (1.5.0)
Requirement already satisfied: prometheus-client in ./anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.7.1)
Requirement already satisfied: terminado>=0.8.1 in ./anaconda3/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.8.3)
Requirement already satisfied: attrs>=17.4.0 in ./anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5.1->perspective-python) (19.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in ./anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5.1->perspective-python) (0.15.7)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in ./anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5.1->perspective-python) (1.5.0)
Requirement already satisfied: ptyprocess>=0.5 in ./anaconda3/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.6.0)
Requirement already satisfied: parso>=0.5.0 in ./anaconda3/lib/python3.7/site-packages (from jedi>=0.10->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.5.2)
Requirement already satisfied: wcwidth in ./anaconda3/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->perspective-python) (0.1.8)
Requirement already satisfied: MarkupSafe>=0.23 in ./anaconda3/lib/python3.7/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (1.1.1)
Requirement already satisfied: entrypoints>=0.2.2 in ./anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.3)
Requirement already satisfied: bleach in ./anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (3.1.0)
Requirement already satisfied: mistune<2,>=0.8.1 in ./anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.8.4)
Requirement already satisfied: pandocfilters>=1.4.1 in ./anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (1.4.2)
Requirement already satisfied: defusedxml in ./anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.6.0)
Requirement already satisfied: testpath in ./anaconda3/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.4.4)
Requirement already satisfied: zipp>=0.5 in ./anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5.1->perspective-python) (2.2.0)
Requirement already satisfied: webencodings in ./anaconda3/lib/python3.7/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->perspective-python) (0.5.1)
Cleaning up...
Removed build tracker: '/private/var/folders/0k/pl94dcf93gx0kc4s7hwtn9q40000gn/T/pip-req-tracker-xdw3hafo'

**Comment by timkpaine** [comment]
We've made some improvements in this space in https://github.com/finos/perspective/pull/1193 and https://github.com/finos/perspective/pull/1163
