### ISSUE TITLE
Lazy loading with perspective-python backend

### ISSUE THREAD

**Issue by Yuri2b** [finos/perspective#1113]
Does exist a way to provide lazy loading of data from perspective-python backend?
When I use remote Perspective via perspective-python and Tornado server as in example:

```python
from perspective import Table, PerspectiveManager, PerspectiveTornadoHandler
import tornado.ioloop
import tornado.web

# Create an instance of PerspectiveManager, and host a Table
MANAGER = PerspectiveManager()

TABLE = Table(large_dataset)
VIEW_2015 = TABLE.view(filter=[["Year", "==", "2015"]])

MANAGER.host_view("view_2015", VIEW_2015)

app = tornado.web.Application([
    # create a websocket endpoint that the client Javascript can access
    (r"/websocket", PerspectiveTornadoHandler, {"manager": MANAGER, "check_origin": True})
])

# Start the Tornado server
app.listen(8888)
loop = tornado.ioloop.IOLoop.current()
loop.start()
```
and on my frontend load this VIEW:

```javascript
perspectiveViewer.load(websocket.open_view("view_2015"))
```
Is there a way to make immediate render of visible rows (or some first chunk of data) and load rest data in background (or by user scroll events)?

My dataset that pushing to browser through websocket is ~135Mb, and I need to wait all this data before see any rows.

**Comment by sc1f** [comment]
For larger datasets, use `host_table` and `websocket.open_table`. The user will get whatever data they are currently seeing, i.e. whatever is rendered in the grid.

We're working on a smoother/faster API for hosted views and large datasets.

**Comment by Yuri2b** [comment]
Now it's really blazing fast! Thank you

**Comment by sc1f** [comment]
No problem - glad to hear it!

**Comment by pony010** [comment]
If my server only has 1G, large_dataset is 4G, Could I  use `TABLE = Table(large_dataset)`?

**Comment by pony010** [comment]
I have large data using feather format，It's out of memory, how to transform `Table`?
