### ISSUE TITLE
perspective viewer notifyResize() api doesnt work!

### ISSUE THREAD

**Issue by Madasamy26** [finos/perspective#1117]
Hi,
I have developing own plugin for perspective, 
from perspepective viewer I am invoking 

`viewer.notifyresize() ` but idoesnt invoke my plugin code for resize which I have configured

`global.registerPlugin(viewRef.plugin.type, {
        ...viewRef.plugin,
        selectMode: "toggle",
        deselectMode: "pivots",
        create: drawView(viewRef),
        update: update,
        resize: resizeView,
        save: save,
        restore: restoreView,
        delete: deleteView
    });`

any help would be appreciated!.

**Comment by texodus** [comment]
Thanks for the report!

These plugin API functions are `async` (or `Promise()` returning), which are notorious for swallowing errors - perhaps your `resizeView` is throwing an exception that is uncaught?  The supplied snippet trivially invokes `resizeView = x => console.log(x)` for me, and the functionality itself is somewhat cornerstone to all resize scenarios, so I'd be surprised if it simply did not work, though there may be bugs;  if you have a more complete repro, feel free to re-open and I can take a look.
