### ISSUE TITLE
Developer Guide seems out of date on emscripten version.

### ISSUE THREAD

**Issue by breakds** [finos/perspective#1121]
## Support Question

Checking the [current DOCKERFILE](https://github.com/finos/perspective/blob/master/docker/emsdk/Dockerfile), the project is now using emscripten 1.39.13. However, in the developer guide https://perspective.finos.org/docs/md/development.html it still states 

>  We currently use Emscripten version 1.38.47 — deviating from this specific version of Emscripten can introduce various errors that are extremely difficult to debug.

Suggest updating that. Thanks!

**Comment by texodus** [comment]
Thanks for the report - this has been fixed!
