### ISSUE TITLE
Inconsistent behavior for Pandas pivot tables

### ISSUE THREAD

**Issue by pgagarinov** [finos/perspective#1122]
### Steps to Reproduce:
 1.
```
arrays = {'A':['bar', 'bar', 'bar', 'bar', 'baz', 'baz', 'baz', 'baz', 'foo', 'foo', 'foo', 'foo', 'qux', 'qux', 'qux', 'qux'],
          'B':['one', 'one', 'two', 'two', 'one', 'one', 'two', 'two', 'one', 'one', 'two', 'two', 'one', 'one', 'two', 'two'],
          'C':['X', 'Y', 'X', 'Y', 'X', 'Y', 'X', 'Y', 'X', 'Y', 'X', 'Y', 'X', 'Y', 'X', 'Y'],
          'D':np.arange(16)}

df = pd.DataFrame(arrays)
df
```

<img width="185" alt="image" src="https://user-images.githubusercontent.com/4868370/87513731-d67fc500-c681-11ea-86ee-a5b95bf26c16.png">

 2. 
```
df_pivot=df.pivot_table(values=['D'], index=['A'], columns=['B','C'], aggfunc={'D':'count'})
df_pivot
```
<img width="102" alt="image" src="https://user-images.githubusercontent.com/4868370/87513783-ed261c00-c681-11ea-93af-01f62ac40fe6.png">

 3. 
```
psp = PerspectiveWidget(df_pivot)
psp
```
<img width="533" alt="image" src="https://user-images.githubusercontent.com/4868370/87513857-07f89080-c682-11ea-9679-caaae7d51e4a.png">

4.
Remove "index" from groupBy and move "A" from "splitBy" to "groupBy":
<img width="481" alt="image" src="https://user-images.githubusercontent.com/4868370/87514008-41c99700-c682-11ea-9978-d4fd6ab3a937.png">

### Expected Result:

I expected

```
df_pivot=df.pivot_table(values=['D'], index=['A'], columns=['B','C'], aggfunc={'D':'count'})
widget= PerspectiveWidget(df_pivot)
```
to give the same result as
```
widget = PerspectiveWidget(df, row_pivots=['A'], column_pivots=['B','C'],aggregates={'D':'count'},columns=['D'])
```
which is
<img width="534" alt="image" src="https://user-images.githubusercontent.com/4868370/87567144-9bef4a00-c6cc-11ea-87bf-031fb59a5ba6.png">

which is closest to the pandas' result:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/4868370/87567455-f7b9d300-c6cc-11ea-9741-588ceb5c31fd.png">

### Actual Result:
For some reason perspective puts both row_pivots and column_pivots from Pands pivoted dataframe to splitBy group.

### Environment:
perspective 0.5.1 installed via 
```
conda install -c conda-forge perspective
```
pandas 1.0.5 and numpy 1.18.5 from conda-forge.

**Comment by timkpaine** [comment]
For both this and #1123, perspective is just providing a convenience layer. We flatten the dataframe and reconstruct the pivots [here](https://github.com/finos/perspective/blob/master/python/perspective/perspective/core/data/pd.py#L52) . It is almost always going to be better to provide perspective the flat dataframe in the first place and to build the pivots directly in perspective.

**Comment by timkpaine** [comment]
@pgagarinov so this is the view you want but with `A` instead of `index`? Looks like a simple bug where the index name isn't necessarily being matched with the index itself. 
<img width="575" alt="Screen Shot 2020-07-15 at 10 55 23 AM" src="https://user-images.githubusercontent.com/3105306/87560694-bbb14e80-c689-11ea-8f97-cc5b2e85f6b1.png">

**Comment by pgagarinov** [comment]
>For both this and #1123, perspective is just providing a convenience layer. We flatten the dataframe and reconstruct the pivots >here . It is almost always going to be better to provide perspective the flat dataframe in the first place and to build the pivots >directly in perspective.

Got it, thanks for the explanation!

> @pgagarinov so this is the view you want but with `A` instead of `index`? Looks like a simple bug where the index name isn't necessarily being matched with the index itself.

Not exactly. I expected

```
df_pivot=df.pivot_table(values=['D'], index=['A'], columns=['B','C'], aggfunc={'D':'count'})
widget= PerspectiveWidget(df_pivot)
```
to give the same result as
```
widget = PerspectiveWidget(df, row_pivots=['A'], column_pivots=['B','C'],aggregates={'D':'count'},columns=['D'])
```
which is
<img width="534" alt="image" src="https://user-images.githubusercontent.com/4868370/87567144-9bef4a00-c6cc-11ea-87bf-031fb59a5ba6.png">

which is closest to the pandas' result:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/4868370/87567455-f7b9d300-c6cc-11ea-9741-588ceb5c31fd.png">

**Comment by timkpaine** [comment]
I think im just going to rewrite this to be cleaner, its a bit complicated unstacking stuff and leads to some incorrect results
