### ISSUE TITLE
Non-blockable Table.update() method with Tornado Server

### ISSUE THREAD

**Issue by Yuri2b** [finos/perspective#1124]
Hello. I am using example code from documentation and hosting couple of Tables on my server-side by Tornado Server. When I'm trying to update data in table, or making sorting, pivoting, etc i getting stuck on all clients connected to this server. Clients don't receive any data from websocket until that updating or filtration has done.
How can I make these operations asynchronously?
Is there in Class `_PerspectiveStateManager` and `queue_process` method standard behavior? How can I overwrite it to archive concurrency?
Or I should overwrite `PerspectiveTornadoHandler` Class methods?

**Comment by texodus** [comment]
Thanks for the report!

GIL-less operation has been added in `v0.5.5` via `perspective.set_event_loop()`, see [docs](https://perspective.finos.org/docs/md/python.html#async-mode) or this [example](https://github.com/finos/perspective/blob/master/examples/tornado-python/server.py#L30) for more details.  It should no longer be possible to timeout clients in this manner, please feel free to re-open with more details if you find this not to be the case.
