### ISSUE TITLE
Python example remote.py/remote.html doesn't work in Firefox

### ISSUE THREAD

**Issue by pgagarinov** [finos/perspective#1128]
### Steps to Reproduce:
 1. run `remote.py` script from `python\perspective\examples` subfolder (I had to remove `#sys.path.insert(1, os.path.join(os.path.dirname(__file__), '..'))` line though as it is not necessary if perspective from conda-forge is used

 2. try to open `http://localhost:8888` in Firefox
page opens but no data is shown

 3. open the console to see the following
<img width="887" alt="image" src="https://user-images.githubusercontent.com/4868370/87801205-0e406580-c858-11ea-84b6-13b30b72f5b7.png">

### Expected Result:
In chrome-based browsers (tested in Brave) everything works

### Environment
Firefox 78.0.1
Perspective 0.5.1 from conda-forge

**Comment by timkpaine** [comment]
1. is required for a local development build so not an issue

**Comment by texodus** [comment]
Can't repro, this has likely bit-rotted. In general, while I do want to fix any obvious errors on web platforms like Firefox, as we cannot currently run our test suite on this platform, it is not technically supported.
