### ISSUE TITLE
PerspectiveWidget in JupyterLab uses different plugins than browser defaults

### ISSUE THREAD

**Issue by pgagarinov** [finos/perspective#1129]
### Directly in the browser (Brave 1.9.69)
<img width="151" alt="image" src="https://user-images.githubusercontent.com/4868370/87804240-434eb700-c85c-11ea-8a7a-6c6663975525.png">

### Perspective Widget (Brave)

<img width="244" alt="image" src="https://user-images.githubusercontent.com/4868370/87804609-ca039400-c85c-11ea-8019-3e52ce947981.png">

### PerspectiveWidget (Firefox)
<img width="159" alt="image" src="https://user-images.githubusercontent.com/4868370/87804194-316d1400-c85c-11ea-860c-46173ad40cda.png">

As we can see, it is "Grid" vs "Datagrid" and "Heatmap" is at different positions in the list.
Finally, the look of the list in Brave browser is not perfect (light gray font on a white background doesn't look good).

### Environment
Brave 1.9.69 
Firefox 78.0.1

**Comment by timkpaine** [comment]
This is not a bug, they use different plugins [here](https://github.com/finos/perspective/blob/master/packages/perspective-jupyterlab/src/ts/index.ts#L19)

**Comment by timkpaine** [comment]
we don't support Brave, though we likely do support whatever browser its based on so its interesting to note (feel free to make a separate issue for it).

**Comment by pgagarinov** [comment]
@timkpaine ok, they use different plugins but why can perspective just use the same names? What is the point of using the different names and placing "Heatmap" to a different position? It just confuses users and makes it more difficult to test things in JupyterLab

@timkpaine I suspect the pale look of the dropdown menu is there for most of Chromium-based browser (I also checked in Chromium), same problem.

**Comment by timkpaine** [comment]
> @timkpaine ok, they use different plugins but why can't perspective just use the same names? What is the point of using the different names and placing "Heatmap" to a different position? It just confuses users and makes it more difficult to test things in JupyterLab

Perspective for JupyterLab uses highcharts plugin which has them in one order, browser uses d3fc which has them in another order. 

[highcharts](https://github.com/finos/perspective/blob/master/packages/perspective-viewer-highcharts/src/js/highcharts/highcharts.js#L208)
[d3fc](https://github.com/finos/perspective/blob/master/packages/perspective-viewer-d3fc/src/js/plugin/plugin.js#L27)

Im ambivalent about the ordering, but I agree it could be confusing for some. I'll make a separate issue for maybe sorting them prior to registering
