### ISSUE TITLE
Dates are not displayed correctly in columns (but just fine in rows)

### ISSUE THREAD

**Issue by pgagarinov** [finos/perspective#1131]
### Steps to Reproduce:
 1. 
Run `python remote_bug4.py` from the attached zip archive
[date_column_bug.zip](https://github.com/finos/perspective/files/4938798/date_column_bug.zip)

 2. open `http://localhost:8888` in the browser and observe the following

<img width="888" alt="image" src="https://user-images.githubusercontent.com/4868370/87807221-ac382e00-c860-11ea-9fb1-82c14df9c2ea.png">

 3. Press on 
<img width="41" alt="image" src="https://user-images.githubusercontent.com/4868370/87807261-b8bc8680-c860-11ea-8c6a-0e119a6e245a.png">

and see the following

<img width="306" alt="image" src="https://user-images.githubusercontent.com/4868370/87807283-c1ad5800-c860-11ea-989e-013b2f718073.png">

### Environment
Perspective 0.5.1

**Comment by texodus** [comment]
Thanks for the report!   A fix for this has been released in 0.5.3
