### ISSUE TITLE
Heatmap datetime pivots show POSIX timestamps and not formatted datetimes

### ISSUE THREAD

**Issue by sc1f** [finos/perspective#1144]
### Steps to Reproduce:
 1. Open superstore.html
 2. Create a treemap pivoted by "Ship Date" or "Order Date"

### Expected Result:
Text in each treemap block should be the formatted datetime, as shown in the tooltip (screenshot below).

### Actual Result:
Text in treemap blocks are unformatted posix timestamps, which means we're missing a coercion to `new Date()` somewhere:

![Screen Shot 2020-07-30 at 11 04 58 AM](https://user-images.githubusercontent.com/13220267/88939753-e805c700-d254-11ea-92f2-332c60f4c323.png)

Tooltips seem to work fine here though.

### Environment:
Latest master build.

**Comment by texodus** [comment]
Fixed in #1165
