### ISSUE TITLE
How can one control the number of TBB threads being used? ( perspective-python )

### ISSUE THREAD

**Issue by robambalu** [finos/perspective#1145]
While trying out perspective-python we noticed our CPU usage skyrocketed to use almost all 36 cores on our box.
Profiling one of those threads shows TBB as the top hitter
  47.97%  python   libtbb.so            [.] tbb::internal::rml::private_worker::run
  20.77%  python   libtbb.so            [.] tbb::internal::rml::private_server::wake_some
  17.21%  python   libtbb.so            [.] tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::receive_or_steal_task
...

we dont use tbb in our code and i see TBB is used in perspective.  Is there a way to control how many cores are dedicated here?

**Comment by timkpaine** [comment]
This is more of a question for intel, does `TBB_NUM_THREADS` env var work?

**Comment by timkpaine** [comment]
alternatively we can make it a parameter and implement this:
`tbb::global_control c(tbb::global_control::max_allowed_parallelism, nthreads)`

**Comment by robambalu** [comment]
configuration option would be preferable to env var if thats doable

**Comment by texodus** [comment]
Thanks @robambalu and @timkpaine  - I've added `set_threadpool_size()`method which allows specifying the TBB threadpool size, it will be released in `v0.5.3`.

**Comment by robambalu** [comment]
great thank you!
