### ISSUE TITLE
Perspective python install failure - CentOS 7

### ISSUE THREAD

**Issue by ananis25** [finos/perspective#1146]
## Bug Report
Building the perspective-python wheel fails on a CentOS 7 machine. 

### Steps to Reproduce:
 1. pip install pyarrow==0.16.0
 2. pip install -v perspective-python

### Actual Result:
Error logs attached. It looks to be a build error of the C++ package. 
[perspective.log.txt](https://github.com/finos/perspective/files/5010454/perspective.log.txt)

### Environment:
```
$ cat /etc/centos-release
CentOS Linux release 7.8.2003 (Core)

$ python --version
Python 3.7.6

$ pip --version
pip 20.2 from /home/ananis/py376/lib/python3.7/site-packages/pip (python 3.7)

$ pip show pyarrow
Name: pyarrow
Version: 0.16.0
Summary: Python library for Apache Arrow
Home-page: https://arrow.apache.org/
Author: None
Author-email: None
License: Apache License, Version 2.0

$ cmake --version
cmake3 version 3.17.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
```

### Additional Context:
I'm curious if there are any other system dependencies besides CMake, TBB and pybind before attempting to install the perspective package.

**Comment by sc1f** [comment]
Your version of Boost (1.53) is too old - we have a dependency on Boost >= 1.67. It's listed, albeit in the Javascript section of the developer docs: https://perspective.finos.org/docs/md/development.html

We are absolutely overdue for a docs overhaul.

**Comment by ananis25** [comment]
Thank you, I definitely went through the developer docs section but somehow overlooked the boost version.
