### ISSUE TITLE
Webpack Example Has Layout Glitch

### ISSUE THREAD

**Issue by hediet** [finos/perspective#1150]
### Steps to Reproduce:
Like #1149, but fixing the less problem by adding this rule and installing `less-loader`:
```js
{
        test: /\.less$/,
        loaders: ["style-loader", "css-loader", "less-loader"],
},
```

### Expected Result:
It should look like this (but in white theme):

![image](https://user-images.githubusercontent.com/2931520/89531100-f5d8c080-d7ef-11ea-9921-02f8cba42246.png)

### Actual Result:
It actually looks like this:

![image](https://user-images.githubusercontent.com/2931520/89531149-0d17ae00-d7f0-11ea-9f81-a547e917f17b.png)

Note how the three dots overlap the column. This does not look nice.

Otherwise, a great library! Thanks for offering it for free!

**Comment by texodus** [comment]
Try using the provided [Material theme](https://github.com/finos/perspective/blob/master/examples/webpack/src/index.js#L16) which pads the plugin by 24px, or try using this as an example to develop your own Theme, where you can completely control the appearance and position of the config button.

**Comment by hediet** [comment]
Thanks for your reply!

Without
```ts
import "@finos/perspective-viewer/dist/umd/material.css";
```
It looks like this:
![image](https://user-images.githubusercontent.com/2931520/90115978-24591d00-dd55-11ea-913a-8e4d3b8acd54.png)

With it, it looks like this:
![image](https://user-images.githubusercontent.com/2931520/90116075-3e92fb00-dd55-11ea-9f37-e2406762c34b.png)

So it has some effect, but it does not help...
