### ISSUE TITLE
How to Customizing behavior of perspective with perspective.config.js

### ISSUE THREAD

**Issue by Madasamy26** [finos/perspective#1151]
I have read in documentation https://perspective.finos.org/docs/md/js.html#customizing-behavior-with-perspectiveconfigjs

I am using with nodejs without @finos/perspective-webpack-plugin 

I have created perspective.config.js in project folder but its not overriding !!!

any help would be appreciated!

**Comment by texodus** [comment]
Thanks for the report!

You can't apply a config without using `@finos/perspective-webpack-plugin` .. but this config only applies to `@finos/perspective-viewer` browser frontend, so not clear what exactly you're trying to achieve.  Maybe try following the `Issues` template provided to open a new issue explaining to us in detail what you're trying to achieve and what you've already tried?

**Comment by Madasamy26** [comment]
Yes, I am trying to override config on  @finos/perspective-viewer browser frontend,
but the difference is without using @finos/perspective-webpack-plugin, I am currently using perspective in  Inline mode
