### ISSUE TITLE
view stops updating

### ISSUE THREAD

**Issue by adpoint72** [finos/perspective#1152]
Using perspective-viewer with websocket, view stops updating after sometime.  I see the following exception in the console (not sure if it is related).  After this happens, resizing the window will update values in the grid but will not do live updates.

utils.js:182 TypeError: Cannot read property 'column_paths' of undefined
    at HTMLElement.draw (scroll_panel.js:384)
    at HTMLElement.i.value (utils.js:180)
    at HTMLElement.update (index.js:59)
    at perspective_element.js:393

**Comment by sc1f** [comment]
Your websocket on the server might be timing out. Set `websocket_ping_interval` in your tornado application, as this example does: https://github.com/finos/perspective/blob/master/python/perspective/examples/client_server_edits.py#L44

It *should* keep it open perpetually, but if it keeps happening let us know when it times out and I'll investigate further.

**Comment by adpoint72** [comment]
thanks, will try

**Comment by robambalu** [comment]
what version of tornado are you using? I cant find that option on our version nor in any tornado docs

**Comment by robambalu** [comment]
nm disreagrd

**Comment by adpoint72** [comment]
we tried websocket_ping_interval=15 but it didn't help.  still freezes if the grid is not interacted with.  refreshing or adding/removing columns brings it back to live

**Comment by texodus** [comment]
Thanks for the report!  We've merged a few patches recently that should make the `PerspectiveTornadoHandler` impervious to this type of websocket timeout:
 * #1198 adds the `perspective.set_loop_callback()` function, which will allows Perspective to release the GIL when run on an event loop.  In this mode, `tornado` can respond to other network and application events, while a `PerspectiveManager` on a dedicated thread pool is processing.  More details can be found in the [docs](https://perspective.finos.org/docs/md/python.html#async-mode), also a simple [example](https://github.com/finos/perspective/blob/master/examples/tornado-python/server.py#L30)
* #1209 adds `chunk_size` kwarg to `PerspectiveTornadoHandler`, which breaks up large Apache Arrow websocket messages in chunks when a response is large.

The former change has been released in `v0.5.5`, the latter will be released in `v0.5.6`.  As the report doesn't provide a specific repro, I am going to mark this as closed for now.  Please give these updates a shot - if they do not resolve your issue, feel free to re-open with more detail or a repro for your specific case (as per template).
