### ISSUE TITLE
CMake picking up different paths for Python executable, libs, includes, not respecting version var

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#1162]
I noticed when running in virtual envs, CMake isn't respecting some vars. I believe this is causing the link issues when installing

**Comment by pgagarinov** [comment]
@timkpaine In your opinion, can this problem be responsible for #1120?

**Comment by timkpaine** [comment]
@pgagarinov yes see https://github.com/finos/perspective/pull/1163
