### ISSUE TITLE
Date64Type demotes to date when table is initialized with arrow format

### ISSUE THREAD

**Issue by TimeWanderer** [finos/perspective#1189]
### Steps to Reproduce:
 1. Create arrow formatted data with date fields. Dates should be Date64Type, meaning unit=1 or i.e DateUnit.Milliseconds.
 2. Load data to a perspective table
 3. Inspect Date field

### Expected Result:
Date field's type should be 'datetime'.
### Actual Result:
The observed type is 'date'.

### Environment:
Window 10 Home, Chrome Version 85.0.4183.83 (Official Build) (64-bit), Data generated both under JS apache-arrow and apache arrow csharp implementations, v17.0.

### Additional Context:
You can find a sample code [here](https://codesandbox.io/s/naughty-cookies-15ky7?file=/src/index.js). I played around in the chrome console to see the results by loading the arrow binary from the arrow table to the perspective table.

**Comment by sc1f** [comment]
We currently only treat `arrow::TimestampType` as a `datetime`,  and we treat `Date64Type ` and `Date32Type` as `date` as the Arrow docs call it a ["type class for 64-bit date data"](https://arrow.apache.org/docs/cpp/api/datatype.html#_CPPv4N5arrow10Date64TypeE) as opposed to ["class for datetime data"](https://arrow.apache.org/docs/cpp/api/datatype.html#_CPPv4N5arrow13TimestampTypeE) for `TimestampType`.

There is currently no facility for updating a Table with a datetime schema with date64/date32, or vice versa from timestamp to date. Is it possible to cast your data as a timestamp?

**Comment by TimeWanderer** [comment]
I believe it is. I will try and get back to you as soon as possible.

**Comment by TimeWanderer** [comment]
It works as intended. Thanks for your help.
