### ISSUE TITLE
Composing filters with 'or'

### ISSUE THREAD

**Issue by TimeWanderer** [finos/perspective#1192]
## Support Question

Is it possible to compose different filter conditions with 'or'. For example, I want to have a filter definition like this:
[[["Freq", "<", 10], 'or', ["Freq", ">", 90]]]

If not so, is this a feature that may be implemented?

**Comment by kryaksy** [comment]
Similar question. How about "between" and "not between"?

**Comment by timkpaine** [comment]
@kryaksy "between" and "not between" reduces to "and" and "or"

**Comment by TimeWanderer** [comment]
@timkpaine AFAIK, there are no filters "between" and "not between". I believe @kryaksy was asking whether those filters could be implemented or not as a feature.

**Comment by kryaksy** [comment]
@TimeWanderer That's right. Also I don't want to spoil the main question above. It would be useful if there are "and", "or" operators for numeric filtering.

**Comment by timkpaine** [comment]
Between is " > small and < large" and not between is " < small or > large"

**Comment by smalltalk96** [comment]
"in" operator is also required

**Comment by TimeWanderer** [comment]
@timkpaine 'or' has wider implications than just the numeric comparison filter, and in some cases, they are not reducible to other filter compositions.

**Comment by timkpaine** [comment]
> @timkpaine 'or' has wider implications than just the numeric comparison filter, and in some cases, they are not reducible to other filter compositions.

I haven't said anything about 'or', only that between and not between is reducible to operations composed of 'and' and 'or'

**Comment by texodus** [comment]
This (as well as arbitrary row-wide filter conditions) has been supported since ~`0.10` or so via ExprTK expressions of `boolean` type.  Example

```javascript
{
    "expressions": ["\"Sales\" > 100 or \"Profit\" < 0"],
    "filter": [["\"Sales\" > 100 or \"Profit\" < 0", "==", true]],
    // ...
}
