### ISSUE TITLE
CDN installation example fails on unresolvable dependency

### ISSUE THREAD

**Issue by Tomtomgo** [finos/perspective#1206]
I'm trying to prototype an example application using Perspective. As it seems the simplest to get an example running, I fetch it via CDN.

I followed the steps lined out in the [docs](https://perspective.finos.org/docs/md/installation.html#from-cdn), leading to this:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pivot 👍</title>

    <script src="https://unpkg.com/@finos/perspective"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer-datagrid"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer-d3fc"></script>
</head>
<body>
    <perspective-viewer id='pivot-table' columns='["Sales", "Profit"]'>
        <script>
            document.addEventListener("WebComponentsReady", function () {
                const data = {
                    Sales: [500, 1000, 1500],
                    Profit: [100.25, 200.5, 300.75]
                };
                // The `<perspective-viewer>` HTML element exposes the viewer API
                const el = document.getElementById("pivot-table");
                el.load(data);
            });
        </script>
    </perspective-viewer>
</body>
</html>
```

It seems the example is somehow broken.

When loading this page in Chrome, the following errors appear:

<img width="1669" alt="Screenshot 2020-09-25 at 17 04 58" src="https://user-images.githubusercontent.com/1175923/94283554-747cef00-ff51-11ea-9baa-8f2232e27602.png">

It seems somehow the URI to fetch dependencies is not properly constructed.

What can I do about this?

**Comment by sc1f** [comment]
@texodus looks like the WASM lookup is broken in all CDN alias links - #1141 doesn't seem to be working for unpkg and JSDelivr, when `@finos/perspective` is loaded. It seems to work fine when workspace/viewer is loaded, which means it is probably resolving the paths to the bundled WASM assets with viewer/workspace.

@Tomtomgo you should be able to run the example by removing `<script src="https://unpkg.com/@finos/perspective"></script>`, which will allow `@finos/perspective-viewer` to resolve WASM assets properly. 

You should also be able to load a direct link to the `.js` assets, instead of using the alias links:

```javascript
<script src="https://cdn.jsdelivr.net/npm/@finos/perspective/dist/umd/perspective.js"></script>
```

**Comment by Tomtomgo** [comment]
Thanks @sc1f! I managed to get the sample working like this:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pivot 👍</title>

    <script src="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer@0.5.5/dist/umd/perspective-viewer.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer-datagrid@0.5.5/dist/umd/perspective-viewer-datagrid.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer-d3fc@0.5.5/dist/umd/perspective-viewer-d3fc.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer@0.5.5/dist/umd/material.css" type="text/css"/>

    <style>
        perspective-viewer {
            position: absolute !important;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
        }
    </style>
</head>
<body>
<perspective-viewer id='pivot-table' columns='["Sales", "Profit"]'/>
<script>
    document.addEventListener("WebComponentsReady", function () {
        const data = {
            Sales: [500, 1000, 1500],
            Profit: [100.25, 200.5, 300.75]
        };
        // The `<perspective-viewer>` HTML element exposes the viewer API
        const el = document.getElementById("pivot-table");
        el.load(data);
    });
</script>
</body>
</html>
```

Some notes in case you're interested, I had to:

- add absolute positioning and 0 top/left/right/bottom for the `perspective-viewer` to actually display
- replace `"['Sales', 'Profit']"` with `'["Sales", "Profit"]'` (mind the quotes)

**Comment by texodus** [comment]
Closing as this appears resolved for now (though I'm always interested in improving our packaging metadata).
