### ISSUE TITLE
Jupyter integration demo

### ISSUE THREAD

**Issue by david542542** [finos/perspective#1210]
## Support Question

Possible to add a jupyter demo on the [examples page](https://github.com/finos/perspective/#examples)? Would be really neat to see how it could be integrated, perhaps something that is already-hosted such as: http://colab.research.google.com/

**Comment by timkpaine** [comment]
We don't support colab but there are docs and images in the docs page https://perspective.finos.org/docs/md/installation.html#jupyterlab

**Comment by david542542** [comment]
@timkpaine thanks for the quick response. 

I was just saying it would be great to see/play around with a demo from the examples page (and just put a simple one on a server or cloud-hosted jupyter service or whatever -- colab doesn't matter). I tried building Jupyter locally (with Anaconda) and it wasn't playing nice with imports, so tried a few of the cloud-hosted jupyter notebooks, and couldn't get it to run, and after about an hour I just thought "it would be great if there was a demo on the site to see how it actually works and how it'd be useful integrating with jupyter."

But yes, the docs are good and any competent developer should be able to build from it. I just think it'd be great to have yet one more additional example to show it with Jupyter. Cheers.

**Comment by timkpaine** [comment]
The python training binder link has perspective built and installed I believe

https://github.com/jpmorganchase/python-training

We can probably add a binder link to this project as well. I doubt we'll have colab anytime soon but jupyterlab on binder sounds reasonable.

**Comment by texodus** [comment]
@timkpaine has added a link to this on the [Perspective `README.md`](https://github.com/finos/perspective)!

**Comment by david542542** [comment]
Awesome, thanks!
