### ISSUE TITLE
Referencing perspective-workspace from index.html complains about perspective-row being already used

### ISSUE THREAD

**Issue by pgagarinov** [finos/perspective#1218]
### Steps to Reproduce:
my index.html looks like this:
```

<html>
<head>
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
    <link rel='stylesheet' href="https://unpkg.com/@finos/perspective-viewer@0.5.5/dist/umd/material-dense.dark.css">
    <script src="https://unpkg.com/@finos/perspective@0.5.5"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer@0.5.5"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer-datagrid@0.5.5"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer-d3fc@0.5.5"></script>
    <script src="https://unpkg.com/@finos/perspective-workspace@0.5.5"></script>
```
and I run the server from Python:

`class MainHandler(tornado.web.RequestHandler, ABC):
    def set_default_headers(self):
        self.set_header("Access-Control-Allow-Origin", "*")
        self.set_header("Access-Control-Allow-Headers", "x-requested-with")
        self.set_header('Access-Control-Allow-Methods', 'POST, GET, OPTIONS')

    def get(self):
        self.render("index.html", listening_ip=LISTENING_IP, listening_port=LISTENING_PORT)
`
The server stars successfully but when I load the page in the browser I see this in the console

<img width="949" alt="image" src="https://user-images.githubusercontent.com/4868370/95375844-e0b00900-08e8-11eb-8a0a-d2d3c2fa0f0e.png">

### Expected Result:
normal operation

### Actual Result:

`'perspective-row' has already been defined as a custom element`

### Environment:
...version and build of the project, OS and runtime versions, virtualised environment (if any), etc. ...

### Additional Context:
...add any other context about the problem here. If applicable, add screenshots to help explain...

**Comment by pgagarinov** [comment]
Am I doing something wrong?

**Comment by zemeolotu** [comment]
The error is from trying to register `@finos/perspective-viewer` multiple times. `@finos/perspective-viewer` is already included in `@finos/perspective-workspace` so you can take it out from index.html i.e. 

```
<script src="https://unpkg.com/@finos/perspective@0.5.5"></script>
<script src="https://unpkg.com/@finos/perspective-workspace@0.5.5"></script>
<script src="https://unpkg.com/@finos/perspective-viewer-datagrid@0.5.5"></script>
<script src="https://unpkg.com/@finos/perspective-viewer-d3fc@0.5.5"></script>  
```

**Comment by pgagarinov** [comment]
@zemeolotu it works, thanks! After removing I faced #1206 but that's another story...

**Comment by texodus** [comment]
Closing as this seems to be resolved.
