### ISSUE TITLE
Can we set custom property on perspective viewer ? 

### ISSUE THREAD

**Issue by Madasamy26** [finos/perspective#1222]
I am using perspective viewer like this 

`<perspective-viewer
                    name="test"
                    id="perspective-view-main"
                    throttle="200"
                    plugin="${this.plugin}"
                    aggregates="${JSON.stringify(this.aggregates)}"
                    sampleData=[]
><perspective-viewer>`

I just want to use  custom data in  my perspective custom plugin ? 
So is there any way to pass the custom data?

**Comment by timkpaine** [comment]
All this information and more is available on the developer docs: https://perspective.finos.org/docs/md/js.html#loading-data
