### ISSUE TITLE
More Recent Conda Builds

### ISSUE THREAD

**Issue by choandrew** [finos/perspective#1226]
### Description of Problem:
I am unable to get python-perspective working except when I install through conda-forge
However, conda only has up to version 0.5.2.

I cannot pip install the more recent versions of perspective within the conda environment, as detailed here  https://github.com/finos/perspective/issues/1216

### Potential Solutions:
Would it be possible to fix the conda feedstock of perspective to make the conda install work?
It seems that one of the issues is that the pyarrow version is wrong in the conda recipe, as detailed here https://github.com/conda-forge/perspective-feedstock/issues/5

**Comment by timkpaine** [comment]
Work for conda compatibility continues on the conda forge repo, please open any (specific) issues there (apart from upgrading as there are numerous attempts to get conda compatibility already in progress).
