### ISSUE TITLE
All API documentation links broken

### ISSUE THREAD

**Issue by madmod** [finos/perspective#1229]
## Bug Report

Many or all of the API links in the documentation are broken and show a Github 404.

Eg:
https://perspective.finos.org/js.html#setting--reading-viewer-configuration-via-attributes
https://perspective.finos.org/docs/obj/perspective-python.html
https://perspective.finos.org/obj/perspective.html

**Comment by texodus** [comment]
Thanks for the report!  I've updated the gh-pages site.

Try these links instead (respectively):
https://perspective.finos.org/docs/md/js.html#setting--reading-perspective-viewer-configuration-via-attributes
https://perspective.finos.org/docs/obj/perspective-python.html
https://perspective.finos.org/docs/obj/perspective.html
