### ISSUE TITLE
Add support for StringDtype (available in Pandas >=1.0)

### ISSUE THREAD

**Issue by pgagarinov** [finos/perspective#1237]
## Feature Request
Allow for Pandas dataframe columns of "string" datatype - see https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html

### Description of Problem:
Right now the following call of perspective's Table constructor fails:
```
from perspective import Table
import pandas as pd
df = pd.DataFrame({'a': ['aa','bbb'],'b':['dddd','dd']},dtype='string')
Table(df)
```
with
`PerspectiveError: Mixed datasets of numpy.ndarray and lists are not supported.`

### Potential Solutions:
Maybe just convert (internally) to dtype('o') for backward compatibility as the first step... At least `Mixed datasets of numpy.ndarray and lists are not supported.` needs to be replaced with something more meaningful as StringDType is neither list nor numpy array. It does also look that StringDType can be converted to arrow array, no problem (see https://github.com/pandas-dev/pandas/blob/v1.1.3/pandas/core/arrays/string_.py#L26-L97)

**Comment by timkpaine** [comment]
We don't currently support the `string` datatype. We'll never support pure transparent pandas compatibility, so best bet is to convert to stable apis (like object) prior to trying to ingest.

**Comment by texodus** [comment]
What is "pure transparent pandas compatibility"?  Support for `dtype="string"` seems simple to add, as does support for newer Pandas versions `>1`.

**Comment by timkpaine** [comment]
@texodus as an example, pivot deconstruction and reconstruction from pandas is mostly broken right now, and there are lots of scenarios where you can't just go from pandas into perspective and get the same results, e.g. in a pivot table you might not have the ability to unpick and repivot.

Also we should be careful to avoid features explicitly marked "unstable" whether or not the exist in a newer version.

**Comment by timkpaine** [comment]
From the docs "StringDtype is considered experimental. The implementation and parts of the API may change without warning."
