### ISSUE TITLE
Pandas on the web browser with perspective?

### ISSUE THREAD

**Issue by ramonck** [finos/perspective#1254]
Hi,

First great project and initiative, I mean it's awesome stuff and to be honest I have not seen anything like this before which is impressive.

My question: I see that you say that you can do Python on the web and I can generate a graph on the web and I also see the pandas.. Can I have it so I can use the pandas on the web or somehow do a build process to do the pandas and then that generate the web pack version of this or how should I do it? I didn't find it in the examples folder and I'm personally very interested in how this could be accomplished it would be very cool.

**Comment by timkpaine** [comment]
No, we interoperate with pandas on a python server, we have no pandas available directly in webassembly in the browser (although perspective itself has many of the functions that pandas has).
