### ISSUE TITLE
Binding to a database on the server

### ISSUE THREAD

**Issue by KrishnaPG** [finos/perspective#1255]
## Support Question

The remote server example nicely demonstrates hosting a local file as a table.

Wondering what does it take to host a real table (from a local database)? For example, say we have a SQLite or some other database and want to bind one of its tables - what kind of API marshalling need to be done?

Is there some kind of interface / class that can be implemented so that **any** datasource can potentially become a table?

**Comment by nevi-me** [comment]
Hi @KrishnaPG. I've been able to successfully use perspective on the browser, and serve it data separately from a SQL backend. To do this, I was using JDBC > Apache Arrow via the provided utilities in the Arrow project. I then converted the Arrow data into batches, which I streamed to the browser via gRPC-web. Then on the browser, I read the Arrow data into Perspective.

Would a workflow like that work for you?

**Comment by KrishnaPG** [comment]
Thank you @nevi-me That sounds reasonable. Perhaps the question would be then,:

-  how do we map the frontEnd (perspective viewer's) filters, sort, scroll position etc. into the SQL / NoSQL queries on the backend

One way binding from server/DB -> frontEnd/Perspectiv Viewer (streaming the results one way) is straight forward. But how to achieve the two-way binding, specifically being able to apply the filters, sort etc. on the fly and get (only) the relevant data from the very large DB.

As user keeps changing the filters, sort etc. on the Perspective viewer, these need to be somehow sent to the server /DB adapter to tune the data that is streamed to the frontend. Is there some example / API to demonstrate the conversion of front-end params to query params?
