### ISSUE TITLE
Perspective Python build failure when executing yarn run build_python

### ISSUE THREAD

**Issue by JeepRenogade** [finos/perspective#1258]
Seeing below  error while trying  to build perspective python by executing build_python script using yarn. I see this issue is related to Issue #938,  based on the conversation in the #938 comments confirming I have installed pyarrow before and pasting some of the system info below.

**Error**

make[1]: *** [CMakeFiles/psp.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 246, in <module>
    setup(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 109, in run
    self.run_cmake()
  File "setup.py", line 129, in run_cmake
    self.build_extension_cmake(ext)
  File "setup.py", line 221, in build_extension_cmake
    subprocess.check_call(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--config', 'Release', '--', '-j12']' returned non-zero exit status 2.

Command failed: cd /Users/rajamutyala/C++/perspective/python/perspective && python3 setup.py build -v
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**System Info**

$system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro15,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 2.2 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 9 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      Boot ROM Version: 1037.100.362.0.0 (iBridge: 17.16.14281.0.0,0)
      Serial Number (system): C02YC5HQJG5H
      Hardware UUID: 9BA3B536-508E-5F62-A5BE-0683A642FC1F
      Activation Lock Status: Enabled

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287

gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ clang --version
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by timkpaine** [comment]
This stack trace is truncated and doesn't include the full error, could you post the entire stack trace

**Comment by JeepRenogade** [comment]
@timkpaine here is the complete stack trace

 yarn run build_python
yarn run v1.16.0
$ node scripts/build_python.js
/bin/sh: python3.7: command not found
`python3.7` not found - using `python` instead.
running build
running build_py
running egg_info
writing perspective_python.egg-info/PKG-INFO
writing dependency_links to perspective_python.egg-info/dependency_links.txt
writing requirements to perspective_python.egg-info/requires.txt
writing top-level names to perspective_python.egg-info/top_level.txt
reading manifest file 'perspective_python.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '.bumpversion.cfg'
warning: no files found matching 'perspective/table/*.so'
warning: no files found matching 'perspective/table/*.dll'
warning: no files found matching 'perspective/table/*.dylib'
warning: no previously-included files found matching 'docs/#*'
no previously-included directories found matching 'docs/build'
no previously-included directories found matching 'docs/gh-pages'
no previously-included directories found matching 'docs/dist'
no previously-included directories found matching 'bench'
warning: no directories found matching 'dist/test'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '.git' found anywhere in distribution
warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
writing manifest file 'perspective_python.egg-info/SOURCES.txt'
running build_ext
CMake Warning (dev) at CMakeLists.txt:371 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable Python_ROOT is set to:

    /Library/Frameworks/Python.framework/Versions/3.8

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at CMakeLists.txt:388 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.


CMake Deprecation Warning at cmake/modules/FindPybind.cmake:6 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  CMakeLists.txt:394 (find_package)


CMake Warning (dev) at /usr/local/Cellar/cmake/3.19.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:424 (message):
  The package name passed to `find_package_handle_standard_args` (PyBind)
  does not match the name of the calling package (Pybind).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindPybind.cmake:40 (find_package_handle_standard_args)
  CMakeLists.txt:394 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find PyBind (missing: PYTHON_PYBIND_INCLUDE_DIR) (found version "")
-- pybind11 v2.6.2 dev1
CMake Deprecation Warning at cmake/modules/FindNumPy.cmake:6 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  CMakeLists.txt:410 (find_package)


CMake Deprecation Warning at cmake/modules/FindPyArrow.cmake:7 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  CMakeLists.txt:418 (find_package)



Skipping WASM binding
Building C++ binding
Building Python 3.8 binding
Building C++ without strict warnings
Building RELEASE
Skipping Perspective Documentation

-- Configuring done
CMake Warning (dev):
  Policy CMP0068 is not set: RPATH settings on macOS do not affect
  install_name.  Run "cmake --help-policy CMP0068" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  For compatibility with older versions of CMake, the install_name fields for
  the following targets are still affected by RPATH settings:

   binding
   psp

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/rajamutyala/C++/perspective/python/perspective/build/temp.macosx-10.9-x86_64-3.8
make[2]: *** No rule to make target `/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyarrow/libarrow_python.0.dylib', needed by `/Users/rajamutyala/C++/perspective/python/perspective/build/lib.macosx-10.9-x86_64-3.8/perspective/table/libpsp.so'.  Stop.
make[1]: *** [CMakeFiles/psp.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 246, in <module>
    setup(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 109, in run
    self.run_cmake()
  File "setup.py", line 129, in run_cmake
    self.build_extension_cmake(ext)
  File "setup.py", line 221, in build_extension_cmake
    subprocess.check_call(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--config', 'Release', '--', '-j12']' returned non-zero exit status 2.

Command failed: cd /Users/rajamutyala/C++/perspective/python/perspective && python3 setup.py build -v
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by timkpaine** [comment]
Looks like you installed pyarrow>=2.? Can you install pyarrow <2 and try again

**Comment by timkpaine** [comment]
#1259 root cause

**Comment by JeepRenogade** [comment]
> Looks like you installed pyarrow>=2.? Can you install pyarrow <2 and try again

@timkpaine build was successful with pyarrow version 1.0.1.

Thank you for your help !

**Comment by timkpaine** [comment]
will track and fix in #1259
