### ISSUE TITLE
Windows support for latest package

### ISSUE THREAD

**Issue by monkeydust** [finos/perspective#1262]
## Support Question
Hi, Is there windows support coming for latest versions? Can only find whls for previous ones. Txs

**Comment by timkpaine** [comment]
All version support windows building from source, though we've never released windows wheels on pypi.

**Comment by monkeydust** [comment]
Thanks I found a a wheel package here for an older version

https://www.piwheels.org/project/perspective-python/

https://www.piwheels.org/simple/perspective-python/perspective_python-0.1.11-py3-none-any.whl#sha256=ff2d106c15451c3f61496dfe297f81b0b6c51298687f7ab800486856696b4636

Is there a guide as to how to build for wheels or latest version of could someone do that?
