### ISSUE TITLE
Defining calculated column using 'final aggregate column values'

### ISSUE THREAD

**Issue by dbboileau** [finos/perspective#1263]
## Support Question

Is there a way to define a calculated column that will be calculated using aggregated columns values rather than an aggregation over itself?

Example: I'm looking at a portfolio using underlying positions data. The portfolio level values are generated using a 'group by' clause. 

However, something like fill rate won't aggregate properly. 

fill rate = sum(executed_qty) / sum(qty)

I would need fill rate to be calculated using aggregate values of both sum(executed_qty) and sum(qty) rather than the individual executed_qty/qty

thx.

**Comment by texodus** [comment]
This can only be done explicitly in the API by _flattening_ ([Docs here](https://perspective.finos.org/docs/md/js.html#flattening-a-view-into-a-table)) an aggregated `View` into a new `Table`, then adding a computed column.  For your case, I'm assuming you are using a Perspective Web Component, so you just need to create the flat `Table` and `load()` it,  something like this:

```javascript
const agg_view = table.view({
    row_pivots: ["portfolio"],
    columns: ["executed_qty", "qty"]
});

workspace.load(worker.table(agg_view));
```

This is not currently possible through the GUI alone, starting with just `table` - you must specify the intermediate aggregate table ahead of time.  The plan is to add this as the `Flatten` command in the `<perspective-workspace>` right-click context menu.
