### ISSUE TITLE
Computed columns should accept scalars

### ISSUE THREAD

**Issue by sc1f** [finos/perspective#1279]
### Description of Problem:

When creating a computed column, I want to express scalar values as part of my computed expression. Right now, the expression `x + 5` is not possible - to do so would require a new column filled with the value `5`, which is cumbersome and traps the full potential of computed columns.

### Potential Solutions:

Implementing scalars would allow a scalar value (of the valid types accepted by Perspective) to take the place of any column name in the expression parser; this would allow operations on existing columns with scalars (i.e `x + 1`) as well as the creation of new columns "from thin air" with purely scalars (i.e. `5 + 6` creates a column filled with `11`, and so on). At the calculation level, a computation is a function that takes >=1 `t_tscalar` values and returns a new `t_tscalar`, so implementing scalar support is quite easy at that level. 

In terms of the expression parser, it will need to be able to differentiate between scalar strings and column names, and the autocomplete system should be improved. One improvement here would be to port the existing expression parser to Rust, using a parser combinator framework like [nom](https://github.com/Geal/nom), and perhaps compiling it down using the C/C++ FFI as a static library that ships with Perspective's core C++ engine. This would mean that both the Javascript and Python libraries can use the parser and express computed columns as string expressions, instead of the complex data structure that the API requires at present. Additionally, we should evaluate some off-the-shelf text editors that don't add too much bloat to JS asset sizes, or at least allow a high level of configuration where we can strip the editor down to the basic elements, and apply syntax highlighting/autocomplete for our minimal expression language.

**Comment by nmichaud** [comment]
You could also leverage exprtk (https://github.com/ArashPartow/exprtk/blob/master/readme.txt)

**Comment by texodus** [comment]
@nmichaud this is a good suggestion. From a light reading of the judicious documentation, Perspective has at least a few API feature challenges I need to understand better:
* Need a way to translate arbitrary string columns names to valid `exprtk` symbol names.
* Need to be able to serialize the AST back to Javascript, for syntax-highlighting/completion/etc.

**Comment by iaryangoyal** [comment]
can I do this?
