### ISSUE TITLE
Scrolling in the Olympics example grids expands the table continuosly

### ISSUE THREAD

**Issue by timpaine-iex** [finos/perspective#1302]
replyto: @timkpaine 
![tmp](https://user-images.githubusercontent.com/74613173/105365444-3ffe0480-5bcc-11eb-9b7b-341f53733270.gif)

**Comment by texodus** [comment]
Thanks for the report!

Important caveat that this is in OSX Safari-only (e.g. not iOS).  You can use the provided GitHub Issues Template which has a versions field for this information.

**Comment by tomthe** [comment]
This bug is still present in the latest version (https://cdn.jsdelivr.net/npm/@finos/perspective@latest/dist/cdn/perspective.js) in Firefox.
