### ISSUE TITLE
Custom styles example not showing anything

### ISSUE THREAD

**Issue by zepaz** [finos/perspective#1303]
### Steps to Reproduce:
visit http://bl.ocks.org/texodus/c42f3189699bd29cf20bbe7dce767b07

### Expected Result:
I would expect to see someting like:
![image](https://user-images.githubusercontent.com/56244702/105438562-5634bf00-5cb7-11eb-8cfe-681b09058c30.png)

### Actual Result:
You get a gray square and that is it. 

### Environment:
Windows 10
Chrome 87
perspective 0.6.0

### Additional Context:
In the console it is complaining:
```
Uncaught (in promise) Error: Unrecognized input type object.  Please use a `perspective.Table()`
    at HTMLElement.load (viewer.js:582)
    at (index):114
```

**Comment by texodus** [comment]
Fixed!
