### ISSUE TITLE
Olympics example still referring to hypergrid

### ISSUE THREAD

**Issue by zepaz** [finos/perspective#1304]
### Steps to Reproduce:
visit https://bl.ocks.org/texodus/efd4a857aca9a52ab6cddbb6e1f701c9

### Expected Result:
no errors in the console
### Actual Result:
It renders but perspective complains in the console `Unknown plugin "hypergrid"`
### Environment:
windows 10
chrome 87
perspective 0.6.0
### Additional Context:
Non-breaking bug

**Comment by texodus** [comment]
Fixed, thanks!
