### ISSUE TITLE
How to destroy perspective worker?

### ISSUE THREAD

**Issue by Madasamy26** [finos/perspective#1317]
Hi,

I am using perspective worker ,

 this.worker = perspective.worker();

while react component unmounting, I just want to destroy the worker  ? 

How can we do that?

**Comment by texodus** [comment]
Try this

```javascript
worker.terminate();
```

Note this _just_ terminates the worker engine - if you also have any `<perspective-viewer>` created, you'll need to also call `.delete()` on these to force them to release their event listeners etc.
