### ISSUE TITLE
SVGs invisible on firefox

### ISSUE THREAD

**Issue by ghost** [finos/perspective#1327]
### Steps to Reproduce:
Go to https://perspective.finos.org/ and toggle example to `treemap`

### Expected Result:
See result

### Actual Result:
`svg`s are present but invisible, no console errors

### Environment:
Firefox 85.0.2
OS X 10.15 Catalina on intel proc

### Additional Context:
<img width="1288" alt="Screen Shot 2021-02-17 at 4 50 04 PM" src="https://user-images.githubusercontent.com/74613173/108272430-340c5080-7140-11eb-862e-c583ab336c4c.png">

**Comment by timpaine-iex** [comment]
Another data point, for https://bl.ocks.org/texodus/raw/803de90736a3641ad91c5c7a1b49d0a7/

<img width="988" alt="Screen Shot 2021-02-17 at 4 54 08 PM" src="https://user-images.githubusercontent.com/74613173/108272833-c14fa500-7140-11eb-9741-c14b1376ee5f.png">
