### ISSUE TITLE
Binder link in README is broken

### ISSUE THREAD

**Issue by sc1f** [finos/perspective#1339]
### Steps to Reproduce:
 1. Open the [JupyterLab Plugin](http://beta.mybinder.org/v2/gh/finos/perspective/master?urlpath=lab/tree/examples/jupyter-notebooks) link from `README.md`

### Expected Result:
A working Jupyterlab instance.

### Actual Result:
Blank screen with the following error in the console:

![Screen Shot 2021-03-02 at 11 42 09 AM](https://user-images.githubusercontent.com/13220267/109682598-9146cf80-7b4c-11eb-8c57-c693da1635a9.png)

**Comment by timkpaine** [comment]
fixed in https://github.com/finos/perspective/pull/1341
