### ISSUE TITLE
Expose `join` aggregate function to clients

### ISSUE THREAD

**Issue by f0ster** [finos/perspective#1373]
### Description of Problem:
When transforming tables/creating views, a join or list operator to apply to the underlying grouped sets would be helpful for debugging. 

### Potential Solutions:
Support `join` operator on client side table aggregate views.

**Comment by hemantbaxi** [comment]
Hi,

I am interested to give a try on this.

My initial understanding after looking at code is that we need something like SQL join operator. Is that right ?  I am wondering on how is it different from pandas.dataframe.join ? Can that be directly used ?

Secondly,  in problem statement it is mentioned as "join" or "list". I think the two are different operations. Can you please elaborate on the issue, if possible, with an example ?

Thanks,
Hemant

**Comment by f0ster** [comment]
Thanks @hemantbaxi , I added a PR with a possible solution above.  We could have better test cases and perhaps break out the aggregate cases into their own file, cc @texodus 

The idea is to have an aggregate function (join), which takes a list, and returns one element (the list joined/concatenated). 
E.g.,  a simple pythonic join

```
>>> list("cheers")
['c', 'h', 'e', 'e', 'r', 's']
>>> "".join(list("cheers"))
'cheers'
>>> 
```

**Comment by hemantbaxi** [comment]
Thanks Ryan,

I looked at the PR.  If I understood it right, I can apply the two commits on my dev branch. The tests will fail initially, but once I add the python code for "join", these tests should pass.. Right ?  

Thanks,
Hemant

**Comment by f0ster** [comment]
@hemantbaxi No problem.  

The new specs are for the javascript library, but the core aggregate function is exposed to python.

Can you verify the existing tests pass as expected in your local environment , before applying and testing the new commits?

**Comment by hemantbaxi** [comment]
> @hemantbaxi No problem.
> 
> The new specs are for the javascript library, but the core aggregate function is exposed to python.
> 
> Can you verify the existing tests pass as expected in your local environment , before applying and testing the new commits?

I assume that since we can setup perspective in two environments Javascript/Python, each has to build and tested separately. I am able to build successfully and pass all the tests when I run in Python setup. But for Javascript setup, it is failing to build itself.

In Javascript setup, it seems even though @babel/preset-env plugin is installed, webpack is not able to recognize optional-chaining and is giving the below syntax error:

```
 babel src/js --source-maps --out-dir dist/esm
SyntaxError: src/js/api/client.js: Unexpected token (61:83)
  59 |                 this.send(msg);
  60 | 
> 61 |                 if ((msg.cmd === "table" || msg.cmd === "view") && !this._features?.wait_for_response && resolve) {
     |                                                                                    ^
  62 |                     resolve();
  63 |                 }
  64 |             });
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:babel:esm" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn build exited 1 in '@finos/perspective'
lerna ERR! yarn build exited 1 in '@finos/perspective'

Command failed: lerna exec --scope="@finos/*" -- yarn build
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Thanks,
Hemant
