### ISSUE TITLE
Jupyter notebook wont display widget

### ISSUE THREAD

**Issue by robambalu** [finos/perspective#1385]
I'm trying to get perspective working in a jupyter notebook.  Ive followed the directions, installed perspective-python as well as jupyterlab extensions ( including ipywidget ).
Everything installed fine, but I'm trying the simplest example in my notebook and it wont display anything.  I notice that when I just eval the widget, it doesn't just print the repr of it, so it seems like its trying to do something.  Any debugging tips would be appreciated:

![Capture](https://user-images.githubusercontent.com/28680700/115311999-91bc1980-a13e-11eb-8c23-7db321b55b31.PNG)

**Comment by timkpaine** [comment]
This looks like you're running Jupyter Notebook, which we do not support. Use JupyterLab instead
