### ISSUE TITLE
Cant get PerspectiveWidget loaded in jupyter lab

### ISSUE THREAD

**Issue by robambalu** [finos/perspective#1392]
I'm not sure what I did or what changed, I had this working just yesterday.  I tried rebuilding my end but I cant get it to work.
Whenever I create the widget I get an error:
Error displaying widget: model not found

I installed both jupyterlab extensions, as I did last time.  

chrome console shows this:
523.fa256ee….js:1 Error: widget model not found
    at x.get_model (523.fa256ee….js:1)
    at u.renderModel (523.fa256ee….js:1)
﻿
​This was done succesfully:
(base) [hfalgo_csp]$ jupyter labextension install @finos/perspective-jupyterlab
Building jupyterlab assets (production, minimized)
(base) [hfalgo_csp]$ jupyter labextension install @jupyter-widgets/jupyterlab-manager
Building jupyterlab assets (production, minimized)

running these versions:
(base) [hfalgo_csp]$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : not installed
ipython          : 7.12.0
ipykernel        : 5.5.3
jupyter client   : 6.1.12
jupyter lab      : 3.0.14
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 4.3.3

Any ideas / debugging tips?

Thanks

**Comment by sc1f** [comment]
What's the version of your `perspective-python`? It most likely has to be upgraded to 0.7.0, which does not look like it has been disted to PyPi yet.

You should be able to install `v0.6.2` of @finos/perspective-jupyterlab and the plugin should work again.

**Comment by robambalu** [comment]
I see thanks.  How do i force the version of the plugin?

**Comment by robambalu** [comment]
fwiw i tried
jupyter labextension install v0.6.2@finos/perspective-jupyterlab

but that seems to be hanging indefinitely

**Comment by texodus** [comment]
`npm` helpfully uses `@` for both scope and version qualifiers

```bash
jupyter labextension install @finos/perspective-viewer-jupyterlab@0.6.2
```

**Comment by robambalu** [comment]
thanks, just tried that and it installed but still hitting the same error
Error displaying widget: model not found

**Comment by texodus** [comment]
You may find cleaning and/or uninstalling/reinstalling helps.

```bash
jupyter labextension uninstall @jupyter-widgets/jupyterlab-manager @finos/perspective-juypterlab 
jupyter lab clean
jupyter labextension install @jupyter-widgets/jupyterlab-manager @finos/perspective-juypterlab
jupyter lab build
```

**Comment by texodus** [comment]
`perspective-python` `v0.7.0` is out now on pypi and it also works for me with the latest (`v0.7.0` also) `@finos/perspective-jupyterlab` and Jupyterlab `v3.0.9`.

**Comment by robambalu** [comment]
Thanks guys, it took a few tries but looks like its working now with 0.7.0

**Comment by robambalu** [comment]
Actually, its still not 100%
looks like if i start a fresh client to the jupyter lab, it hits the model not found error consistently.  It also consistently works if in that session I restart the kernel, so not sure whats going on there

**Comment by robambalu** [comment]
no semver warning in the console.  The versions are aligned, as i said if i restart kernel it works.
This is what the console looks like on first attempt and then after restarting the kernel:
![image](https://user-images.githubusercontent.com/28680700/116098413-0e884f80-a679-11eb-81b4-1e4f487e27f7.png)

**Comment by timkpaine** [comment]
Once the widget is disconnected from a running kernel, the expected behavior is that the model doesn't work. There's no save/restore.

**Comment by robambalu** [comment]
I dont follow.  What im saying is that in a brand new, fresh jupyterlab notebook, I get this "model not found error"
The only way I get this to work is if I then restart the kernel and rerun the notebook

**Comment by timkpaine** [comment]
So you open a new notebook, execute all the cells, and you get model not found?

**Comment by robambalu** [comment]
yes, the first time around.  If I then restart the kernel it runs fine
I didnt have this issue before the latest upgrade

**Comment by timkpaine** [comment]
So the first pass executing all the cells doesn't render, then you restart and re-re-execute all cells and it renders fine? So basically you

**Comment by robambalu** [comment]
yes, exactly.  where by restart i mean restart the kernel ( basically clicking the (>>) button at the top of the notebook, which restart kernel and replays the cells )
if there's any more debug info I can send over let me know

**Comment by timkpaine** [comment]
i just want to be doubly sure that you are executing all cells and that doesn't work on the first pass. By default when you open a notebook nothing gets executed, so the expectation is "model not found" since you haven't created a perspective table yet, even if the notebook has one saved from the previous execution it wont be restored. But to confirm, what you're seeing is you open a notebook, go and manually execute all the cells one by one and get an error, but then when you restart the notebook and rexecute all cells again (e.g. via the >>) you do get one.

**Comment by robambalu** [comment]
ok, this is a bit more interesting.  So what ive been doing is hitting F5 ( refresh ) to reconnect to the jupyter lab server.  This does seem to re-execute all my cells when it loads (and fails )
however in the same notebook, without restarting the kernel, if I re-evaluate the widget cell it does start working.  So sounds like some startup race ( and somewhat less of an issue for me, but maybe something you still want to look into )

**Comment by timkpaine** [comment]
you must have something custom then as the default behavior on refresh does nothing to re-execute cells, it just refreshes the page with the same prior notebook state. The expectation on page refresh is that your widget models will become disconnected from their python-side models, so it is expected that a widget model breaks on refresh right now for perspective (until and if we implement save/restore)

**Comment by robambalu** [comment]
ok thanks for working through this, will close this out
