### ISSUE TITLE
PerspectiveWidget graph tooltips error

### ISSUE THREAD

**Issue by robambalu** [finos/perspective#1396]
I noticed that the graph tooltips of the jupyerlab perspective grab ( d3_y_lin3 ) shows the circle but no data.  I see this error stack in the console:

Uncaught TypeError: A.select(...).selectAll(...).data(...).join is not a function
    at index.js:formatted:10575
    at index.js:formatted:10575
    at SVGCircleElement.a (index.js:formatted:10575)
    at zA.AA [as each] (index.js:formatted:10575)
    at i (index.js:formatted:10575)
    at u (index.js:formatted:10575)
    at HTMLElement.<anonymous> (index.js:formatted:10575)
    at a.call (dispatch.js:57)
    at HTMLElement.t (index.js:formatted:10575)
    at HTMLElement.<anonymous> (index.js:formatted:10575)

Simplest of graphs reproduces the issue for me:

import pandas
import perspective
x = pandas.DataFrame( { "a" : list(range(10))})
perspective.PerspectiveWidget( x, plugin='d3_y_line')

then hover mouse on the graph

**Comment by texodus** [comment]
I can't repro this on [binder](http://beta.mybinder.org/v2/gh/finos/perspective/master?urlpath=lab/tree/examples/jupyter-notebooks).  What browser are you using?

![repro](https://user-images.githubusercontent.com/60666/116191758-e04b5400-a6fa-11eb-9c43-a813f440f34e.gif)

**Comment by robambalu** [comment]
seems to work for me on binder too ( in the same browser ), so not sure whats causing it.  If I run the example snippet you're demoing here I still get the error in my notebook.
I'm on chrome v 90.0.4430.85.
