### ISSUE TITLE
API docs are returning 404

### ISSUE THREAD

**Issue by holdenmatt** [finos/perspective#1398]
## Bug Report

The API docs were accessible until recently, but now return 404.

### Steps to Reproduce:
 1. Visit an existing page in the docs, like [this one](https://perspective.finos.org/docs/md/view.html).
 2. This page has multiple links that reference the [API Docs](https://perspective.finos.org/docs/obj/perspective.html).
 3. Click one of those links.

### Expected Result:
The API docs were visible until recently.

### Actual Result:
404

### Additional Context:
I used to reference the API docs quite a bit, so hopefully they'll be back soon. Thanks!

**Comment by timkpaine** [comment]
Yep i see the first one on the page references https://perspective.finos.org/docs/obj/perspective.html which is incorrect

**Comment by texodus** [comment]
Thanks for the report!  This should be fixed now, just an error publishing the gh-pages site on my part
