### ISSUE TITLE
Cannot find perspective_vieux_bg.wasm

### ISSUE THREAD

**Issue by genderev** [finos/perspective#1409]
### Steps to Reproduce:
 1. I simply followed the example in the [JavaScript User Guide](https://perspective.finos.org/docs/md/js.html).
 2. I saved a simple `index.html` file with the following content:
```
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Perspective Demo</title>
    <script src="https://unpkg.com/@finos/perspective"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer-datagrid"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer-d3fc"></script>
  </head>
  <body>
<script type="text/javascript">
async function main(){
  const worker = perspective.worker();
  const table = await worker.table({A: [1, 2, 3]});
  const view = await table.view({sort: [["A", "desc"]]});
}
main();
</script>
  </body>
</html>
```
 3. I opened this HTML file in a browser that I knew had WebAssembly support.

### Expected Result:
I expected to see a simple table.

### Actual Result:
I received these errors in Chromium:
`unpkg.com/@finos/perspective_vieux_bg.wasm:1`
`Failed to load resource: the server responded with a status of 404 ()`

`index.html:1` 
`Uncaught (in promise) CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 43 61 6e 6e @+0`

`unpkg.com/@finos/perspective.cpp.wasm:1` 
`Failed to load resource: the server responded with a status of 404 ()`

### Environment:
OS X (Catalina), using CDN to load Perspective. I don't think my setup is special, just testing out a demo.

### Additional Context:
I tried this demo on a different computer yesterday (also OS X Catalina with Chromium browser). The browser could not find `perspective_vieux_bg.wasm`.

**Comment by texodus** [comment]
The documentation is out-of-date - use the CDN fully-qualified paths as in the [`bl.ocks` examples](https://bl.ocks.org/texodus/45b868833c9f456bd39a51e606412c5d).

```html
<script src="https://unpkg.com/@finos/perspective/dist/umd/perspective.js"></script>
<script src="https://unpkg.com/@finos/perspective-viewer/dist/umd/perspective-viewer.js"></script>
<script src="https://unpkg.com/@finos/perspective-viewer-datagrid/dist/umd/perspective-viewer-datagrid.js"></script>
<script src="https://unpkg.com/@finos/perspective-viewer-d3fc/dist/umd/perspective-viewer-d3fc.js"></script>
```
