### ISSUE TITLE
Apache Arrow featherV2 read function

### ISSUE THREAD

**Issue by public-tatsuya-noyori** [finos/perspective#1456]
When I read Apache Arrow featherV2, I get the following error.

Table initialization failed: Error: Abort(): Failed to read file record batch: NotImplemented: LZ4 codec support not built

It would be appreciated if you could implement Apache Arrow featherV2 read function.

**Comment by nevi-me** [comment]
The solution here might be to bump the Arrow version. This project seems to still use 1.0.1, and LZ4 compression seems to have been enabled by default in Arrow version 4.0.0

**Comment by texodus** [comment]
I am certain this still won't work even with Arrow 5.0.  We don't yet build LZ4 for wasm for starters, it is "enabled" by default in that the python API will default the `compression` kwarg but even this depends on the python bindings for LZ4.

**Comment by texodus** [comment]
Fixed in #2339
