### ISSUE TITLE
Ability to programmatically set the toggle state of the side panel from Python

### ISSUE THREAD

**Issue by dhirschfeld** [finos/perspective#1499]
### Description of Problem:
When I create a `PerspectiveWidget` in Python/JupyterLab it always starts with the side panel expanded. I'd like the ability to programmatically set the toggle state of the side panel so I can (initially) hide confusing complexity from end users.

**Comment by dhirschfeld** [comment]
It would also be good to be able to disable the side panel altogether (from Python/`PerspectiveWidget`) - xref: #1085

The use case is that I have carefully crafted a summary view from the state of other external widgets and don't want that to be altered to get out of sync with the external state. I also provide a table view of the data which I'm happy for the traders to slice-and-dice however they see fit, but it would be good if I could enforce the summary view to be fixed.

**Comment by ptomecek** [comment]
+1, same use case, especially when displaying multiple perspective Views beside each other in a Jupyter GridBox. The user needs to manually minimize each window to really be able to see the composite widget the way it was intended.

**Comment by ccarli** [comment]
+1 with same use case as @ptomecek
