### ISSUE TITLE
Set title value for tab in ipywidgets (widget_tutorial.ipynb)

### ISSUE THREAD

**Issue by kimmolinna** [finos/perspective#1504]
You can't set title value for tab with command 
`tab.titles = ["Sales by State", "Profit by State"]`
but it's possible at least with the following command
`[tab.set_title(i, title) for i, title in enumerate(["Sales by State", "Profit by State"])]`

**Comment by timkpaine** [comment]
https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Tabs

**Comment by kimmolinna** [comment]
Maybe it's better to use stable documentation instead of latest.
[Tabs](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Tabs)
```
Tabs
In this example the children are set after the tab is created. Titles for the tabs are set in the same way they are for Accordion.

tab_contents = ['P0', 'P1', 'P2', 'P3', 'P4']
children = [widgets.Text(description=name) for name in tab_contents]
tab = widgets.Tab()
tab.children = children
for i in range(len(children)):
    tab.set_title(i, str(i))
tab
```
In next version you can do according to your example.
