### ISSUE TITLE
Inconsistent view output under frequent insert&delete

### ISSUE THREAD

**Issue by kryaksy** [finos/perspective#1505]
## Bug Report 
When creating new view with new filters under frequent insert and delete, filtered data output could be inconsistent with view config.

### Steps to Reproduce:
 1. Create worker
 2. Create table
 3. Insert and delete table data frequently
 4. Create view without filters
 5. Create view with filters, delete previous view
 6. If it is not reproduced, go back to 4. step

### Expected Result:
I expect to see that the output data of view to be consistent with view config. 

### Actual Result:
When I repeatedly create new view with new config (just filters are different), I eventually encounter some inconsistent output. 

**Screenshot:**
<img width="1759" alt="Screen Shot 2021-08-05 at 14 34 46" src="https://user-images.githubusercontent.com/33466807/128356032-fa8498c9-4ee8-4860-b097-5126aa1db1b3.png">

**Reproducable Example**
This project clearly reveals the bug. But before you open, I want to clarify a few things:

1. There are 3 important section which are aligned horizontally. 
   - PerspectiveViewer
   - view.to_json() output
   - view.get_config() output
2. When you open the project it will automatically create worker, table and view respectively.
3. After table is created, it will start these periodic operations:
   - update(<5rows/500ms), 
   - insert(<5rows/500ms),
   - delete(<5rows/1000ms) .
4. In parallel it will recreate view (with deleting previous one) once in 5000ms with changing just filters in view config. As follows:
   - `{ ...prevConfig, filters: []}`
   - `{ ...prevConfig, filters: [['Column1', 'in', ['C', 'E']]]}`
   - `{ ...prevConfig, filters: []}`
   - `{ ...prevConfig, filters: [['Column1', 'in', ['C', 'E']]]}`
   - and so on...

I hope I didn't confuse. When you open the project, just wait for the error.

[Codesandbox Project](https://codesandbox.io/s/perspective-filtering-error-bcypx?file=/src/App.tsx)

### Environment:
Codesandbox, React Application dev and prod environments.
Browser: Chrome 92.0.4515.131 (Official Build) (x86_64)
Perspective: 0.10.0
OS: macOS Big Sur

**Comment by kryaksy** [comment]
Were you able to review this? It may be bigger problem than it seems. I've just encountered another one which could be related to this issue.

**Comment by kryaksy** [comment]
I tried it with 0.10.1 version. Problem still exists.
[Codesandbox - perspective-filtering-error-v0.10.1](https://codesandbox.io/s/perspective-filtering-error-v0-10-1-ksfyu?file=/src/App.tsx)

**Comment by sc1f** [comment]
Hi,

Thanks for the report! Though the ultimate fix to the issue did not have anything to do with filters, your repro's use of randomized string primary keys, removes, and filters highlighted the issue well and was helpful in nailing down the ultimate problem.

As a note, however, issue reproductions that are overly complex and drag in other large libraries such as React sometimes serve to make the problem harder to diagnose, especially when the reproduction depends on the order of operations as submitted to the Perspective table. We encourage the use of the Examples folder or the [bl.ocks examples](bl.ocks.org/texodus) as a starting-off point for issue reproductions, as they only use pure Javascript and are easy to understand at a glance.

I'll keep this issue open until the PR is merged, but I am confident that the correctness bug here has been dealt with. Thanks again!

**Comment by kryaksy** [comment]
Hi,

Thanks @sc1f . I know, the reproduction was a little complicated and not much isolated. Thanks for your advices. Next time, I will reproduce with html and pure javascript.

Also, I don't want to rush, but I wonder when will you release the next version. Can I have any information about that?

**Comment by sc1f** [comment]
No worries at all - your repro helped to reveal the issue and was helpful in nailing down the specific cause. The fix was merged and will be in the next release (`v1.0.0`), which is on its way to completion. I don't have a specific timeline for the release yet but it is approaching completion. Thanks!
