### ISSUE TITLE
Custom cell renderer

### ISSUE THREAD

**Issue by jonw09** [finos/perspective#1508]
## Support Question

Is there an API or approach that I can use to extend or override the cells within the datagrid?

Ideally I'd like to make use of the table as is, but have a way to provide the individual cells to display. This would allow me to do custom formatting and styling and make use of bespoke components.

Is this supported?

**Comment by timkpaine** [comment]
There is a custom styles example on the README:
https://bl.ocks.org/texodus/c42f3189699bd29cf20bbe7dce767b07

**Comment by jonw09** [comment]
That’s for the link. I’m looking for a way to fully customise cells on an individual basis though. From what I can see in the example, the styling would be table-wide with no ability to target individual cells based on their content. 

Is there either:
- a way to override the rendered cell component with something bespoke? E.g. return a new div per cell with custom content
- a way to style specific cells either by applying extra class names or applying styles directly?

An example of what I’d like to do is a flash of green if a number ticks up and red if it ticks down. As far as I can tell from the docs there’s no way to do this in a targeted manner using styles.

**Comment by nekw** [comment]
I am looking for this feature/api as well.

**Comment by timkpaine** [comment]
You can, e.g. [the Magic example](https://texodus.github.io/mtg-perspective/?seasons-in-the-abyss-67)

**Comment by texodus** [comment]
I do not understand what is being asked for by "customize cells on an individual basis" or "target individual cells based on their content".  You can choose to update all, some or none of the visible cells at your discretion based on a wide-range of metadata provided by  [`getMeta()`](https://github.com/jpmorganchase/regular-table#addstylelistener-and-getmeta-styling) per cell, you just iterate through visible cells on each style listener callback and only modify the ones you're interested in, a la any of the style examples @timkpaine linked above.  Even `@finos/perspective-viewer-datagrid` itself [uses this API](https://github.com/finos/perspective/blob/master/packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js#L16) from the underlying [`regular-table` datagrid library](https://github.com/jpmorganchase/regular-table) to do its own styling.

Perspective does not generate deltas [unless you explicitly request them](https://perspective.finos.org/docs/obj/perspective.html#module_perspective..view+on_update), which means the datagrid does not  provide the delta per cell in the [metadata object returned from `getMeta()`](https://github.com/jpmorganchase/regular-table#addstylelistener-and-getmeta-styling).   You can however subscribe to these yourself pretty simply, if I have time I will try to add an example of this after we merge the newest plugin API.
