### ISSUE TITLE
Examples/gallery of actual products that rely on Perspective

### ISSUE THREAD

**Issue by AlexAltea** [finos/perspective#1511]
While the examples (and community plugins) are quite helpful at understanding individual features of Perspective. I am curious about finished products that make use Perspective. Even if closed-source, such projects would be a great inspiration and a fantastic showcase on how *all* of Perspective may be used in production (with more than just mock data).

Seeing them live would certainly help me (and others?) at having a better grasp at how Perspective can fit in our own projects.

Maybe it would make sense to add a "*Showcase*"-like section to the *README.md*?

**Comment by ccarli** [comment]
+1, this would help me a lot !

**Comment by texodus** [comment]
Thanks for the issue - unfortunately, the reality is that most users of Perspective in the finance industry aren't keen to share their work. I put every talk, news item and demo or Perspective that we can find on the [`README.md`](https://github.com/finos/perspective) and [docs site](https://perspective.finos.org/), we're not holding somehting back, so there's no need for a standing issue for it, closing.
