### ISSUE TITLE
1-sided row deltas fail with hidden sorts applied

### ISSUE THREAD

**Issue by sc1f** [finos/perspective#1513]
### Steps to Reproduce:
 1. Create a 1-sided view and apply a hidden sort:

```javascript
const table = await perspective.table({
    x: [1, 2, 3, 4],
    y: ["A", "B", "C", "D"]
});
const view = await table.view({
    row_pivots: ["y"],
    sort: [["y", "desc"]],
    columns: ["x"]
});
```
2. Subscribe to deltas through `on_update`, and apply an update:

```javascript
view.on_update(
    async function(updated) {
            const t2 = perspective.table(updated.delta);
            const view2 = await table2.view();
            console.log("Row delta:", await view2.to_columns());
    },
    {mode: "row"}
);

table.update({x: [1, 2], y: ["NEW STRING", "NEW STRING"]});
```

### Expected Result:

A correct row delta showing the updated rows.

### Actual Result:

A thrown exception from C++: `thrown: 21562720`. The exception is thrown in [view.cpp:555](https://github.com/finos/perspective/blob/master/cpp/perspective/src/cpp/view.cpp#L555), when `to_arrow` tries to get a column name. In pivoted contexts, the `num_columns` property of the data slice created by `get_row_delta` is determined by the number of aggregates applied to the context.

A hidden sort does not appear in the columns, but _does_ appear in the aggregates map as "unique" is required for these sort specifications to apply properly. Hence, `to_arrow` thinks there is `num_columns + 1` columns in the delta, but there is only `num_columns`, and thus accesses an invalid index on the `names` array of the data_slice, and throws the error.

### Environment:
Master, MacOS Mojave.

**Comment by texodus** [comment]
Fixed in #1519
