### ISSUE TITLE
Bad links in docs

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#1521]
<img width="552" alt="Screen Shot 2021-08-24 at 5 06 41 PM" src="https://user-images.githubusercontent.com/3105306/130690009-444fa211-a257-44fc-810a-20cc941f165b.png">

links to missing page:
https://github.com/finos/perspective/blob/master/examples/simple/superstore-arrow.html

**Comment by rgrupesh** [comment]
Hello @timkpaine ,

I went through the issue. I would like to work on this. Where should I look for superstore-arrow.html page? I went through the [examples](https://github.com/finos/perspective/tree/master/examples) but I did not find that page.

**Comment by texodus** [comment]
@rgrupesh The offer is appreciated but there is no need for help here, this is a 6 character fix which we'll take care of in the next docs epic.

For your future reference, a good way to find the origin of a missing file is to use [`git blame`](https://git-scm.com/docs/git-blame) on the documentation in question to find a commit where this file was present, then do the same thing in reverse to find where this file ended up (in this case it was renamed to `/examples/blocks/superstore/index.html`)

**Comment by morzel85** [comment]
BTW:
https://perspective.finos.org/docs/md/docs/md/server.html#clientserver-replicated and https://perspective.finos.org/blog are 404 too. The first link should be likely replaced by https://perspective.finos.org/docs/md/server.html#clientserver-replicated

**Comment by texodus** [comment]
@morzel85 Thanks! 

I've updated this Issue's title to indicate it is a collection of docs bugs.

**Comment by HARRISH2004** [comment]
I thought we can easily add it to the source page.

**Comment by texodus** [comment]
Closing
