### ISSUE TITLE
Panic when trying to load different datasets with similarities between schemas

### ISSUE THREAD

**Issue by garneck** [finos/perspective#1558]
When I try loading tables with different schemas that have some similarities between them (1 or more shared column names), perspective throws an unwrap error, panics and stops responding

Steps to Reproduce:

Run provided sandbox: https://codesandbox.io/s/recursing-proskuriakova-f7rwv
Load dataset 1
Try loading dataset 2
There should be a panic error in console as described above
Loading further datasets will not work

**Comment by garneck** [comment]
Confirmed to still be an issue after 1.0.0 release

**Comment by texodus** [comment]
Bit-rotted, closing. 

Calling `.reset()` will fix the (real) issue that the viewer config no longer matches the table, in that case. Replacing the table an preserving the config may (or may not) work - its not the intended use case, use `Table.replace()` for this.
