### ISSUE TITLE
PerspectiveWidget.save() should emit plugin_config

### ISSUE THREAD

**Issue by sc1f** [finos/perspective#1560]
save() does not return plugin config

**Comment by sc1f** [comment]
save() is also currently out of date if no traitlets are set on the widget, so in the following scenario:

```python
w = PerspectiveWidget(table)
# add some expressions, drag some columns, etc.
config = w.save()
```
config will not reflect the viewer state. At this point the best solution seems like to remove all traitlets, remove the python `PerspectiveViewer` API, and rewrite the widget to implement the `restore(config)` and `save()` API that just requests the message from the front-end. Even if we don't remove the kwargs like `columns` etc., we should remove traitlets and basically back all kwargs onto a call to restore(). We'd need a small custom wire API for save and restore, but it should be very uncomplicated as all we need is to pass valid configs and handle errors from invalid configs.

**Comment by timkpaine** [comment]
You'll need it to be synchronous in both directions so that UI based changes are exposed in `save`. Also will want to support partial `restore` if the python side doesn't persist the info (so you can set a single attribute without having to remember the current state, similar to performing a single ui action).

**Comment by timkpaine** [comment]
e.g. 

```python
pspWidget = PerspectiveWidget()

# set columns
pspWidget.restore({"columns": [...]})

# set filters
pspWidget.restore({"filters": [...]})

# at this point, columns and filters should be set
```

I dont remember if the JS api is also cumulative like this, but if not we should probably do that too since its convenient. We could determine the "reset" of a field by its value, e.g. `el.restore({columns: null})`

**Comment by sc1f** [comment]
@timkpaine partial restores already work I think - on the widget front-end the calls to set a trait are just calling restore with one single key, and restore is cumulative as well.

With this change the JS front-end should be the source of truth for "viewer state". The way this really should work is with a single save() and restore() API, and no more manually setting attributes individually, but it's also a very widely used API and more pythonic to use kwargs/attributes so I see both sides of the argument. Removing attributes would make it really easy to get the correct viewer state - it is always whatever comes out of save().

**Comment by timkpaine** [comment]
its easy enough to do both:

```python
class PerspectiveWidget:

    def restore(self, **kwargs):
         # validate kwargs dict
         self.send(json.dumps(kwargs))

    @property
    def columns(self):
        return self.save().get("columns")

    @columns.settter
    def columns(self, value):
        # validate value
        self.restore(columns=value)

```

**Comment by timkpaine** [comment]
fixed in https://github.com/finos/perspective/pull/1850
