### ISSUE TITLE
Customized types are not support perspective 1.0.1

### ISSUE THREAD

**Issue by jshinonome** [finos/perspective#1602]
### Steps to Reproduce:
```
<!DOCTYPE html>
<html>

<head>

    <meta name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">

    <script src="https://unpkg.com/@finos/perspective/dist/umd/perspective.js"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer/dist/umd/perspective-viewer.js"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer-datagrid/dist/umd/perspective-viewer-datagrid.js"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer-d3fc/dist/umd/perspective-viewer-d3fc.js"></script>
    <link rel='stylesheet' href="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer/dist/umd/material-dense.css"
        is="custom-style">

    <style>
        perspective-viewer {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
        }
    </style>

</head>

<body>

    <perspective-viewer editable>

    </perspective-viewer>

    <script>
        const overridden_types = {
            types: {
                float: {
                    filter_operator: '==',
                    aggregate: 'sum',
                    format: {
                        style: 'decimal',
                        minimumFractionDigits: 2,
                        maximumFractionDigits: 7
                    }
                },
                string: {
                    filter_operator: '==',
                    aggregate: 'count'
                },
                integer: {
                    filter_operator: '==',
                    aggregate: 'sum',
                    format: {}
                },
                boolean: {
                    filter_operator: '==',
                    aggregate: 'count'
                },
                datetime: {
                    filter_operator: '==',
                    aggregate: 'count',
                    format: {
                        year: 'numeric',
                        month: '2-digit',
                        day: '2-digit',
                        hour: '2-digit',
                        minute: '2-digit',
                        second: '2-digit',
                        fractionalSecondDigits: 3,
                        hourCycle: 'h23',
                    },
                },
                timestamp: {
                    filter_operator: '==',
                    aggregate: 'count',
                    type: 'datetime',
                    format: {
                        year: 'numeric',
                        month: '2-digit',
                        day: '2-digit',
                        hour: '2-digit',
                        minute: '2-digit',
                        second: '2-digit',
                        fractionalSecondDigits: 3,
                        hourCycle: 'h23',
                    },
                },
                time: {
                    filter_operator: '==',
                    aggregate: 'count',
                    type: 'datetime',
                    format: {
                        hour: '2-digit',
                        minute: '2-digit',
                        second: '2-digit',
                        fractionalSecondDigits: 3,
                        hourCycle: 'h23',
                    },
                    null_value: -1
                },
                timespan: {
                    filter_operator: '==',
                    aggregate: 'count',
                    type: 'datetime',
                    format: {
                        hour: '2-digit',
                        minute: '2-digit',
                        second: '2-digit',
                        fractionalSecondDigits: 3,
                        hourCycle: 'h23',
                    },
                    null_value: -1
                },
                minute: {
                    filter_operator: '==',
                    aggregate: 'count',
                    type: 'datetime',
                    format: {
                        hour: '2-digit',
                        minute: '2-digit',
                        hourCycle: 'h23',
                    },
                    null_value: -1
                },
                second: {
                    filter_operator: '==',
                    aggregate: 'count',
                    type: 'datetime',
                    format: {
                        hour: '2-digit',
                        minute: '2-digit',
                        second: '2-digit',
                        hourCycle: 'h23',
                    },
                    null_value: -1
                },
                date: {
                    filter_operator: '==',
                    aggregate: 'count',
                    format: {
                        year: 'numeric',
                        month: '2-digit',
                        day: '2-digit',
                    },
                    null_value: -1
                },
                month: {
                    filter_operator: '==',
                    aggregate: 'count',
                    type: 'date',
                    format: {
                        year: 'numeric',
                        month: '2-digit',
                    },
                    null_value: -1
                }
            }
        };

        const worker = perspective.worker(overridden_types);

        document.addEventListener("DOMContentLoaded", async function () {
            var data = [
                { x: 1, y: "a", z: true, t: "2016-01-13T17:11:29.998", s: "2000-01-01T00:00:32.000" },
                { x: 2, y: "b", z: false, t: "2016-01-13T17:11:29.999", s: "2000-01-01T00:00:33.000" },
                { x: 3, y: "c", z: true, t: "2016-01-13T17:11:30.000", s: "2000-01-01T00:00:34.000" },
                { x: 4, y: "d", z: false, t: "2016-01-13T17:11:30.001", s: "2000-01-01T00:00:35.000" }
            ];

            var viewer = document.getElementsByTagName('perspective-viewer')[0];

            const table = await worker.table({
                x: 'integer',
                y: 'string',
                z: 'boolean',
                t: 'datetime',
                s: 'second'
            });

            table.update(data);

            viewer.load(table);
        });
    </script>

</body>

</html>
```

### Expected Result:
Customized types should show correctly.

### Actual Result:
Customized types do not work anymore.

### Environment:
fedora 34
perspective v1.0.1

**Comment by jshinonome** [comment]
Error message: 
```
Uncaught (in promise) unknown variant `second`, expected one of `string`, `datetime`, `date`, `integer`, `float`, `boolean` at line 1 column 69
```

**Comment by texodus** [comment]
Thanks @jshinonome - the custom types feature was officially removed in `1.0.0`, and is no longer referenced in the docs. Unfortunately, this feature ..

1) Just did not work particularly well and was quite awkward to use due to the initialization-order shenanigans
2) Offers very limited customizable features e.g. `format()`.
3) Is incompatible with editing, cross filtering, charting, expressions, and a whole raft of other features.

In `1.0.0`, we are instead actively working towards a more fully featured plugin system based on implementing your own plugins via Custom Elements class inheritance.  I've made an [example of your `seconds` type](https://bl.ocks.org/texodus/238458c2feb8c6b56599cdb6b3ac9526) using the new Custom Elements plugin pattern;  there are some initial docs on this [here](https://github.com/finos/perspective/tree/master/rust/perspective-viewer#interface-iperspectiveviewerplugin), as well as additional examples that use this pattern in [Custom](https://bl.ocks.org/texodus/c42f3189699bd29cf20bbe7dce767b07), [NFT](https://sc1f.github.io/pudgy-penguin-perspective/), and [BTC Liquidity](https://sc1f.github.io/perspective-btc-liquidity/) examples.

**Comment by texodus** [comment]
Additional docs on [`regular-table` datagrid styling](https://github.com/jpmorganchase/regular-table#addstylelistener-and-getmeta-styling)

**Comment by jshinonome** [comment]
@texodus thank you for your reply. 

I will take a look at the code you provided and build one for my use case.

**Comment by texodus** [comment]
Since you're using this feature - we'd also be interested in any feedback you have regarding the new API design and capabilities, as I mentioned this area is under active development.

**Comment by jshinonome** [comment]
Understood, I will let you know if I need any feature or help on supporting all those temporal tyeps.

**Comment by jshinonome** [comment]
Hi @texodus, I was busy moving to a new country. I am only able to check this now. Looks like the new approach is based on column name rather than the data type. My use case would never know the column name. Any way to add a data type time without a date? I will map hour, second to this.

**Comment by texodus** [comment]
@jshinonome You can get a cell's type from `View.schema()` (as per docs):
```javascript
const view = await viewer.getView();
const schema = await view.schema();

// ...

const cell_type = schema[datagrid.getMeta(td).column_header.join("|")];
```

[example](https://bl.ocks.org/texodus/238458c2feb8c6b56599cdb6b3ac9526).

> As for the format, I actually just updated packages/perspective-viewer-datagrid/src/js/regular_table_handlers.js and build, it is easier to update this file and build.

Easier if you're <i>vendoring and building your app's dependencies from source</i> perhaps, but this is a nightmare for maintainability, and is guaranteed to break every time these files are changed upstream, for example right now #1691. 

Please don't do this.  Use `npm` or equivalent and don't fork your dependencies, for the sake of any future developer with the misfortune of having to fix your code.

**Comment by jshinonome** [comment]
Thank you for your advice @texodus. I will migrate to the example you showed me.  A quick question does the current perspective schema only support types in this file:
https://github.com/finos/perspective/blob/master/packages/perspective/src/js/config/settings.js
I was looking for a type of 'time'(without a date).
- datetime -> YYYY-MM-DD[D]HH:mm:ss.SSS
- date -> YYYY-MM-DD
- **time -> HH:mm:ss.SSS**

**Comment by texodus** [comment]
This is covered [in the docs](https://perspective.finos.org/docs/md/table.html#schema-and-types).

**Comment by jshinonome** [comment]
Thanks. Understood that we can format datetime to time string, but I may have 3 data types at the same time. In this case, since we have only two data types, I can only have two kinds of temporal format right, right?

**Comment by texodus** [comment]
No, you can have as many formats as you want, on a per-cell basis if you want.  In your case, you'll just need to distinguish them by something other than their schema type, like their column name, cell content, or any custom plugin metadata you want to add (e.g. add a method to your custom plugin called `setTimeColumns(column_names)`)

**Comment by jshinonome** [comment]
Thank you very much for your prompt reply, very helpful. I will think about how to deal with this.

**Comment by jshinonome** [comment]
Thanks again for your explanations. I managed to use the plugin for all kdb+ temporal types(8 types) and I don't ever need to build from source code again.
