### ISSUE TITLE
Can I use a websocket client to asynchronously update the table? 

### ISSUE THREAD

**Issue by jmy48** [finos/perspective#1604]
I plan to use this endpoint https://polygon.io/docs/websockets/ws_stocks_A_anchor to update tables. How can I do this?

**Comment by timkpaine** [comment]
Perspective doesn't care where the data comes from, here is a python example you can start from:
https://github.com/finos/perspective/blob/master/examples/tornado-streaming-python/server.py

And a full-featured JS one:
https://github.com/sc1f/perspective-btc-liquidity/blob/master/src/datasource.tsx
