### ISSUE TITLE
Precision Display Window on Dark Background

### ISSUE THREAD

**Issue by ptomecek** [finos/perspective#1609]
### Steps to Reproduce:
 1. Create a PerspectiveWidget in Dark Mode
 2. Click on the precision controls

### Expected Result:
A readable version of the precision control window with light text on a dark background

### Actual Result:
A dark window with dark text on a dark background. 

### Environment:
Perspective 1.0.1

### Additional Context:
See screenshot
![perspective-precision](https://user-images.githubusercontent.com/40371786/141691105-d9eb0e0a-59eb-4691-950a-94cb4b1966bf.png)

**Comment by texodus** [comment]
Thanks for the report @ptomecek!  I've merged a fix for this, it will be in the `1.0.3` release.
