### ISSUE TITLE
JupyterLab CSV widget not working anymore

### ISSUE THREAD

**Issue by moiney** [finos/perspective#1612]
#### Steps to reproduce:

1. Open JuypyterLab
2. Import a CSV file to your workspace
3. Right-click -> Open With -> CSVPerspective

#### Expected result:

Perspective viewer containing the CSV data.
![image](https://user-images.githubusercontent.com/25009134/141959265-6b787872-4443-45cf-866b-a32f01e59f30.png)

#### Actual result:

Empty Perspective viewer.
![image](https://user-images.githubusercontent.com/25009134/141959418-60291a48-cf88-4548-a06d-18cbf1c9f3cc.png)

#### Impacted versions:
1.0.x

#### Working versions:

0.10.2 and before

**Comment by texodus** [comment]
Thanks for the report @moiney!  This issue has been fixed and will be in the `1.0.3` release.
