### ISSUE TITLE
Themes moved causing build errors

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#1648]
## Bug Report

`@finos/perspective^1.0.3`

```
Module not found: Error: Can't resolve resolve '~@finos/perspective-workspace/dist/theme/material.less' in '/Users/...`
```

Looking in the folder:
<img width="390" alt="Screen Shot 2021-12-02 at 15 58 30" src="https://user-images.githubusercontent.com/3105306/144502015-5789d05a-3ac4-407f-ba66-43d08b80a46f.png">

I \*believe\* this should break these two examples:
- [remote-workspace](https://github.com/finos/perspective/blob/e95dc5249542008a7b2cd84d6a61886610e0542a/examples/remote-workspace/src/index.less#L10)
- [workspace-editing-python](https://github.com/finos/perspective/blob/e95dc5249542008a7b2cd84d6a61886610e0542a/examples/workspace-editing-python/src/index.less#L10)

I think we need to copy theme assets in addition to css assets to maintain the same importability:
Add here: https://github.com/finos/perspective/blob/master/packages/perspective-workspace/build.js#L81
To account for removal from web pack step here: https://github.com/finos/perspective/commit/5df1d045c170799ed2726262d51ec780266c5486#diff-9125ba2248bc16eb862b5199a87368613b083e054809ce7500b1091c1e73af38L19

**Comment by texodus** [comment]
We use `externals` now which should allow us to alias this to as many legacy locations as we want, at least for all platforms which recognize `externals` which (I believe) is a strict superset of those which Perspective has plugins (e.g. `webpack@5` as of now).  This annoyingly doesn't work on CDNs though.

In the (near?) future, I'd like to move towards a theme system that allows theming to be controlled within the UI itself, and this will almost certainly be the end of separate JS/CSS assets anyway, at least in the sense that `material.css` is currently a pre-requisite for any app.
