### ISSUE TITLE
Consume perspective with `esbuild`

### ISSUE THREAD

**Issue by LukeSheard** [finos/perspective#1655]
## Support Question

While `perspective` itself is build with `esbuild` there's no documentation for projects which are using `esbuild` themselves to build their applications. 

I setup a simple test to see whether this worked directly and it does, however it produces a 12.2MB bundle which is just un-consumable and there's a warning about perspective being inlined. 

I couldn't find on the website or in the issues any documentation for setting up with non-webpack projects. I would imagine there needs be to a separate esbuild plugin for consuming perspective similar to webpack?

**Comment by timkpaine** [comment]
https://github.com/finos/perspective/pull/1611#discussion_r750531822

**Comment by texodus** [comment]
There is a plugin for this in [`tools/perspective-build`](https://github.com/finos/perspective/tree/master/tools/perspective-build) that perspective uses to build itself;  we plan to publish this in `1.1.0`.

While the inline-ed version is a large JavaScript file, in practice the difference between these builds on initial load time over a modern connection is likely to be quite small  (e.g. 200ms vs 1.5s, testing myself on a 5g device from unpkg).  This is unfortunate, but not un-consumable - is there something I'm missing?

[Paralell/native wasm perspective example](https://bl.ocks.org/texodus/raw/45b868833c9f456bd39a51e606412c5d/?raw=true)

[Inline single-js perspective example](https://bl.ocks.org/texodus/9bec2f8041471bafc2c56db2272a9381)
