### ISSUE TITLE
Support all `Intl` format options for `perspective-viewer-datagrid` columns

### ISSUE THREAD

**Issue by texodus** [finos/perspective#1665]
## Feature Request

`perspective-viewer-datagrid` should support all formatting options available via the [`Intl` format API](), via an extension to the Column Style menu with form field entries for options and locale based on column type.

### Description of Problem:
`perspective-viewer-datagrid` already uses these internally, and the `options` object for configuration are JSON friendly.  I am especially interested as these APIs mature, we get new features for free and accessible, e.g. `compact` which newly available in Chrome.  Some permutations of this are already supported via ExprTK, but it won't currently work with the color/style options as you'd need a `string` return type.

**Comment by dhirschfeld** [comment]
Related? https://github.com/finos/perspective/discussions/1478

**Comment by texodus** [comment]
Fixed in #2286
