### ISSUE TITLE
Unexpected behavior with string filtering/views/partial updates

### ISSUE THREAD

**Issue by nickpholden** [finos/perspective#1701]
## Bug Report

This is running on latest Windows python, but I think it's also latest linux. I wouldn't expect to see the none value in the second print as it should be filtered? Think the example is overly verbose sorry

Thanks!! 

import perspective

foo = perspective.Table([{'a': '1', 'b': 2, 'c': '3'}, {'a': '2', 'b': 3, 'c': '4'}, {'a': '3', 'b': 3, 'c': None}], index='a')

view = foo.view(filter=[['c', '==', '4']])

print(view.to_records())

foo.update([{'a': '4', 'b': 10}])

print(view.to_records())

>>>>>>>>>>> 

[{'a': '2', 'b': 3, 'c': '4'}]

[{'a': '2', 'b': 3, 'c': '4'}, {'a': '4', 'b': 10, 'c': None}]

**Comment by texodus** [comment]
Thanks for the report!  This looks like a bug, I'll take a look and get it fixed.

**Comment by texodus** [comment]
This is fixed in #1708 and will be in the `1.1.1` release
