### ISSUE TITLE
CDN example in document doesn't work

### ISSUE THREAD

**Issue by rigogsilva** [finos/perspective#1706]
### Steps to Reproduce:
I am trying to use the CDN option of perspective but the example in the [document](https://perspective.finos.org/docs/md/js.html#from-cdn) doesn't seem to be working properly. 

I tried to create a minimal example and you can see that here. The code is from the documentation:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello Perspective World!</title>
    <script src="https://unpkg.com/@finos/perspective@^1.1.0/dist/umd/perspective.js"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer@^1.1.0/dist/umd/perspective-viewer.js"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer-datagrid@^1.1.0/dist/umd/perspective-viewer-datagrid.js"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer-d3fc@^1.1.0/dist/umd/perspective-viewer-d3fc.js"></script>
</head>
<body>
    <title>
    Hello Perspective World!
    </title>
    <perspective-viewer columns="['Sales', 'Profit']"
      >`
      <script>
        document.addEventListener("DOMContentLoaded", async function () {
          const data = {
            Sales: [500, 1000, 1500],
            Profit: [100.25, 200.5, 300.75],
          };
          // The `<perspective-viewer>` HTML element exposes the viewer API
          const worker = perspective.worker();
          const table = worker.table(data);
          const el = document.getElementsByTagName("perspective-viewer")[0];
          el.load(table);
        });
      </script>
    </perspective-viewer>
</body>
</html>
```

### Expected Result:
* Expected to show the data grid
* Expected to be able to change from DataGrid to Y Bar.

### Actual Result:
* No data is shown in the data grid
* When switching to Y Bar I get a console error: `colorStyles.js:50 Uncaught (in promise) TypeError: Cannot read properties of null`

### Environment:
* macOS Monterey. Mac M1 Pro
* Chrome and Safari

**Comment by rigogsilva** [comment]
<img width="1362" alt="Screen Shot 2022-01-17 at 10 14 53 AM" src="https://user-images.githubusercontent.com/31558765/149804731-a5047ca0-3c63-442a-805a-5a1fb3c739fc.png">

**Comment by texodus** [comment]
You need to [import the `material-dense.css` theme CSS](https://perspective.finos.org/docs/md/js.html#theming) and set some reasonable defaults for the `position` property (`<perspective-viewer>` is a block-level component, which will default to 0 height if you just plop it onto your page).  See the [many working examples](https://bl.ocks.org/texodus) on `bl.ocks.org`, as well as in the [project's `/examples` directory](https://github.com/finos/perspective/tree/master/examples).

There is a typo ` in the docs we'll get fixed, and some updates for the `1.x` branch that haven't been published yet, but the examples should be quite clear and are up-to-date.

```html
<head>
    <script src="https://unpkg.com/@finos/perspective@^1.1.0/dist/umd/perspective.js"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer@^1.1.0/dist/umd/perspective-viewer.js"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer-datagrid@^1.1.0/dist/umd/perspective-viewer-datagrid.js"></script>
    <script src="https://unpkg.com/@finos/perspective-viewer-d3fc@^1.1.0/dist/umd/perspective-viewer-d3fc.js"></script>
    <link rel="stylesheet"  href="https://unpkg.com/@finos/perspective-viewer@^1.1.0/dist/umd/material-dense.css"/>
    <style>
        perspective-viewer {
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
        }
    </style>
</head>
<body>
    <perspective-viewer columns="['Sales', 'Profit']"></perspective-viewer>
    <script>
        const data = {
            Sales: [500, 1000, 1500],
            Profit: [100.25, 200.5, 300.75],
        };
        const worker = perspective.worker();
        const table = worker.table(data);
        const el = document.getElementsByTagName("perspective-viewer")[0];
        el.load(table);
    </script>
</body>
</html>
```
