### ISSUE TITLE
General performance question for wide datasets (400+ columns)

### ISSUE THREAD

**Issue by almackenzie** [finos/perspective#1719]
## Support Question

Apologies if this is not the appropriate forum for this question - I'm interested in perspective for a project I'm working on but have a few general questions about its intended usage/performance.

I'm trying out `perspective-viewer` - pure client side - with an arrow dataset that has approx 400 columns, a mixture of VarCharVector, BigIntVector, Float8Vector, and around 14,000 rows. It's approx 46MB in size. The initial render into a flat datagrid is performant, but when I apply a group by using one of the string columns, it takes a good 10seconds or more to apply, and blocks the GUI thread while it works. I am purely coming at this from a user point of view so I haven't delved into the underlying code but I just have a couple of high level questions to check I haven't missed something:

1) Is this kind of time expected for an aggregation of this size ... is perspective more suitable for fewer columns, more rows?
2) I am surprised the GUI thread is blocked - doesn't all the computation happen in a web worker?

I can't post my full code directly but it's based on the example here - the only difference is that I pull the perspective code from the CDN at runtime (because my project is still using webpack 4), which as I understand it makes initial page load slower but should not affect runtime.

https://github.com/finos/perspective/blob/master/examples/react/src/index.tsx

I guess the relevant bits are:

```
// top level const
const worker = (window as any).perspective.worker();

....

// react component top level:
const viewer = useRef<HTMLPerspectiveViewerElement>(null);
...
// in useEffect. arrayBuffer is the arrow data returned from my API
worker.table(arrayBuffer as any)
                        .then((tbl: any) => {
                            if (viewer.current) {
                                viewer.current.load(tbl);
                            }
                        });
                });
...

// rendered:
...
<perspective-viewer ref={viewer}></perspective-viewer>
...
```

Many thanks in advance for any input or advice.

**Comment by texodus** [comment]
Thanks for the report @almackenzie!

Can you try your data set on [this version of Perspective](https://texodus.github.io/demo-perspective/) and let me know if you see the same performance issue?  I've made a few changes to how the UI is rendered on this fork that I believe will address this.

**Comment by almackenzie** [comment]
Many thanks @texodus , I just tried this against my data (exported as csv from my original) and indeed the grouping is applied an order of magnitude quicker in your new version (sub 1s vs 10s+).
