### ISSUE TITLE
Fire `perspective-config-update` on axis switch for multi-axis charts

### ISSUE THREAD

**Issue by jkusa** [finos/perspective#1729]
### Description of Problem:

Currently, it does not seem that the dual axis configuration can be persisted and restored.

### Potential Solutions:

Add dual axis properties in the `plugin_config` section of the config object.

**Comment by texodus** [comment]
The [`movies` bl.ocks example](https://bl.ocks.org/texodus/6b4dcebf65db4ebe4fe53a6de5ea0b48)'s "Ratings vs Sales" chart is an example of a persistent mutli-Y axis, [`plugin_config` here](https://github.com/finos/perspective/blob/master/examples/blocks/src/movies/layout.json#L161).

Granted, this API is somewhat ambiguously named at the moment.

**Comment by jkusa** [comment]
Ah, ok, that is what `splitMainValues` is for.  So save and restore is good to go 👍 

However, it seems like `perspective-config-update` is not fired when changing axis settings.
