### ISSUE TITLE
Weird behaviour in string match operation in expression

### ISSUE THREAD

**Issue by cihantoraman** [finos/perspective#1758]
## Support Question

I have a question about "match" operator. I don't know if I have a false expectation or it's a bug. Can you please help me to understand correctly.

In my case,
Expression is:
`// mike_zero 
 if (match("name", 'Mike')) {"size" * 0} else {"size"}`

With a couple of update and delete operation below, I encounter this issue in the image. If I understood correctly, mike_zero column of Sarah should not be zero.

```
/**
* STEP 1 ************************
*/
        await table.update([{
          "index": "1",
          "name": "Mike",
          "size": 0.74
        }])

/**
* STEP 2 ************************
*/
        await table.update([{
          "index": "2",
          "name": "Sarah",
          "size": 0.32
        }])

/**
* STEP 3 ************************
*/
        await table.remove(["1"]);
```

<img width="924" alt="image" src="https://user-images.githubusercontent.com/675905/157964470-5d4516e2-ca65-4917-8313-15fda4653b90.png">

Here is the full code:
https://jsfiddle.net/20hw7ajf/2/

Please let me know if there is anything wrong in implementation. 
Thank you.

**Comment by adetsi** [comment]
Hi @cihantoraman I believe this issue has been resolved by @texodus on PR #2311 . Please see diagrams below. @texodus could you please confirm this?

### Without remove

![without_remove](https://github.com/finos/perspective/assets/131965000/859fa546-ce20-456d-ab08-1d6614f37e7a)

### Removing index 1 value
![with_remove](https://github.com/finos/perspective/assets/131965000/36a278e3-91a7-4df2-bafa-a6df715d5c25)
