### ISSUE TITLE
`join` aggregate is incorrect with certain data sets

### ISSUE THREAD

**Issue by zemeolotu** [finos/perspective#1786]
### Steps to Reproduce:
 1. Open attached html

### Expected Result:
'Total' and 'US' row should have the joined value

### Actual Result:
'Total' and 'US' row show null

### Additional Context:
This is a pretty strange bug. It seems to be related to the presence of a null value and the character length of the other value. If you delete one of the characters or change the null to a non-null value then it works as expected.
[join_bug.html.zip](https://github.com/finos/perspective/files/8509397/join_bug.html.zip)

**Comment by texodus** [comment]
This is fixed in `1.5.0`
