### ISSUE TITLE
Add `date`/`datetime` column configuration for Datagrid, based on JavaScript `Intl`

### ISSUE THREAD

**Issue by brianblakely** [finos/perspective#1817]
### Description of Problem:
As an end user, when my data contains date values, I want to specify the display format, so I can render dates appropriately for my use case.

### Potential Solutions:
At present, custom columns have a hamburger button that enables access to edit their expressions. Perhaps static columns can have a button to tweak settings related to their respective data types. In the case of dates, the display format could be one such option.

**Comment by dhirschfeld** [comment]
***xref:*** https://github.com/finos/perspective/discussions/1478

**Comment by texodus** [comment]
Given that `regular-table` uses JavaScript's `Intl` for `Date` formatting and there are a [plethora of formatting options available here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat), IMO it makes sense to attempt to expose most of this API 1:1, with a `plugin_config` that is verbatim an `Intl` locale and options tuple, and a UX that exposes this.   Note this will allow rudimentary timezone fixing when mis-encoded data is provided to Perspective, but this isn't the intended use case - for this we'll need more sophisticated `date`/`datetime` exporTK functionality that allows simple math on these types.

**Comment by brianblakely** [comment]
This is fixed by #1932
