### ISSUE TITLE
Provide complete documentation for Perspective's variant of ExprTK

### ISSUE THREAD

**Issue by brianblakely** [finos/perspective#1818]
### Description of Problem:
As an end user, I want to use custom columns, but the currently-provided documentation for expressions is not user friendly and it is incongruous with Perspective's implementation.

### Potential Solutions:
Provide comprehensive documentation for Perspective's expression engine, with live examples.

**Comment by brianblakely** [comment]
Please take note that I have started a branch to work on this issue
https://github.com/brianblakely/perspective/tree/feature/1818-expression-docs

**Comment by texodus** [comment]
#1903
