### ISSUE TITLE
Handling of zero values in line plots

### ISSUE THREAD

**Issue by maximlt** [finos/perspective#1830]
Hi,

I'm reporting a potential bug first observed by a user of Panel using the Perspective pane (https://github.com/holoviz/panel/issues/3577).

To reproduce the bug I've installed the Python version of Perspective (version `1.3.5`) and ran this code in JupyterLab:

```python
import pandas as pd
import perspective

data = {'x': [1,2,3], 'y': [1, 0, 3]}
df = pd.DataFrame(data)

w = perspective.PerspectiveWidget(data)
w
```

I then chose the `X / Y Line` representation. Hovering the 2nd point, at coordinates [2, 0], doesn't show any tooltip while a tooltip is displayed when the other points are hovered. Hovering that point gives the following error in the web console:

```
Uncaught TypeError: e.mainValues is undefined
    OO perspective-jupyterlab.js:1324
    OO perspective-jupyterlab.js:1324
    RO perspective-jupyterlab.js:1324
    a perspective-jupyterlab.js:1324
    r perspective-jupyterlab.js:1324
    rl perspective-jupyterlab.js:17
    r perspective-jupyterlab.js:1324
    c perspective-jupyterlab.js:1331
    o perspective-jupyterlab.js:1331
    call perspective-jupyterlab.js:17
    t perspective-jupyterlab.js:576
    gh perspective-jupyterlab.js:17
```

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/35924738/171691229-ba803be7-a2ba-4f24-9a4e-598a55089266.png">

**Comment by HariChandana2000** [comment]
is it due to that the value zero is taken as null in javascript?

**Comment by haditya** [comment]
@HariChandana2000  - I think you are on the right track
I think this is coming from selectionData.js - `getDataValues` function
```
    return [
        {
            name: settings.mainValues[0].name,
            value: toValue(
                settings.mainValues[0].type,
                data.colorValue ||
                    data.mainValue - data.baseValue ||
                    data.mainValue ||
                    data.mainValues
            ),
```
I am no javascript expert (not even a beginner :P)  but I was playing around with boolean operations and this is what I observe
`0 || undefined` - is `undefined`
`0.2 || undefined` is `0.2`

Essentially, the fact the we are OR'ing undefined with 0 makes the value continue to be undefined.
I suspect we could handle this in `getDataValues` or in `toValue` and check for `undefined` or `null` in the `float` case

**Comment by haditya** [comment]
```
return [
        {
            name: settings.mainValues[0].name,
            value: toValue(
                settings.mainValues[0].type,
               (data.mainValue === 0 ? data.mainValue : (data.colorValue ||
                    data.mainValue - data.baseValue ||
                    data.mainValue ||
                    data.mainValues))
            ),
```
something like this ought to fix it?
