### ISSUE TITLE
manually select gradient scheme for column in JupyterLab

### ISSUE THREAD

**Issue by zxweed** [finos/perspective#1860]
## Support Question

Hello, how can I specify in the PerspectiveWidget constructor call that I want to use a gradient (or bar) view scheme for certain columns?

**Comment by timkpaine** [comment]
Gradient:
`plugin_config={'columns': {'YOUR COLUMN NAME': {'gradient': MAX VALUE FOR GRADIENT, 'number_color_mode': 'gradient'}}}`

Bar
`plugin_config={'columns': {'YOUR COLUMN NAME': {'gradient': MAX VALUE FOR GRADIENT, 'number_color_mode': 'bar'}}}`
