### ISSUE TITLE
Title for `PerspectiveWidget`

### ISSUE THREAD

**Issue by wangkev** [finos/perspective#1861]
## Feature Request
Add support for title in the perspective widget. In the demo gif, there is an [untitled] title, but I do not think that this is supported in the jupyter widget?

**Comment by timkpaine** [comment]
The example is demoing perspective workspace which is a collection of linked perspective viewers. Perspective workspace lets you do things like rearrange a layout of perspective viewers, cross filter, etc, and one of the features is to name the viewer's window. Perspective viewer has no notion of a "window" on its own, so it does not support setting a title on a window.

The python widget is a wrapper around a perspective viewer, not perspective workspace, so it cannot support setting a title. There is ongoing work to make a python widget out of perspective workspace, and that will support this functionality.
