### ISSUE TITLE
Implement start_of_week and start_of_isoweek functions in expression language

### ISSUE THREAD

**Issue by cythrawll** [finos/perspective#1901]
## Feature Request

We would like functions in order to facilitate date groupings that given a date, returns the date that returns the first day of that week. With another of same idea for isoweek.

### Description of Problem:
The DateTime functions in the expression language seem to be pretty light. We want to given data that has a date in the row to be able to group by and pivot all rows with the same week.

### Potential Solutions:
Add functions expression language that given the date return the `start of` and `end of` certain periods. supported periods could be, day, week, isoweek, month, quarter, or year.  example `start_of("date_field", "week")`

Add functions to expression language simply could be described as `start_of_week` and `start_of_isoweek` however I feel the former would be more valuable to more people.

**Comment by texodus** [comment]
Create an expression column for your `datetime`-typed column `"My Datetime Column"` using `bucket()` with the `'w'` specifier for _week_, then group by this expression column.   The [COVID Example](https://bl.ocks.org/texodus/e074d7d9e5783e680d35f565d2b4b32e) from the examples gallery demonstrates this.

```javascript
{
    expressions: ["bucket(\"My Datetime Column\", 'w')"],
    group_by: ["bucket(\"My Datetime Column\", 'w')"
}
```
