### ISSUE TITLE
Shouldn't the median value for numbers 1 and 2 be equal to 1.5 instead of 2?

### ISSUE THREAD

**Issue by AlexandrOvcharenko** [finos/perspective#1928]
## Support Question

Hi!

During the calculation of the aggregation as the median of an even number of values, I noticed that the result is calculated as the value of the element of the sequence, which is at the position calculated by the "formula" - **Median = n/2 + 1**, where **n** - is the number of elements in the sequence.

Example:

1, 2 - Median = 2
5, 8, 9, 15 - Median = 9

Based on this [source](https://www.scribbr.com/statistics/median/#:~:text=To%20find%20the%20median%2C%20calculate,and%20dividing%20them%20by%20two.) I expect the Median to be 1.5 and 8.5 respectively.

Please tell me if this is the expected behavior of the library? If so, do you have any reference to explain why that logic was chosen.

Thank you very much and wish you good luck :)

I am also attaching a piece of JavaScript code for reproducing:

    const data = [
      {
        Fruit: 'Apple',
        Price: 1,
      },
      {
        Fruit: 'Apple',
        Price: 2,
      },
    ];
    const options: ViewConfig = {
      columns: ['Price'],
      aggregates: { Price: 'median' },
      group_by: ["Fruit"],
    };
    const schema =
    {
      Gender: 'Fruit',
      Price: 'float'
    };
    const table = await perspective.worker().table(schema);
    table.update(data)
    const view = await table.view(options)
    const aggregationResult = await view.to_json();

_aggregationResult here is '[{"__ROW_PATH__":[],"Price":2},{"__ROW_PATH__":[null],"Price":2}]'_

**Comment by sinistersnare** [comment]
The median of the list [1,2] is either 1 or 2 (depending on implementation, here its 2). The _average_ of the list [1,2] is 1.5. 

The [median](https://en.wikipedia.org/wiki/Median) is the middle element of a sorted set of data, it will never be a value that is not in that data.

**Comment by timkpaine** [comment]
The behavior exhibited is expected based on the code, which uses std::nth_element to get the middle element ceil(n/2) (around here https://github.com/finos/perspective/blob/440106c64772d0a83807536edbba079c217323ec/cpp/perspective/src/cpp/sparse_tree.cpp#L1117). It seems like a pretty easy change to make it take an average if this is preferred, we can discuss.

**Comment by texodus** [comment]
This is not expected behavior, its a bug/mis-spec.  [Numeric median is defined as the mean of the nearest values when a set has an even number of elements](https://en.wikipedia.org/wiki/Median), but in Perspective we overload `median()` aggregate type for category columns as well, where no such mean can be calculated, and the common type-naive implementation uses `nth_element()` incorrectly.  I propose we break it into 2 type-specific aggregates (like `median()` and `middle()`), alternatively we could make `median()` type-dispatching internally but this may prove difficult or expensive.

**Comment by orimir** [comment]
@texodus What would be the best approach to implement the proposed solution - breaking into two type-specific aggregates or making median() type-dispatching internally?
