### ISSUE TITLE
how to do internationalization or change to chinese ui please?

### ISSUE THREAD

**Issue by markqiu** [finos/perspective#1934]
how to do internationalization or change to chinese ui please?

**Comment by texodus** [comment]
Perspective is currently only internationalized for the `en-us` locale.  The UI is already uses fully parameterized labels, so new UI locales can mostly be added via CSS [example](https://github.com/finos/perspective/blob/master/rust/perspective-viewer/src/themes/material.less#L99);  the UI should already support locale-determined `number` and `datetime` data representations, as well as full utf-8 support for `string` columns.

I'd merge a pull request adding chinese parameterized labels as in the above example, the type labels may require some creativity in other languages (particularly datetime `mdy` and boolean `t/f`).

**Comment by markqiu** [comment]
A merge request like this is exactly what I need, or I am also willing to submit an MR like this.

**Comment by aswfilip** [comment]
Hello! 
I would also like to contribute to the internationalization of Perspective. @texodus Can you please point me in the right direction? Link for the example no longer works. Thank you!

**Comment by texodus** [comment]
[Internationalization support](https://github.com/finos/perspective/blob/master/rust/perspective-viewer/src/themes/intl.less) was added in #2565
