### ISSUE TITLE
Using sunburst with grouping and tabs results in unresponsive application

### ISSUE THREAD

**Issue by sramcode** [finos/perspective#1938]
### Steps to Reproduce:

1. Create a `perspective-workspace` configuration that includes two tabs in a `tab-area`, and a `group_by` where the plugin is a `Sunburst`
2. `restore()` the configuration on a newly created `perspective-workspace`

The bug is reproduced here: https://codepen.io/sonikar1/pen/BarYPNL
Note: The bug is only reproduced by restoring the configuration, and not by constructing the `perspective-workspace` layout manually. 

### Expected Result:
Sunburst view shows up or application is responsive. 

### Actual Result:
The application is unresponsive.

### Environment:
Latest versions of Perspective on browser.

**Comment by texodus** [comment]
Thanks for the report and especially the excellent repro.  This has been fixed in #1939 and will be in the nest release, along with a [test case based on your repro](https://github.com/finos/perspective/runs/7794655366?check_suite_focus=true#step:20:327)
