### ISSUE TITLE
Night mode not working correctly

### ISSUE THREAD

**Issue by harmichimo** [finos/perspective#1940]
### Steps to Reproduce:
 1. Launch Perspectives using Safari: https://perspective.finos.org
 2. Click on night mode
### Expected Result:
Expected to see background in dark gray and text in white

### Actual Result:
Background was dark grey as expected but text was black, not white
### Environment:
Safari Version 15.4 (17613.1.17.1.13)
Mac OS Monterey Version 12.3.1 (21E258)

### Additional Context:
![image](https://user-images.githubusercontent.com/100539328/184458304-17378e0b-4da5-4362-89ed-ba337f08f551.png)

**Comment by prathamshroff** [comment]
Hi, I believe this issue has been fixed! I tried to replicate the error and didn't face it. @harmichimo @timkpaine please recheck if you'd like but otherwise I think this issue should be closed 👍

**Comment by madhurimatummala** [comment]
Hello, I have tried replicated this issue. I wasn't able to replicate the mentioned issue. The bug seems to be fixed and the issue can be resolved as of now.

**Comment by texodus** [comment]
Bit-rotted, closing
