### ISSUE TITLE
Upgrade or remove lumino dependency

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#1946]
For JupyterLab 4 compat

Xref https://github.com/jupyterlab/jupyterlab/pull/12992

**Comment by afshin** [comment]
There is a partially complete [Lumino 1 → Lumino 2 migration guide](https://lumino.readthedocs.io/en/latest/migration.html) that might be helpful.

**Comment by texodus** [comment]
Closing in favor of the real issue #2307 - what we do with `lumino` is accessory to this.
