### ISSUE TITLE
Autocomplete in filter lists replaces the entire list

### ISSUE THREAD

**Issue by brianblakely** [finos/perspective#1947]
### Steps to Reproduce:
1. Open viewer config panel.
2. Filter with "in" function.
3. Add more than one value, attempting to add any value after the first via autocomplete.

### Expected Result:
The autocomplete should only populate the value for the currently-edited item in the "in" list.

### Actual Result:
The entire list is replaced with the autocompleted value.

### Environment:
v1.6.4, Chrome

**Comment by madhurimatummala** [comment]
This code snippet ensures that only currently edited item in the "in" list is replaced with the autocompleted value, while leaving the rest of the list unchanged.
`function handleAutocomplete(selectedItem, autocompletedValue) {
  const selectedItemIndex = list.indexOf(selectedItem);
  if (selectedItemIndex !== -1) {
    list[selectedItemIndex] = autocompletedValue;
  }
}
const selectedItem = getSelectedItem();
const autocompletedValue = getAutocompletedValue();
handleAutocomplete(selectedItem, autocompletedValue);`

**Comment by brianblakely** [comment]
This was fixed. Cheers 👍🏻
