### ISSUE TITLE
plugin selection dropdown: header background wrong with dark-mode

### ISSUE THREAD

**Issue by texodus** [finos/perspective#1956]
### Discussed in https://github.com/finos/perspective/discussions/1954

<div type='discussions-op-text'>

<sup>Originally posted by **GREEB** August 26, 2022</sup>
Seems like a dark-mode problem, in light-mode everything seems fine.
(sorry for GIFS hard to screenshot these menus)

### Steps to Reproduce:
 1. Open Chromium
 2. Go to [official example](https://bl.ocks.org/texodus/6b4dcebf65db4ebe4fe53a6de5ea0b48) ```Perspective / Movies``` this should be on ```@latest```
 3. Open the plugin selection menu

### Expected Result:
The option headers should be the same background as the options like it is in  ```Firefox 103.0.2 (64-bit)```
![Peek 2022-08-27 01-27](https://user-images.githubusercontent.com/1221769/187002650-60c33a8d-e768-40da-8d88-66ace1b22dee.gif)

### Actual Result:
This happens with ```Chromium Version 104.0.5112.79```, the option headers are not the same background as the options
![Peek 2022-08-27 01-28](https://user-images.githubusercontent.com/1221769/187002647-973dc824-a1e2-4ebb-84db-2085f1a65938.gif)

### Environment:
```Chromium Version 104.0.5112.79 (Official Build) Arch Linux (64-bit)```
Reproduced on: ```Chromium Version 104.0.5112.101 (Official Build) Pop!_OS 22.04 LTS(64-bit)```

### Cause
Seems like Chromium does not like to have ```background-color``` on top of ```background```, Firefox has no problems with that:
#### Chrome:
![image](https://user-images.githubusercontent.com/1221769/187003611-ef4d94fa-27c7-482a-ba28-8df0b8197e31.png)

#### Firefox:
![image](https://user-images.githubusercontent.com/1221769/187004766-84611691-f9ad-4b20-8879-81a3e27106d9.png)
(Firefox doesn't even need the ```background-color``` to render the options right, at least on my system)
### Fix
This is probably a bad idea but what i found is: when putting background-color underneath background, chromium applies it as expected:
![image](https://user-images.githubusercontent.com/1221769/187004865-6aa13c2e-1583-4888-b5e7-d85e0787bb1f.png)

![Peek 2022-08-27 01-50](https://user-images.githubusercontent.com/1221769/187004900-278281ef-6c5b-4739-ba80-0808ec47fa16.gif)</div>

**Comment by GREEB** [comment]
i was able to fix this by adding 
```css
optgroup{
    background: var(--select--background-color, #ffffff);
}
```
to ```rust/perspective-viewer/src/less/dom/select.less``` ```select```

the proposed fix (putting background-color underneath background) would have unwanted side-effects:
![image](https://user-images.githubusercontent.com/1221769/187782164-e42fe8df-e002-4d9f-a12f-3564d09928e3.png)
