### ISSUE TITLE
Conda installs include pip extras as of 1.6.5

### ISSUE THREAD

**Issue by tim-hutchinson** [finos/perspective#1965]
### Steps to Reproduce:
```
conda install -c conda-forge perspective
```

### Expected Result:
Perspective installed with its core dependencies only

### Actual Result:
Perspective is installed along with `jupyterlab`, `tornado`,  `fastapi` etc.

### Environment:
Perspective 1.6.5, installed via conda in a Docker image, with Jupyterlab in one virtual environment and our runtime python in another.

### Additional Context:
We were troubleshooting version conflicts we were seeing after upgrading from 1.4.0 (for some reason conda can't resolve the pyarrow versions between perspective and `awswrangler`) and noticed that starting in 1.6.5 `perspective` on conda-forge now includes some heavyweight extra packages in webservers and jupyterlab.

We use Perspective from withing Jupyterlab, but we launch the Lab in one Python environment and the python kernel in another. Perspective gets installed into the kernel virtual environment. This has been working well for us and lets us version Jupyter separately from notebook code. However, with this change, we're now getting another entire Jupyter and web server environment installed that we'd like to avoid.

**Comment by timkpaine** [comment]
The version of perspective and jupyterlab need to match inside the kernel and jupyter environments, so this is a good thing. Feel free to open an issue on https://github.com/conda-forge/perspective-feedstock/issues however, conda does not support `extras` in the same way so you may prefer `--no-deps` and managing your own set of dependencies.
