### ISSUE TITLE
Perpective Breaking with Big Dataset

### ISSUE THREAD

**Issue by akash-goel** [finos/perspective#1972]
Hi Team ,

We are trying to visualize 18 million records , when we are trying to send records on UI , we are getting  SBOX_FATAL_MEMORY_EXCEEDED after 1 million records.

![image](https://user-images.githubusercontent.com/5937612/191784742-3df17eb8-4bbc-4ffe-8cb5-d25cb0d16682.png)

it would be helpful if you can guide that will 18 million records at a time will work or not , or what is the max no of records we can view in UI using perpective.

Regards,
Akash

**Comment by timkpaine** [comment]
Not directly related to perspective, your browser has run out of memory:
https://www.chromestory.com/2020/06/sbox-fatal-memory-exceeded/
