### ISSUE TITLE
Turn on/off Thousand Separator (comma) for numbers

### ISSUE THREAD

**Issue by KrishnaPG** [finos/perspective#2021]
## Feature Request

The viewer table is adding thousand separators (commas) automatically to all number fields. But in some cases, such as the Year field the commas should not be added. It would be nice to control the format of the numbers in the table view through UI control.

### Description of Problem:
There is currently no way to control the `number` type field display behavior. E.g. Thousand separators are automatically added to the number and there does not seem to be anyway to control this behavior.
![image](https://user-images.githubusercontent.com/4610831/204192882-4fd24bc9-3ec9-43a6-bec9-4236655a6e69.png)

### Potential Solutions:
It would be nice to control the "presentation" of the `number` field. For example, the `string` types are already allowing few format options (shown below). Similary it would be great to expose the format options for numbers also to control whether thousand separators should be applied or not for a particular field (and any other relevant options).
![image](https://user-images.githubusercontent.com/4610831/204193057-282a8db0-03b6-4c50-a948-07365e23e5cd.png)

There was a suggestion [here](https://github.com/finos/perspective/discussions/2020) about pre-processing the data to change the number type to string or other: while this is a work around, changing the type of the field makes it loose the "number"-like properties. Since this is a presentation (view) problem it is better to control the "presentation" format through UI than changing the underlying type of the data to fit the view.

**Comment by texodus** [comment]
Not implementing this, presentation of numbers is handled by the browser's locale.

**Comment by KrishnaPG** [comment]
What does browser locale has to do with your component? 

- Is your component reading the browser locale? If so, you **should** allow in your UI to control that format behavior.

To put things in context, we display dozens of numbers on the screen, none of them are rendered "incorrectly" except your viewer (refer the screenshot below)

![image](https://user-images.githubusercontent.com/4610831/204197826-4734d6a2-5f99-45d8-bb68-99a3a102198c.png)

Please add a UI control in your number format option to control this thousand separator behavior. There is already a `precision` control there.

![image](https://user-images.githubusercontent.com/4610831/204198278-0bfe3dfe-47d5-4804-8d55-1d5249a12ac6.png)

**Comment by texodus** [comment]
Please stop spamming us - maybe instead invest that time into [educating yourself on how a browser works](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString).
