### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by dhirschfeld-shell** [finos/perspective#2059]
## Bug Report

In JupyterLab the `PerspectiveWidget` fails to render with the above error message.

In the JS console I see the below error message:
```
Error: Module @finos/perspective-jupyterlab, semver range ~1.7.1 is not registered as a widget module
```

### Steps to Reproduce:
In JupyterLab:
```python
data = pd.DataFrame({
    "int": np.arange(100),
    "float": [i * 1.5 for i in range(100)],
    "bool": [True for i in range(100)],
    "date": [date.today() for i in range(100)],
    "datetime": [datetime.now() for i in range(100)],
    "string": [str(i) for i in range(100)]
})
table = perspective.Table(data, index="float")
perspective.PerspectiveWidget(table)
```

### Expected Result:

The perspective widget displayed

### Actual Result:
```
Error displaying widget: model not found
```
Output in JupyterLab. JS console output below:

![image](https://user-images.githubusercontent.com/107382673/208564723-0065baf6-562f-4b56-9b00-966d6373c527.png)

### Environment:
* `perspective` 1.7.1
* `ipywidgets` 7.7.2
* JupyterLab 3.5.1

All packages installed from `conda-forge`

**Comment by dhirschfeld-shell** [comment]
Yep, I thought this was a prebuilt extension but I see that's still a work in progress - #1976.

Unfortunately install the JS labextension hasn't worked and I'm still trying to debug...

**Comment by zxweed** [comment]
Faced the same problem, however, the solution above doesn't help. What else can I check?

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/16319433/208687667-8d31fe76-637f-4f01-bbf5-5ba31eb5d9a9.png">

**Comment by timkpaine** [comment]
Your python and JavaScript have to match (up to a minor version), this is a JupyterLab check not a perspective check.

**Comment by zxweed** [comment]
@timkpaine, thanks for reply. I cleaned the yarn cache, removed any suspicious packages, then installed perspective again:
```
 conda install -c conda-forge perspective 
 jupyter labextension install @finos/perspective-jupyterlab@1.7.1 
 jupyter lab build 
 ```

 The problem persists. The versions of the packages are:
 
**$>conda list | grep -E "perspective|widget"**
 ```
ipywidgets                7.6.6              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
perspective               1.7.1            py39h8208f0e_1    conda-forge
widgetsnbextension        3.5.2            py39h06a4308_0
```

**$>ls ~/anaconda3/share/jupyter/lab/extensions**
`finos-perspective-jupyterlab-1.7.1.tgz`

I tried to update the **jupyterlab_widgets** package to version 3.0.4 from the conda-forge repository, but this did not solve the problem, only adding other startup errors.

What else could this problem be related to?

**Comment by timkpaine** [comment]
There is no problem, please follow the instructions in a clean environment.
