### ISSUE TITLE
build error when run scripts/build_js.js

### ISSUE THREAD

**Issue by shinnqy** [finos/perspective#2080]
## Support Question

Hi, I'm trying to run `scripts/build_js.js`. But it hit the error `'boost/multiprecision/cpp_int.hpp' file not found`. I already run `node scripts/install_tools.js`, so I cannot figure out what missed. Would you please help me how to resolve this?

![image](https://user-images.githubusercontent.com/15121888/212556165-98d2f66c-d53a-4213-894e-2201313e3b45.png)

### Follow up
I've resolved this by installing boost with another guide from google result.

But then I hit another error.
![image](https://user-images.githubusercontent.com/15121888/212559472-20315631-ea3b-42a6-a59f-aa9f9c106c7a.png)

**Comment by sinistersnare** [comment]
Did you try installing boost with

```sh
node scripts/installl_tools.js
```

**Comment by shinnqy** [comment]
The same. It will finally run `node build.js`
<img width="413" alt="image" src="https://user-images.githubusercontent.com/15121888/212690225-69de2bca-65e5-41ea-bedc-28f9de1da42d.png">
