### ISSUE TITLE
build error when run yarn build

### ISSUE THREAD

**Issue by shinnqy** [finos/perspective#2083]
## Support Question

Why close this issue? https://github.com/finos/perspective/issues/2080

I already tried `yarn & yarn setup & yarn build`. The same error.

And. once you have run yarn setup, it's the same to run `node build_js.js`, right?
<img width="428" alt="image" src="https://user-images.githubusercontent.com/15121888/212694092-7de64ef0-ef20-4965-ab8f-a96034419c99.png">

**Comment by texodus** [comment]
This issue should've been converted to a discussion, I've done so [here](https://github.com/finos/perspective/discussions/2084).  Please use this in lieu of "Issues".
