### ISSUE TITLE
DOMException CustomElementRegistry dupe on esbuild example

### ISSUE THREAD

**Issue by davisford** [finos/perspective#2091]
### Steps to Reproduce:
 1.  Check out finos/perspective repo 
 2. Copy examples/esbuild-example to tmp/ (Doing this b/c whole repo has higher-level package-lock.json which screws up yarn install paths
 4. cd /tmp/esbuild-example
 5. yarn install
 6. yarn start
 7.  open http://localhost:8080

Console Output:

```sh
➜ yarn start
yarn run v1.22.19
$ yarn build && http-server dist
$ node build.js
Starting up http-server, serving dist
Available on:
  http://127.0.0.1:8080
  http://192.168.25.68:8080
Hit CTRL-C to stop the server
[2023-01-25T16:53:25.933Z] "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
(node:12630) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
[2023-01-25T16:53:25.971Z] "GET /perspective_viewer_bg.wasm" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
[2023-01-25T16:53:25.972Z] "GET /editor.worker.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
[2023-01-25T16:53:25.973Z] "GET /perspective_viewer_bg.wasm" Error (404): "Not found"
[2023-01-25T16:53:25.973Z] "GET /editor.worker.js" Error (404): "Not found"
```

### Expected Result:
Loads a datagrid at http://localhost:8080

### Actual Result:
Fails to load several resources it wants, and has duplicate registrations in browser's CustomElementRegistry which cause the whole thing to fail.

![Screen Shot 2023-01-25 at 11 59 11 AM](https://user-images.githubusercontent.com/186677/214629388-18a3a42e-0b2f-4160-8c05-735014e6bb73.png)

### Environment:

Mac OS Monterey, M1 chip, no virtual environment.

```
commit e0fbceba02cd65e0ed031b6d60a3eb6b288cf341 (HEAD -> master, tag: v1.9.3, origin/master, origin/HEAD)
Author: Andrew Stein <steinlink@gmail.com>
Date:   Thu Jan 19 14:43:04 2023 -0500

    v1.9.3
```

### Additional Context:

It doesn't appear that esbuild plugin is copying all the things it needs to in the `dist` folder?

```sh
➜ tree dist
dist
├── index.css
├── index.html
├── index.js
├── perspective.cpp.wasm
├── perspective.worker.js
├── perspective_bg.wasm
└── superstore.arrow

1 directory, 7 files
```

```sh
➜ tree build
build
└── worker
    └── perspective.worker.js
```

**Comment by davisford** [comment]
It looks like one of the `.wasm` files was referenced incorrectly in the HTML pre-load or was later re-named.  If I change this line in `index.html`

```html
<link rel="preload" href="perspective_viewer_bg.wasm" as="fetch" type="application/wasm" crossorigin="anonymous">
```

to this instead:

```html
<link rel="preload" href="perspective_bg.wasm" as="fetch" type="application/wasm" crossorigin="anonymous">
```

The data grid now loads.  However, I'm not sure why it is trying to load `editor.worker.js` or whether it needs it for this example?  That still returns a 404.

**Comment by texodus** [comment]
@davisford I can't tell what your issue was from the information provided, but I am certain it's unrelated to `<link rel="preload">`.  The error seems to indicate you built/linked the project twice - perhaps you had a prior build of perspective in `/dist`?
