### ISSUE TITLE
Is the schema for perspective-workspace layout documented anywhere?

### ISSUE THREAD

**Issue by davisford** [finos/perspective#2093]
## Support Question

There are many examples with a `layout.json` file that are loaded / restored into the `perspective-workspace` but after combing through some of the source, I haven't found anywhere in the source or docs specifically that describe the JSON schema, and exactly what the fields mean or do.

I was just curious if there was any documentation related that maybe I missed?

**Comment by sinistersnare** [comment]
If you would like to see a schema for example, you can create a layout you would like to save, and call:

```
await viewer.save()
```

This will return the JSON for the layout. You can tweak it from there.

**Comment by davisford** [comment]
Yea, I know that.  I can see many examples.  I just don't know for sure what all the fields are for.  I think I found my answer.  It appears to be based off `@lumino` widget `DockPanel` which seems to have the documentation defined in the source code: https://github.com/jupyterlab/lumino/blob/main/packages/widgets/src/docklayout.ts

I'll go ahead an close this out.

**Comment by texodus** [comment]
@davisford `@finos/perspective-workspace` itself is not documented (but it is used in several examples).  This component is unfortunately not quite ready for general use.  It's undergoing a rewrite at the moment and will see docs released when it is "officially" supported (where it may live under a new package name, we'll see).

**Comment by davisford** [comment]
@texodus is there a roadmap I can follow for the re-work on this?
