### ISSUE TITLE
Link to Perspective Viewer Documentation in README file is broken

### ISSUE THREAD

**Issue by riziles** [finos/perspective#2096]
### Description of Problem:

The Link in `README.md > Documentation > API > Perspective Viewer API` generates a 404

### Potential Solutions:

I believe that it should point here: 

<https://perspective.finos.org/docs/obj/perspective-viewer/>

**Comment by franher** [comment]
Hello, I've been reviewing the issues labelled with "good first issue", trying to find some topics to start contributing to. I think this issue may be closed because #2098 fixed it.

Thank you.
