### ISSUE TITLE
Hover-expanding buttons in the menu bar are wonky on Firefox

### ISSUE THREAD

**Issue by texodus** [finos/perspective#2115]
### Steps to Reproduce:
 1. Hover over the "Theme" button, click the dropdown but then click away (lose focus) without selecting a theme.
 2. Try to select a theme again

### Expected Result:
The them should change

### Actual Result:
Carnage.  It looks like sometimes, the container element loses hover/focus state when the dropdown is open, causing the container to collapse and break the dropdown.  This is _certainly_ a Firefox bug, as it can only be triggered by collapsing the container when the dropdown is in an open state.

### Environment:
Firefox

**Comment by supreeth99** [comment]
To address this issue, the following steps can be taken:

1. Implement a listener for the container element's blur event. This event will be triggered when the container loses focus.
2. check if the dropdown is open when the container loses focus.
3. If the dropdown is open, prevent the container from collapsing and maintain its hover/focus state until a theme is selected or the dropdown is closed.
4. Additionally, ensure that the container's hover/focus state is properly managed when interacting with the dropdown.

Javascript solution :
// Get references to the container and dropdown elements
const container = document.getElementById('container');
const dropdown = document.getElementById('dropdown');

// Flag to track if the dropdown is open
let isDropdownOpen = false;

// Event listener for container blur event
container.addEventListener('blur', () => {
  // Check if the dropdown is open and the browser is Firefox
  if (isDropdownOpen && navigator.userAgent.includes('Firefox')) {
    // Prevent container from collapsing
    container.style.display = 'block';
    // Maintain hover/focus state
    container.focus();
  }
});

// Event listener for dropdown open event
dropdown.addEventListener('open', () => {
  // Set the dropdown open flag to true
  isDropdownOpen = true;
});

// Event listener for dropdown close event
dropdown.addEventListener('close', () => {
  // Set the dropdown open flag to false
  isDropdownOpen = false;
});

Or we can address this issue by adding this in css file: 

.container:focus-within:not(:focus) {
  display: block;
}

Hope this helps!!

**Comment by RadhaGavade01** [comment]
There is a bug in Firefox causing the container element to lose hover/focus state when the dropdown is open, causing the container to collapse and break the dropdown. This bug can only be triggered by collapsing the container when the dropdown is in an open state.

**Comment by texodus** [comment]
Thanks for the report. I've consolidated this and other Firefox issues into #2693, closing.
