### ISSUE TITLE
WebSocketClient Memory leak on send ping timeout - it should be cleared on terminate

### ISSUE THREAD

**Issue by dtassone** [finos/perspective#2146]
When you open a WebClientSocket and terminate. I expect the socket to not send more messages but it does as the setTimeout for sending ping messages is not cleared.

https://github.com/finos/perspective/blob/379cb3845135b5910b0c1637c9627d0bddf97842/packages/perspective/src/js/websocket/client.js#L31

https://github.com/finos/perspective/blob/master/packages/perspective/src/js/websocket/client.js#L155

**Comment by texodus** [comment]
Thanks for the report, this is fixed in #2151 and will be in the next release.
