### ISSUE TITLE
Website a11y: no keyboard access to buttons

### ISSUE THREAD

**Issue by julianna-ciq** [finos/perspective#2171]
### Description of Problem:
The homepage of the Perspective website includes a series of buttons with the labels: "Sparkgrid", "Datagrid", "X Bar", "Y Line", "XY Scatter", "Treemap", and "Heatmap". 

While they are visually buttons, they are semantically DIVs, with nothing that helps provide access for keyboard-only users. The functionality of these buttons (changing the kind of datagrid/chart that's being displayed) is inaccessible.

### Potential Solutions:
1. Change the `<div>`'s to `<button>`'s. You could still maintain the current aesthetic, though the onMouseOver functions would need to be duplicated with onClick. (The equivalent to onMouseOver would actually be onFocus, but it's not a best practice to change contexts when elements receive focus, so I'd recommend duplicating with an onClick function
2. Adding `tabIndex=0` and a keydown handler to the `<div>`'s.

I'm willing to implement this change.

**Comment by timkpaine** [comment]
> chane the `<div>` to `<button>`
I think you can just give the `div` `role=“button”`?

**Comment by julianna-ciq** [comment]
We can give the DIV's `role="button"`, which will tell screen readers to call out the element as a button. (Screen reader will read "Sparkgrid, button" instead of the current "Sparkgrid")

However, we will still need to add `tabIndex="0"` so that the element is added to the tab order, and a keydown event handler to that press SPACEBAR or ENTER will do something.

I wish adding `role="button"` accomplished all of that, but we have to wire each of those up ourselves.

**Comment by julianna-ciq** [comment]
https://github.com/finos/perspective/pull/2174

**Comment by texodus** [comment]
See comments on PR.  Addressing accessibility is good, but let's not do this one button at a time.
