### ISSUE TITLE
Error: Cannot find module 'stoppable'

### ISSUE THREAD

**Issue by Khalilsqu** [finos/perspective#2183]
### Steps to Reproduce:
1. Next JS app
2. No use of npm perspective-webpack-plugin
3. `import * as perspective from "@finos/perspective";`

I keep getting this error

![image](https://user-images.githubusercontent.com/22060413/230987205-dfd92eb6-0b18-4824-a342-ad1733ae7ac5.png)

```
import * as perspective from "@finos/perspective";

export default function Students() {
  return <h1>Students</h1>;
}

```

**Comment by sinistersnare** [comment]
This looks unrelated to Perspective. Post full source code please.

**Comment by yangjunhan** [comment]
Hi, @Khalilsqu. I encountered the same problem. Looks like the latest upgrade (v2.0.0) of Perspective introduced a new dependency. Try `npm i -D stoppable` and put it in your webpack plugin custom config:
```typescript
webpackConfig.resolve.fallback = {
    stoppable: require.resolve('stoppable')
  };
```

This helped me resolve this issue.

**Comment by texodus** [comment]
> 1. Next JS app

@Khalilsqu This is not an adequate repro. I don't know even which version of the library you are trying to import -  `webpack` and the perspective module that imports `stoppable` (node.js) are mutually exclusive AFAIK.

This dependency does look like its missing so I'll add it, but as you've provided no repro I can't verify it does anything for you, so closing. Please use the [error template](https://github.com/finos/perspective/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) when you file issues and provide as much detail as possible in the future.

**Comment by riziles** [comment]
@texodus , I have been able to replicate simply by upgrading to Perspective 2.2.1 in a deployment that was working fine on 1.9.4. Please see pull request here: <https://github.com/riziles/svelte-perspective-starter1/pull/2> the Vercel preview deployments show server errors. The log files all point to the missing `stoppable` dependency.
