### ISSUE TITLE
`color` column field does not work with `string` typed columns in `"X/Y Scatter"` chart

### ISSUE THREAD

**Issue by texodus** [finos/perspective#2199]
### Steps to Reproduce:
Create an `X/Y Scatter` chart, with a `string` field in column position 3. As discusssed in #1487 

### Expected Result:
A chart with category-colored scatter points, ala `Treemap` and `Sunburst` charts.

### Actual Result:
A console error and no chart

### Environment:
Chrome

**Comment by jaivardhan-bhola** [comment]
can i work on this ?

**Comment by jaivardhan-bhola** [comment]
can I work on this issue? Also can I know what file needs to be changed?

**Comment by texodus** [comment]
@jaivardhan-bhola please stop the spam, you can ask questions in [Discussion](https://github.com/finos/perspective/discussions).

**Comment by jaivardhan-bhola** [comment]
I just want to work on this?

**Comment by RadhaGavade01** [comment]
Solution is to check the configuration of the X/Y Scatter chart and ensure that it is properly set up to display the string field in column position 3 as a category color. It's possible that there is a bug in the chart configuration that is causing the chart to fail.

**Comment by texodus** [comment]
Fixed in #2303
