### ISSUE TITLE
Incorrect timezone offset when using datetime filters

### ISSUE THREAD

**Issue by ming08108** [finos/perspective#2203]
## Bug Report

Datetime filters do not respect DST.

### Steps to Reproduce:
1. Create a table with a datetime column
2. Add a where clause on that datetime column

### Expected Result:
Rows should be correctly filtered.

### Actual Result:
Rows are filtered but the filtered time could be off by 1 hour due to DST offsets.

### Environment:
Any

### Additional Context:

Problematic code is likely here: https://github.com/finos/perspective/blob/91102a05032a133e8648032f7f3d7c8f84998076/rust/perspective-viewer/src/rust/utils/datetime.rs#L24

`new Date(0).getTimezoneOffset() != new Date(1682122531000).getTimezoneOffset()` in all timezones.

**Comment by texodus** [comment]
Duplicate #2023
