### ISSUE TITLE
Broken Link in Docs

### ISSUE THREAD

**Issue by riziles** [finos/perspective#2212]
I believe the following link:

https://github.com/finos/perspective/blob/e89ae0ab2aca1d903a0d3738ee2e8d9f67c1c684/packages/perspective/README.md?plain=1#L7

which shows up in the docs here: https://perspective.finos.org/docs/obj/perspective/

should point here instead:

https://perspective.finos.org/docs/js/

**Comment by ayushkcs** [comment]
Hi @riziles @timkpaine ,
Can I please try to fix this?
Thanks

**Comment by texodus** [comment]
Appreciate the report @riziles, we'll fix this.

Closing as to dissuade future PRs that exclusively update links or spelling - the notification of the issue is enough for now.
