### ISSUE TITLE
The switchover configuration of the production environment is incorrect

### ISSUE THREAD

**Issue by leet-code-master** [finos/perspective#2245]
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'opacity')
    at ol (perspective-viewer-d3fc.js:18:3658)
    at wo (perspective-viewer-d3fc.js:18:3263)
    at HTMLElement.update (perspective-viewer-d3fc.js:18:18438)
    at async HTMLElement.draw (perspective-viewer-d3fc.js:18:16954)

**Comment by leet-code-master** [comment]
perspective-viewer-d3fc.js:18 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'opacity')
    at ol (perspective-viewer-d3fc.js:18:3658)
    at wo (perspective-viewer-d3fc.js:18:3263)
    at HTMLElement.update (perspective-viewer-d3fc.js:18:18438)
    at async HTMLElement.draw (perspective-viewer-d3fc.js:18:16954)
ol @ perspective-viewer-d3fc.js:18
wo @ perspective-viewer-d3fc.js:18
update @ perspective-viewer-d3fc.js:18
Promise.then (async)
n.wbg.__wbg_then_ec5db6d509eb475f @ perspective-viewer.js:10
$func2920 @ 005b26a6:0xeeeae
$func5388 @ 005b26a6:0x12098a
$func4501 @ 005b26a6:0x1125b4
$func5958 @ 005b26a6:0x127cc3
$func1722 @ 005b26a6:0xc2c84
$func4264 @ 005b26a6:0x10dccc
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_f753623316e2873a @ perspective-viewer.js:10
$func823 @ 005b26a6:0x8b165
$func314 @ 005b26a6:0x1c6bf
$func597 @ 005b26a6:0x720e3
$func398 @ 005b26a6:0x49df4
$func992 @ 005b26a6:0x98897
$func1296 @ 005b26a6:0xabc54
$func4808 @ 005b26a6:0x117ac8
$func705 @ 005b26a6:0x7f32c
$func1025 @ 005b26a6:0x9aba6
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_ec5db6d509eb475f @ perspective-viewer.js:10
$func2920 @ 005b26a6:0xeeeae
$func5388 @ 005b26a6:0x12098a
$func4501 @ 005b26a6:0x1125b4
$func5958 @ 005b26a6:0x127cc3
$func1722 @ 005b26a6:0xc2c84
$func4265 @ 005b26a6:0x10dd14
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_f753623316e2873a @ perspective-viewer.js:10
$func823 @ 005b26a6:0x8b165
$func1440 @ 005b26a6:0xb38ed
$func314 @ 005b26a6:0x1bd9d
$func597 @ 005b26a6:0x720e3
$func398 @ 005b26a6:0x49df4
$func992 @ 005b26a6:0x98897
$func1296 @ 005b26a6:0xabc54
$func4808 @ 005b26a6:0x117ac8
$func705 @ 005b26a6:0x7f32c
$func1025 @ 005b26a6:0x9aba6
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_ec5db6d509eb475f @ perspective-viewer.js:10
$func2920 @ 005b26a6:0xeeeae
$func5388 @ 005b26a6:0x12098a
$func4501 @ 005b26a6:0x1125b4
$func5958 @ 005b26a6:0x127cc3
$func1722 @ 005b26a6:0xc2c84
$func4265 @ 005b26a6:0x10dd14
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_f753623316e2873a @ perspective-viewer.js:10
$func823 @ 005b26a6:0x8b165
$func1439 @ 005b26a6:0xb3807
$func314 @ 005b26a6:0x1bc68
$func597 @ 005b26a6:0x720e3
$func398 @ 005b26a6:0x49df4
$func992 @ 005b26a6:0x98897
$func1296 @ 005b26a6:0xabc54
$func4808 @ 005b26a6:0x117ac8
$func705 @ 005b26a6:0x7f32c
$func1025 @ 005b26a6:0x9aba6
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_ec5db6d509eb475f @ perspective-viewer.js:10
$func2920 @ 005b26a6:0xeeeae
$func5388 @ 005b26a6:0x12098a
$func4501 @ 005b26a6:0x1125b4
$func5958 @ 005b26a6:0x127cc3
$func1722 @ 005b26a6:0xc2c84
$func4265 @ 005b26a6:0x10dd14
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_f753623316e2873a @ perspective-viewer.js:10
$func823 @ 005b26a6:0x8b165
$func1440 @ 005b26a6:0xb38ed
$func478 @ 005b26a6:0x5d504
$func597 @ 005b26a6:0x71fff
$func398 @ 005b26a6:0x49df4
$func992 @ 005b26a6:0x98897
$func1296 @ 005b26a6:0xabc54
$func4808 @ 005b26a6:0x117ac8
$func705 @ 005b26a6:0x7f32c
$func1025 @ 005b26a6:0x9aba6
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_ec5db6d509eb475f @ perspective-viewer.js:10
$func2920 @ 005b26a6:0xeeeae
$func5388 @ 005b26a6:0x12098a
$func4501 @ 005b26a6:0x1125b4
$func5958 @ 005b26a6:0x127cc3
$func1722 @ 005b26a6:0xc2c84
$func4265 @ 005b26a6:0x10dd14
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_f753623316e2873a @ perspective-viewer.js:10
$func823 @ 005b26a6:0x8b165
$func1401 @ 005b26a6:0xb183f
$func478 @ 005b26a6:0x5d4bb
$func597 @ 005b26a6:0x71fff
$func398 @ 005b26a6:0x49df4
$func992 @ 005b26a6:0x98897
$func1296 @ 005b26a6:0xabc54
$func4808 @ 005b26a6:0x117ac8
$func705 @ 005b26a6:0x7f32c
$func1025 @ 005b26a6:0x9aba6
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_ec5db6d509eb475f @ perspective-viewer.js:10
$func2920 @ 005b26a6:0xeeeae
$func5388 @ 005b26a6:0x12098a
$func4501 @ 005b26a6:0x1125b4
$func5958 @ 005b26a6:0x127cc3
$func1722 @ 005b26a6:0xc2c84
$func4265 @ 005b26a6:0x10dd14
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_f753623316e2873a @ perspective-viewer.js:10
$func823 @ 005b26a6:0x8b165
$func1321 @ 005b26a6:0xad2cd
$func354 @ 005b26a6:0x3853f
$func655 @ 005b26a6:0x7959a
$func992 @ 005b26a6:0x9882e
$func1296 @ 005b26a6:0xabc54
$func4808 @ 005b26a6:0x117ac8
$func705 @ 005b26a6:0x7f32c
$func1025 @ 005b26a6:0x9aba6
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_ec5db6d509eb475f @ perspective-viewer.js:10
$func2920 @ 005b26a6:0xeeeae
$func5077 @ 005b26a6:0x11bfd9
$func2180 @ 005b26a6:0xd671a
$func7159 @ 005b26a6:0x133706
$func3349 @ 005b26a6:0xfa3b7
$func3448 @ 005b26a6:0xfca24
$func908 @ 005b26a6:0x92338
$func628 @ 005b26a6:0x76138
$func5049 @ 005b26a6:0x11b914
$func842 @ 005b26a6:0x8cb82
$func1154 @ 005b26a6:0xa3463
$func2246 @ 005b26a6:0xd8e09
$func1332 @ 005b26a6:0xadd39
$func6867 @ 005b26a6:0x131a25
$func1025 @ 005b26a6:0x9aba6
$__wbindgen_export_8 @ 005b26a6:0x131a68
he @ perspective-viewer.js:10
s @ perspective-viewer.js:10
Promise.then (async)
n.wbg.__wbg_then_ec5db6d509eb475f @ perspective-viewer.js:10
$func2920 @ 005b26a6:0xeeeae
$func5077 @ 005b26a6:0x11bfd9
$func2180 @ 005b26a6:0xd671a
$func7159 @ 005b26a6:0x133706
$func3349 @ 005b26a6:0xfa3b7
$func4956 @ 005b26a6:0x11a16a
$func3501 @ 005b26a6:0xfddb6
$func5483 @ 005b26a6:0x121e37
$func8031 @ 005b26a6:0x137203
$func401 @ 005b26a6:0x4afc7
$__wbindgen_export_9 @ 005b26a6:0x11e540
xe @ perspective-viewer.js:10
s @ perspective-viewer.js:10

**Comment by zumbalogy** [comment]
I seem to be experiencing the same problem with `vite@7.0.6`
