### ISSUE TITLE
TableData Error

### ISSUE THREAD

**Issue by UKEYBHAKTI002922939** [finos/perspective#2247]
### Steps to Reproduce:
 1. Open the code in Pycharm
 2. Edit componentDidUpdate()
 3. add if (this.table) {
        this.table.update([
            DataManipulator.generateRow(this.props.data),
      ] as unknown as TableData);
    }

### Expected Result:
No error should be encountered

### Actual Result:
There is an error mentioning TableData not found. And it points out to the TableData variable on line 62

### Environment:
Pycharm environment python 3.8 

### Additional Context:
Gets solved by adding an  import { TableData } from '@finos/perspective';

**Comment by sinistersnare** [comment]
Please provide a repo that reproduces this issue. I am not sure what this has to do with Perspective, so if you could share a larger working example that would be great! Thanks
