### ISSUE TITLE
Y area charts draws funny near the Y axis after the X axis starts scroling

### ISSUE THREAD

**Issue by tomjakubowski** [finos/perspective#2249]
### Steps to Reproduce:

1. Create a Y area chart of a time series
2. Add enough points to the time series that the X axis starts "scrolling"
3. Look on the left hand side

### Expected Result:

After the X axis starts scrolling, the graph should continue to cut off cleanly at the left hand edge

### Actual Result:

The graph tapers down towards the origin 

<img width="558" alt="Screenshot 2023-06-07 at 6 28 20 PM" src="https://github.com/finos/perspective/assets/667901/6bae57e2-e8df-4f11-a274-48f0b17430c3">

### Environment:
Chrome 114

**Comment by texodus** [comment]
This isn't a bug, it's a property of how your data model works.
