### ISSUE TITLE
 Blog link is not working

### ISSUE THREAD

**Issue by Meruem1** [finos/perspective#2260]
### Steps to Reproduce:
 Blog link is not working (https://www.prospective.co/blog)

### Expected Result:
Link should open with the blog and reviews.

### Actual Result:
When  Clicked the  blog it shows "This site can’t be reached".

### Environment:
Perspective

**Comment by timkpaine** [comment]
The www subdomain doesn't work it seems

**Comment by RawHit02** [comment]
it seems that the domain you are using is not responding due to web issues
