### ISSUE TITLE
sorting by expression doesn't work after removing data from table

### ISSUE THREAD

**Issue by cakir-enes** [finos/perspective#2292]
title basically explains it, using `2.3.1`., `datagrid` plugin. Table is a client side table using Client/Server replicated model. (Backend is python, fastapi) . It works fine if I don't delete any rows

**Comment by sristi-2002** [comment]
If the sorting by expression is not working correctly after removing data from the table, there could be a couple of reasons for this issue. Here are a few potential solutions:

Reapply the sorting expression: After removing data from the table, the sorting expression may need to be reapplied. Check if the sorting expression is still set correctly and if it needs to be refreshed or reapplied to reflect the updated data.

Reset the sorting state: Sometimes, removing data from the table can affect the sorting state. Try resetting the sorting state to its default state and then reapply the sorting expression. This can be done by clearing any existing sort settings or resetting the sorting options.

Refresh the table: After removing data, refresh the table to ensure that the changes are properly reflected. This can be done by triggering a re-render or re-rendering the component that renders the table. Make sure that the table component is updated to reflect the changes in the data.

Check for any errors or conflicts: Verify if there are any errors or conflicts in the code that could be impacting the sorting functionality. Review the code related to sorting and ensure that it is implemented correctly without any errors or conflicting logic.

**Comment by texodus** [comment]
> title basically explains it

@cakir-enes I believe you found a bug, but the title does _not_ basically explain it. We have an [bug report template](https://github.com/finos/perspective/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) which asks for requisite details such as reproduction steps - please use it so we don't have to reiterate the those requirements in a comment like this one. 

Tell us what you did (repro) and what didn't meet your expectations (expected & actual result).

**Comment by cakir-enes** [comment]
I realized if I wait long enough table looks how it supposed to look. When I play with sorting on the table expression column values seems to hang until they recomupted again.
