### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by TusharPaul01** [finos/perspective#2300]
Steps to Reproduce:
Hover over the "Theme" button, select a theme from the dropdown, and then click away (lose attention).
Try selecting a theme again.
Expected Outcome:

They should be changed.

Actual Result:
Carnage. When the dropdown is open, it appears that the container element loses its hover/focus state, leading the container to collapse and break the dropdown. This is almost probably a Firefox bug because it can only be activated by compressing the container when the dropdown is active.

**Comment by texodus** [comment]
Duplicate #2115
