### ISSUE TITLE
No Themes Button in Market Monitor & it Does Not Adapt Night Mode Properly in Safari Browser

### ISSUE THREAD

**Issue by themihirmathur** [finos/perspective#2308]
### Steps to Reproduce:
1. Launch Perspectives using Safari: https://perspective.finos.org/
2. Click on Night Mode

### Expected Result:
To see the Themes Button in Market Monitor & Background of the Market Monitor in (Black + Dark Gray) mode and + the other background in black (like in chrome).

### Actual Result:
Don't See the Themes Button in Market Monitor & In Dark Mode, The Other Background was Black as Expected, but the Background of the Market Monitor was white.

### Environment:
Safari Version 16.5.2 
Mac OS Ventura 13.4.1 (c)

### Additional Context:
See the attached pictures of the issue below-

In Safari-

<img width="1470" alt="Screenshot 2023-07-15 at 6 51 48 PM" src="https://github.com/finos/perspective/assets/92594107/297a1fc9-b521-4426-bf79-83c4e5cbe623">

In Chrome-
<img width="1470" alt="Screenshot 2023-07-15 at 6 51 26 PM" src="https://github.com/finos/perspective/assets/92594107/38823580-ce14-4360-b8af-3c9fa2247c2c">

**Comment by texodus** [comment]
This is fixed in 2.7.0
