### ISSUE TITLE
Bug scroll in movies example in Firefox

### ISSUE THREAD

**Issue by mhkeller** [finos/perspective#2357]
### Steps to Reproduce:
 1. Open this page in Firefox (running version 117 on macOS): https://perspective.finos.org/block/?example=movies
 2. Scroll the left pane
 

### Expected Result:

In Chrome, the scroll is vertical, as expected

### Actual Result:

The content scrolls horizontally instead of vertically.

### Environment:
Firefox 117, macOS

### Additional Context:

https://github.com/finos/perspective/assets/498744/86ee4895-e0ba-4ef8-8d0c-33b37d625129

**Comment by ArjunPK7** [comment]
Check the Console tab in the Developer Tools for any JavaScript errors or warnings related to the scrolling issue.

**Comment by msmolkin1** [comment]
The problem still exists in Firefox 122.0.1.

When you [open the perspective directly](https://perspective.finos.org/blocks/movies/index.html
) (e.g. by clicking "Open in New Tab"), same issue.

**Comment by sjpfenninger** [comment]
It might be related to what kind of DOM container the table view is inside? Examples where the table is next to a graph, like [movies](https://perspective.finos.org/block/?example=movies) and [citibike](https://perspective.finos.org/block/?example=citibike), do not work in Firefox 124 on macOS, but do work in the most recent Safari.

More annoyingly, I have this issue in Firefox _as well as_ in Safari, when displaying just a plain Datagrid [using perspective 2.8.0 inside Panel 1.4.0](https://panel.holoviz.org/reference/panes/Perspective.html), making perspective entirely unusable. The embedding of perspective inside of Panel seems to trigger the bug in more contexts.

**Comment by texodus** [comment]
Thanks for the report. I've consolidated this and other Firefox issues into #2693, closing.
