### ISSUE TITLE
perspective-nextjs: Unknown plugin race condition

### ISSUE THREAD

**Issue by makeitrein** [finos/perspective#2372]
### Steps to Reproduce:
 1. Load the table via `await ref.current!.load(table);`
 2. Immediately restore config with ```ref.current!.restore({
        plugin: "Treemap",
      });```
3. Continuously refresh the browser, the error occurs about half of the time for me. It seems to occur more consistently for me when visiting localhost:3000 in a new tab.

### Expected Result:
I see a Treemap visualization of the data.

### Actual Result:
I do not see a Treemap visualization of the data. I see the default Datagrid visualization of the data with an error in the console: 
<img width="816" alt="CleanShot 2023-09-28 at 14 31 45@2x" src="https://github.com/finos/perspective/assets/2068463/46306a7e-db93-4399-bca2-babbafddc34e">. The plugin dropdown does not show any other plugin besides Datagrid. 
<img width="449" alt="CleanShot 2023-09-28 at 14 32 15@2x" src="https://github.com/finos/perspective/assets/2068463/6baed73a-6bbf-4da0-b073-ec33f6ae822c">

DevTools suggests this this line of Javascript in perspective-viewer.js is the culprit: 
```{return await this.__load_wasm(),await this._instance[n].call(this._instance,...e)}});for(let n of["registerPlugin","getExprTKCommands"])Object.defineProperty(C,n,{value:async function(...e){let t=await Q;return t[n].call(t,...e)}});customElements.define("perspective-viewer",C);var wt={};export{$ as HTMLPerspectiveViewerPluginElement,ct as convert,wt as default};```

### Environment:
OSX + Chrome/Safari/Firefox

### Additional Context:
Github Reproduction Here: https://github.com/makeitrein/perspective-nextjs
Reproduced on versions 2.5.1 and 2.1.2 of Perspective
Reproduced on a full configuration object saved via `await ref.current!.save("json");`

**Comment by texodus** [comment]
Please file this with the repro you forked the example from, as I have no reason to believe this is an issue with Perspective, rather likely it is in how the module is loaded by this framework "nextjs"
