### ISSUE TITLE
Examples on site point to wrong version

### ISSUE THREAD

**Issue by droher** [finos/perspective#2378]
## Bug Report
The examples on the site point to version 2.5.2, when the latest released version is 2.5.1.

### Steps to Reproduce:
1. Navigate to any example on the site, e.g. https://perspective.finos.org/block/?example=editable

### Expected Result:
Working example

### Actual Result:
Perspective viewer is blank. In the console there are 404s on each js script:
```
Failed to load resource: the server responded with a status of 404 ()
```

### Environment:
MacOS, Latest versions of Brave and Safari

**Comment by timkpaine** [comment]
the release is forthcoming
