### ISSUE TITLE
exprtk: abs() returns '-' 

### ISSUE THREAD

**Issue by fundef1** [finos/perspective#2379]
## Bug Report
abs("coumn") doesn't return the absolute value
### Steps to Reproduce:
```
<!DOCTYPE html>
<html>
    <head>
        <title>abs test</title>
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no" />
        <meta charset="utf-8">
        
        <STYLE>
            perspective-viewer {position: absolute;top: 0;bottom: 0;left: 0;right: 0;}
        </STYLE>

		<script type="importmap">
            { "imports": {
                "@finos/perspective-viewer": "https://cdn.jsdelivr.net/npm/@finos/perspective-viewer/dist/cdn/perspective-viewer.js",
                "@finos/perspective-viewer-datagrid": "https://cdn.jsdelivr.net/npm/@finos/perspective-viewer-datagrid/dist/cdn/perspective-viewer-datagrid.js"
				} 
			}
        </script>
         <script type="module">
            import "@finos/perspective-viewer";
            import "@finos/perspective-viewer-datagrid";
            import perspective from "https://cdn.jsdelivr.net/npm/@finos/perspective/dist/cdn/perspective.js";

            window.addEventListener("DOMContentLoaded", async function () {
                const viewer = document.getElementById("viewer");
                var worker = perspective.worker();

                const schema = {number: "integer"};
                const data = [{number: 2},{number: 1},{number: 0},{number: -1},{number: -2},{number: -3}];
                const table = await worker.table(schema);
                const conf = {
                    "plugin": "Datagrid",
                    "settings": true,
                    "columns": ["number","absolute","workaround"],
                    "expressions": [
                        "// absolute\nabs(\"number\")",
                        "// workaround\ninteger(sqrt(pow(\"number\",2)))"
                    ]
                };

                viewer.load(table);
                viewer.restore(conf);
                table.update(data);
            });
        </script>
        <link rel="stylesheet" crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer/dist/css/pro-dark.css" />
    </head>
    <body>
        <perspective-viewer id="viewer" >
        </perspective-viewer>    
    </body>
</html>
```

### Expected Result:
see workaround column

### Actual Result:
![image](https://github.com/finos/perspective/assets/12233640/5b62757f-41a5-4d26-abb6-f64a5212764b)

### Environment:
latest from jsdelivr , chrome on windows

ps: "expression columns" docs/examples  specify `function("columnname") `,
while the exprtk function refereence always uses `abs(${1:x})`
it reads like a parameter substitution, but is never explained anywhere? what does that do?

**Comment by d-manas28** [comment]
There doesn't seem to be any implementation issues per say. Below is the abs() method implementation taken from scaler.cpp.

t_tscalar::abs() const {
    t_tscalar rval;
    rval.clear();
    rval.m_type = m_type;

    if (!is_valid())
        return rval;

    switch (m_type) {
        case DTYPE_INT64: {
            std::int64_t v = std::abs(to_double());
            rval.set(v);
        } break;
        case DTYPE_INT32: {
            std::int32_t v = std::abs(to_double());
            rval.set(v);
        } break;
        case DTYPE_INT16: {
            std::int16_t v = std::abs(to_double());
            rval.set(v);
        } break;
        case DTYPE_INT8: {
            std::int8_t v = std::abs(to_double());
            rval.set(v);
        } break;
        case DTYPE_UINT64:
        case DTYPE_UINT32:
        case DTYPE_UINT16:
        case DTYPE_UINT8: {
            return *this;
        } break;

        case DTYPE_FLOAT64: {
            rval.set(std::abs(m_data.m_float64));
        } break;
        case DTYPE_FLOAT32: {
            rval.set(std::abs(m_data.m_float32));
        } break;
        default: {
            // no-op
        }
    }
    return rval;
}

However being specific to your query, it seems that passing only the "number" parameter to abs doesn't seem to work as it directly goes to execute the default switch case and hence you see "-" as output. A simple workaround is to use **"number-0"** to make it identify as INT/UINT that converts into abs double type, You can then use interger typecasting to get absolute value of integer number. Referncing the code below

 window.addEventListener("DOMContentLoaded", async function () {
                const viewer = document.getElementById("viewer");
                var worker = perspective.worker();

                const schema = {number: "integer"};
                const data = [{number: 2},{number: 1},{number: 0},{number: -1},{number: -2},{number: -3}];
                const table = await worker.table(schema);
                const conf = {
                    "plugin": "Datagrid",
                    "settings": true,
                    "columns": ["number","absolute"],
                    "expressions": [
                        "// absolute\ninteger(abs(\"number\"-0))",
                    ]
                };
                
                
                
   Output:
   
<img width="290" alt="jpm_bug_fix" src="https://github.com/finos/perspective/assets/44508681/8dc47da2-e8ff-47fd-bc4d-3ff0a986c496">

**Comment by fundef1** [comment]
Great! thanks for investigating this.
