### ISSUE TITLE
Clicking on legend elements in scatterplots doesn't remove items

### ISSUE THREAD

**Issue by mhkeller** [finos/perspective#2382]
### Steps to Reproduce:
 1. Select a scatterplot view, for this we're using the Editable example on the website: https://perspective.finos.org/block/?example=editable
 2. Color by `Category`
 3. Click one of the category items in the legend

### Expected Result:
I expect it to filter the results of the scatterplot to exclude the categories that are now grayed-out in the legend.

### Actual Result:
Nothing changes

### Environment:
MacOS, tried in Firefox 118.01 and Chrome 117.0.5938.149

### Additional Context:

https://github.com/finos/perspective/assets/498744/b00c055f-1779-4cb2-96b6-2411bf93356c

**Comment by Pranav141** [comment]
Can someone please provide the repo for this issue I am not able to get it. I want to make my first open-source contribution and I think maybe I can work this issue out. Thank You.

**Comment by nithishchouti** [comment]
Use Chrome Browser [Version 119.0.6045.160]. It works perfectly fine in it. We are able to segregate and distinguish the various color features. The link provided works perfectly fine - https://perspective.finos.org/blocks/editable/index.html

**Comment by texodus** [comment]
#2391 #2394
