### ISSUE TITLE
Percentage formatting

### ISSUE THREAD

**Issue by fibinger** [finos/perspective#2386]
### Description of Problem:
When column shows percentage users prefer to see it as percentage (x * 100).
Currently we cannot tell Perspective that a particular column represents percentage.

### Potential Solutions:
1. Schema may be introduced with a new data type (apart from existing 'float' and 'integer) called 'percent'.
2. Other solution would be to add ability of specifying a custom (or built-in) value formatters on per-column basis.

**Comment by hengaini2055** [comment]
In aggregate or group by, how could you  get a new columnC with values as "sum(columnA) / sum(columnB)"?

**Comment by texodus** [comment]
Percent format (with or without Expression Columns) is available in `v2.9.0`, added in #2563
