### ISSUE TITLE
Re-drop python 3.7

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#2415]
Python 3.7 was deprecated 27 Jun 2020. We dropped in https://github.com/finos/perspective/issues/2073 / https://github.com/finos/perspective/pull/2065 and then restored in https://github.com/finos/perspective/pull/2223. We will need to re-drop in order to support JupyterLab 4 builder https://github.com/jupyterlab/jupyterlab/pull/13745

**Comment by tomjakubowski** [comment]
If we're supporting both jl3 and jl4 on modern Python versions, could we just say that on 3.7 we only support jl3? Somehow?

**Comment by timkpaine** [comment]
"somehow". perspective does not have a (direct) dependency on JupyterLab, so if you `pip install perspective-python` you won't be forced to upgrade JupyterLab to 4, and we can try to not explicitly break compatibility (no walrus operator).

**Comment by dhirschfeld** [comment]
> *Python 3.7 was deprecated 27 Jun 2020*

...and has been EOL now for going on 5 months. It's not receiving even security fixes anymore. Does anyone on py37 really need to be running the latest and greatest `perspective`? Most modern libraries in the pydata stack no longer support py37 so `perspective` would definitely be the exception there.

![image](https://github.com/finos/perspective/assets/881019/49ba301c-c347-4e08-a957-6ff991f66b62)

**Comment by texodus** [comment]
We support the Python versions our clients use. I can't discuss particulars beyond this but I'll point out that [`3.7` is installed more frequently than `3.11`](https://pypistats.org/packages/perspective-python) despite scheduled demolition.

@timkpaine How can we continue to support Jlab3. My understanding is that we'd need separate labextension builds?

**Comment by texodus** [comment]
Closing this as it's not an issue in itself - the issue is captured in #2307.

We may (or may not) soon drop Python 3.7, but if we do it will be to support JupyterLab.
