### ISSUE TITLE
Fixing mobile responsiveness

### ISSUE THREAD

**Issue by williamwebs** [finos/perspective#2425]
### Description of Problem:
viewing perspective on mobile screens isn't too great. There is need to improve the responsiveness on mobile screens. There is no padding on the sides and some contents are overflowing the screen width.

![jj](https://github.com/finos/perspective/assets/52858298/b8ec61fe-567a-4783-894b-6abdc60d764b)

### Potential Solutions:
I can help make perspective more responsive on mobile device.

**Comment by texodus** [comment]
Perspective' docs site is built on [docusaurus](https://docusaurus.io/), any issues with responsiveness need to be addressed there.
