### ISSUE TITLE
Docs: Broken link on website to Expression Columns API 

### ISSUE THREAD

**Issue by mhkeller** [finos/perspective#2460]
## Bug Report

The link to `obj/perspective-view-exprtk` on [this line](https://github.com/finos/perspective/blob/18e19e303903117a401e107d1af88af4585b9be9/docs/docs/expressions.md?plain=1#L123) in **expressions.md** results in a 404.

**Comment by texodus** [comment]
Thanks for the report, this is [fixed](https://perspective.finos.org/docs/obj/perspective-viewer-exprtk/).

Note all docs pages are always available from the sidebar on the left (in this case - "API" -> "ExprTK Function Reference".

**Comment by mhkeller** [comment]
Awesome thanks. One question on this doc page: I was playing around with `bucket()` and it seems that the column name needs to be in double quotes such as `bucket("my_col", 10)`. Is this documented somewhere and I missed it?

**Comment by texodus** [comment]
[Docs on referencing column values with _double-quotes_](https://perspective.finos.org/docs/expressions/#referencing-table-columns)

`bucket()` is just a function that takes two arguments - a value to bucket, and a bucket size. Using a _column value_ for the first argument just parameterizes this value per row.

For example, this is valid also and will be the same for every row:

```
bucket(3.14159, 2)
```

This example is identical to `bucket("Sales", 10)`, but made more explicit:

```
var x:= "Sales";
bucket(x, 10)
```
