### ISSUE TITLE
Restore Widget with Version: Doesn't Restore

### ISSUE THREAD

**Issue by ada-x64** [finos/perspective#2485]
## Bug Report
![Screenshot_20240102_214923](https://github.com/finos/perspective/assets/41482263/38028145-bdef-445b-9682-952aa2b0ecef)
![Screenshot_20240102_214958](https://github.com/finos/perspective/assets/41482263/0566dc91-0a2d-4359-8329-ba05c5731306)

### Steps to Reproduce:
 1. Create a widget with a table.
 2. Restore the widget with a version number.
 3. The restore method does nothing.

### Expected Result:
Symmetric save/restore functionality

### Actual Result:
Restore does not restore the saved widget

### Environment:
Perspective 2.7.1 on Manjaro Linux in Vivaldi Browser (Chromium)

### Additional Context:
Pretty sure this is a break in the python code where the viewer or widget attempts to ignore the version number. the version number is only relevant to the perspective-viewer, but we need to accept it for symmetry's sake

**Comment by texodus** [comment]
Fixed in #2465
