### ISSUE TITLE
JupyterLab: "Enable Scrolling for Outputs" does not work when perspective is installed

### ISSUE THREAD

**Issue by azjps** [finos/perspective#2494]
### Steps to Reproduce:
```bash
$ micromamba create -y -p /tmp/venv.perspective jupyterlab perspective -c conda-forge
+ jupyterlab 4.0.10
+ perspective 2.7.1
$ micromamba activate /tmp/venv.perspective
$ jupyter lab
```
In an empty notebook, run anything that generates reasonably long output like
```python
for i in range(500):
    print(i)
```
(note that `perspective` does not need to be imported) and then Right Click and select "Enable Scrolling for Outputs" in the context menu. No scroll bar appears.

### Expected Result:
Scrollbar should appear when using "Enable Scrolling for Outputs". [Here is someone else's video of what this looks like.](https://www.youtube.com/watch?v=U4usAUZCv_c)

### Actual Result:
No scroll bar appears when using "Enable Scrolling for Outputs" when `perspective` is installed in the environment.

### Environment:
I've observed that this bug happens on MacOS & Chrome, Safari; Ubuntu & Chrome, Firefox; and across various versions of `jupyterlab >= 3.5` and `perspective >= 2.0`, installed via any of pip / conda / mamba.

**Comment by texodus** [comment]
Thanks for the report, this is fixed in #2495 and will be in the `v2.7.2` release
