### ISSUE TITLE
Table View with PerspectiveWidget shows duplicated rows when table get updated

### ISSUE THREAD

**Issue by gangtao** [finos/perspective#2506]
### Steps to Reproduce:
 1. open the stack created by https://mybinder.org/ with github repo https://github.com/gangtao/perspective-table-demo
 2. run notebook mytable.ipynb
 3. the table view got updated with two rows for each update

https://github.com/finos/perspective/assets/3509037/0f6a267b-79f1-46cd-92f8-f65b5719d4e2

```python
from perspective import Table, PerspectiveWidget
import time
rows = [{"a": 1, "b": True}, {"a": 2, "b": False}]
table = Table(rows)
PerspectiveWidget(table)

for i in range(10):
    table.update({
        "a": [i],
        "b": [True]
    })
    time.sleep(1)


```

### Expected Result:

the table view should only show one new row each time when table get updated

### Actual Result:
the table view get updated with two rows every second

### Environment:
mybinder jupyterlab 3.6.6
perspective-python==2.7.1

**Comment by texodus** [comment]
I've told you three times now this is [not a Perspective bug](https://github.com/finos/perspective/discussions/2504#discussioncomment-8162328).
