### ISSUE TITLE
CSV update fails on schema-defined table but succeeds on creation

### ISSUE THREAD

**Issue by kryaksy** [finos/perspective#2524]
## Bug Report

When updating a table created with a schema using a CSV file, an error is thrown, but the same error is not thrown when creating the table with the same CSV.

### Steps to Reproduce:
```js
const csv = `field\n2147483648`;

const tableFromCsv = await worker.table(csv);
// No error

const tableFromSchema = await worker.table({ field: "integer" });
await tableFromSchema.update(csv);
// Update failed: Error: Abort(): Invalid: In CSV column #0: Row #2: CSV conversion error to int32: invalid value '2147483648'

```

### Expected Result:
Consistent behavior between updating a schema-defined table and creating a table with the same CSV.

### Actual Result:
While one of them succeeds, the other one throws error.

### Environment:
perspective@2.7.2

**Comment by timkpaine** [comment]
Your first schema isn't going to match your second schema, the number you picked exceeds int32

**Comment by kryaksy** [comment]
Schemas are the same:
```js
const csv = `field\n2147483648`;
const tableFromCsv = await worker.table(csv);
console.log(await tableFromCsv.schema());
// {field: 'integer'}
```
As you see, even the value exceeds int32, schema response is integer.

**Comment by timkpaine** [comment]
You're in JS and int is int32. CSV is not JavaScript, so it can use e.g. int64.

**Comment by timkpaine** [comment]
I don't see any issue here, csv or arrow or python will allow for large integers whereas JS does not. So constructing something from a csv or arrow or python vs from JS will have minor differences as a result of the language and format differences. 

ref: https://github.com/finos/perspective/issues/1346

**Comment by texodus** [comment]
Perspective currently only officially supports 32bit signed integer for `"integer"` type columns, because JavaScript only had native support for this type (at least, when Perspective was originally published). If you want numbers larger than that, you'll need to use `"float"` typed column (64bit float).

While I'd prefer this to be consistent behavior between platforms, and Perspective may soon support BigInt types as they have wide platform support today, it won't change the fact that `"integer"` type will still be 32bit. Ergo in your case, the fix is not to accept this value in JavaScript, but rather to reject it in Python.

**Comment by kryaksy** [comment]
@texodus Thanks for the explanation. Based on the what you said, it would be correct to expect this field to be recognized as a 'float' when I create a table with a csv containing a 64-bit value, right? 
```js
// Csv containing 64-bit value
const csv = `field\n2147483648`;

const tableFromCsv = await worker.table(csv);
console.log(await tableFromCsv.schema());
// Expected {field: 'float'}
// Received {field: 'integer'}
```
This is the issue from my perspective. Am I missing something?

**Comment by timkpaine** [comment]
No, you're mixing CSV and javascript. If you're ingesting as csv, the internal type will be int64. But this doesn't exist in javascript, so when you query FROM JAVASCRIPT it gets truncated to int32 (both types represented in schema as "integer"). 

If you predefine your schema as float and then ingest as csv, then from javascript the stuff will come out as float.
