### ISSUE TITLE
Unable to change sizing column on treemap

### ISSUE THREAD

**Issue by jacquelinegarrahan** [finos/perspective#2550]
### Steps to Reproduce:
1. I used this [table example](https://perspective.finos.org/docs/python/#table) in to render a `PerspectiveWidget` in jupyter.

<img width="1166" alt="Screenshot 2024-03-01 at 4 43 46 PM" src="https://github.com/finos/perspective/assets/25035114/67df2cfe-03fa-452b-a1f5-c71c6590d3e6">

### Expected Result:
I would expect the size to be configurable to quantitative columns.

### Actual Result:
The size is fixed as the table index. 

### Environment:
```
python ==3.9.9
perspective-python==2.8.1
jupyter-widgets=3.0.10
jupyterlab==4.0.11
```

**Comment by texodus** [comment]
The `size` field is not fixed, it just can't be de-selected. Select a column from the column list as in the screenshot
![image](https://github.com/finos/perspective/assets/60666/18fdd72e-e425-4858-a439-e2a2dbc83fcf)
