### ISSUE TITLE
"Treemap" showing blank screen on Firefox v123, Windows 11 on Surface Pro

### ISSUE THREAD

**Issue by dejanmccreery** [finos/perspective#2557]
## Bug Report
Tree map blank on Firefox v123, Surface Pro 9 running Windows 11.

### Steps to Reproduce:
 1. Open Firefox
 2. Go to https://perspective.finos.org/
 3. Select "TREEMAP" option on sidebar below chart

### Expected Result:
Some tree chart/volume map

### Actual Result:
Blank object

![image](https://github.com/finos/perspective/assets/108457094/4de67aa0-5568-49b2-9b8e-9645ef04d0a5)

### Environment:
Firefox v123, Windows 11, Surface Pro 9

**Comment by texodus** [comment]
Duplicate #1983
