### ISSUE TITLE
Conditional cell formatting

### ISSUE THREAD

**Issue by lmeyerov** [finos/perspective#2559]
## Feature Request

We would like to be able to define conditional formatting on cells within a column. For example, when a column has certain string values, change the background, foreground colors, and font family/size/weight/decoration. Same but different for value ranges, like being below some threshold.

Tools like Google Sheets call this conditional formatting afaict.

### Description of Problem:

We are trying to make certain categorical and continuous columns easier to read , such as risk scores and error values

### Potential Solutions:

We can provide a sequence of formulas for whether a cell in a column being conditionally formatted should trigger, and for each formula, a corresponding css class name or style object. The first format registered to match a cell is the one to that gets picked.

Later, a UI-editable version.

**Comment by timkpaine** [comment]
https://github.com/finos/perspective/discussions/1510#discussioncomment-1146608
