### ISSUE TITLE
python user guide broken

### ISSUE THREAD

**Issue by ekalosak** [finos/perspective#2560]
## Bug Report

See https://perspective.finos.org/docs/python/, specifically the Torando websocket example `index.html`:
```
<perspective-viewer id="viewer" editable></perspective-viewer>

<script>
    window.addEventListener("DOMContentLoaded", async function () {
        // Create a client that expects a Perspective server
        // to accept connections at the specified URL.
        const websocket = perspective.websocket(
            "ws://localhost:8888/websocket"
        );

        // Get a handle to the Table on the server
        const server_table = websocket.open_table("data_source_one");

        // Create a new view
        const server_view = await table.view();

        // Create a Table on the client using `perspective.worker()`
        const worker = perspective.worker();
        const client_table = await worker.table(view);

        // Load the client table in the `<perspective-viewer>`.
        document.getElementById("viewer").load(client_table);
    });
</script>
```

Of course, `table` is not defined.
Worse, `server_table.view()` is not a function.

## Solution
The [Tornado example](https://github.com/finos/perspective/blob/master/examples/python-tornado/index.html) works. Hard problem to keep the web guide snippets in sync with fast-moving codebase, for sure. But here's the details:

### Specifics
1. add worker in the guide
2. await the open_table
3. server_view from server_table, not table
4. worker.table isn't a future

**Comment by Aqina** [comment]
Hi, are these the amendments that you had asked for in the index.html example-
![image](https://github.com/finos/perspective/assets/68770282/75b60beb-c735-40a7-adef-591524b2b298)

**Comment by texodus** [comment]
Appreciate the effort but we do not need issues for docs. They attract low-effort bikeshedding and are rarely worth the effort -e.g., the details of the report are abotu 10x the writing necessary to just submit the fix, and they're not correct (`work.table` _is_ a `Promise`, `open_table` is synchronous on <3, etc).

@Aqina, stop spamming this project.
