### ISSUE TITLE
docs rendered oddly

### ISSUE THREAD

**Issue by ekalosak** [finos/perspective#2567]
https://perspective.finos.org/docs/obj/perspective/#module_perspective..table+view

<img width="966" alt="Screen Shot 2024-03-12 at 7 55 40 PM" src="https://github.com/finos/perspective/assets/6068321/bf08f265-da7a-4427-a566-406ff52490d3">

Please see logs split mid-sentence between code highlighting and paragraph body in screenshot attached.

**Comment by Aqina** [comment]
Hi I would like to be assigned to this task but I had a doubt about how I should send the corrected output here, like in a word doc or as I have sent here 
![Screenshot 2024-06-25 235414](https://github.com/finos/perspective/assets/68770282/2d761948-e52c-456f-ac6e-246857eb9a73)

Do let me know where I went wrong.

**Comment by texodus** [comment]
These docs are what they are, we can clean them up as new features are developed, but this is not an addressable bug and is attracting ChatGPT coders.

For the record though @Aqina - no, a screenshot of an MS Word document is _not_ a suitable way to [contribute changes](https://github.com/finos/perspective/blob/master/CONTRIBUTING.md) to Perspective or any GitHub project.
