### ISSUE TITLE
perspective javascript API view.to_json() is not deterministic 😳

### ISSUE THREAD

**Issue by jordanskole** [finos/perspective#2601]
### Steps to Reproduce:
 1. create a table with data 
 2. render the table as a view, passing a config that will return a view with a schema that is different from the underlying table schema (expressions to create new table)
 3. create an async function like this...

```typescript
const SHARED_CONFIG = {...config}

const myAsyncOne = async () => {
  const view = await table.view(SHARED_CONFIG)
  const rows = await view.to_json();
  await view.delete()
  return rows;
}

const myAsyncTwo = async () => {
  const view = await table.view(SHARED_CONFIG)
  const rows = await view.to_json();
  const schema = await view.schema();
  await view.delete()
  return rows;
}

const isDeterministic = (one, two) => {
  return one === two;
} 

(async () => {
  
  const rowsOne = await myAsyncOne();
  const rowsTwo = await myAsyncTwo();
  const result = isDeterministic(); // expect true 
  
})()
```

### Expected Result:
I would expect that the rows after being serialized to json would match, at least the properties should match, but that is not the case. 

if you wait for the schema to come back each row will have a shape like: 

```typescript
{ data: { ...row } } 
```

If you don't call the schema function you will end up with the "Raw" rows 

```
{...row}
```
They are otherwise the same! 

### Actual Result:
brb! 

...what actually happened, including full exceptions (please include the entire stack trace, including "caused by" entries), log entries, screen shots etc. where appropriate...

### Environment:
I am currently on `"@finos/perspective": "^2.8.0",`

### Additional Context:
...add any other context about the problem here. If applicable, add screenshots to help explain...

**Comment by jordanskole** [comment]
I know, I am not meaning strict equals (why I said "match"), i mean that somehow the row object transforms from `schema` to `{data: schema}`. 

Another way to say the same thing would be that the `Object.keys(row)` are not even deterministic. 


concrete examples: 

```
obj1 = {
  firstName: "jordan", 
  lastName: "skole"
}

obj2 = {
  data: {
    firstName: "jordan", 
    lastName: "skole"
   }
 }
 ```
 
 i know that even if the two had the same key/value pairs they would not strict equal each other, that's not what this is about

**Comment by texodus** [comment]
@jordanskole We can only help you with a _full reproduction_ that I can replicate, a description of the output you observed is insufficient.

`to_json()` has [hundreds of tests](https://github.com/finos/perspective/blob/master/packages/perspective/test/js/to_format.spec.js), if oyu need a reference for what a repro looks like.

**Comment by jordanskole** [comment]
Understood.
