### ISSUE TITLE
Integration of DuckDB-Wasm with FINOS Perspective

### ISSUE THREAD

**Issue by simisoz** [finos/perspective#2617]
### Description of Problem:
When dealing with large datasets in web applications, I want to perform complex analytical queries and visualize the results seamlessly, so I can have an efficient, in-browser data analysis experience without relying on server-side processing.

Currently, there is a gap between performing advanced SQL queries in-browser and visualizing the results interactively. DuckDB-Wasm provides efficient, high-performance SQL query capabilities within the browser, while FINOS Perspective excels at providing interactive data visualization and analysis. However, these two tools do not integrate natively, leading to a fragmented experience and additional overhead for developers to connect them manually.

### Potential Solutions:
To address this problem, I propose integrating DuckDB-Wasm with FINOS Perspective. This integration would allow users to run SQL queries on large datasets directly in the browser using DuckDB-Wasm and seamlessly pass the results to FINOS Perspective for interactive visualization and analysis. 

**Key Features of the Integration:**
1. **Native Support for DuckDB-Wasm in Perspective:**
   - Enable Perspective to accept DuckDB-Wasm query results as a data source.
   - Provide utilities to execute DuckDB-Wasm queries and format the results for easy ingestion by Perspective.

2. **Unified API:**
   - Develop a unified API that abstracts the complexity of using both tools, allowing developers to perform SQL queries and visualize the results with minimal setup.

3. **Real-time Updates:**
   - Implement mechanisms to support real-time data updates from DuckDB-Wasm queries to Perspective visualizations, enabling dynamic data analysis.

4. **Cross-Platform Compatibility:**
   - Ensure the integration works seamlessly across different browsers and platforms, maintaining performance and reliability.

**Considered Drawbacks:**
- **Increased Bundle Size:**
  Integrating these two tools may increase the overall bundle size of web applications. Optimizations and selective loading of components could mitigate this issue.

- **Complexity in Maintenance:**
  Maintaining the integration might require coordination between the DuckDB and Perspective development teams, potentially increasing complexity.

### Alternatives Considered:
- **Manual Integration:**
  Developers can manually set up and connect DuckDB-Wasm with Perspective in their applications. However, this approach lacks the efficiency and ease-of-use of a native integration and could lead to inconsistencies and increased development time.

By integrating DuckDB-Wasm with FINOS Perspective, we can create a powerful, cohesive toolset for in-browser data analysis and visualization, enhancing the user experience and reducing the development overhead.

**Comment by timkpaine** [comment]
dupe https://github.com/finos/perspective/discussions/1664
