### ISSUE TITLE
Perspective Workspace : Context Menu does *not* overlay content

### ISSUE THREAD

**Issue by saadmunir** [finos/perspective#2620]
### Steps to Reproduce:
 1. Go to: https://prospectiveco.github.io/prospective-gh-pages-demo/?csvs=PRICE_TREE_FILE_1659660015_exchangename.csv&layout=lseg_avg_price.json 
 2. Right Click anywhere

### Expected Result:
The context menu should appear where the mouse is clicked

### Actual Result:
The context menu appears at the bottom of the page and is very difficult to use.

On Edge:
![image](https://github.com/finos/perspective/assets/971816/e21a06b4-b324-4ecb-adaf-6703cb87c327)

On Chrome:
![image](https://github.com/finos/perspective/assets/971816/430c2c9a-1259-434c-b401-387beed826de)

### Environment:
Windows 11
Chrome: Version 124.0.6367.203 (Official Build) (64-bit)
Edge: Version 124.0.2478.97 (Official build) (64-bit)
"@finos/perspective": "^2.10.0",
"@finos/perspective-viewer": "^2.10.0",
"@finos/perspective-viewer-d3fc": "^2.10.0",
"@finos/perspective-viewer-datagrid": "^2.10.0",
"@finos/perspective-workspace": "^2.10.0",

### Additional Context:
Have tried this with multiple projects as well as personal but see the same behaviour.

**Comment by texodus** [comment]
This is the repository and support issues list for _Perspective itself_, not random sites that use Perspective. File this with the implementing project.

> Have tried this with multiple projects as well as personal but see the same behaviour.

Then you [didn't click past the first workspace example on the docs page](https://perspective.finos.org/blocks/nypd/index.html).
