### ISSUE TITLE
Python 3.12 wheels

### ISSUE THREAD

**Issue by 0x26res** [finos/perspective#2632]
### Description of Problem:

I can't install python-perspective on with python 3.12 (there's no wheel so I have to build it from source).

### Potential Solutions:

Upload wheels for python 3.12. I believe some work got done to get partial python 3.12 support, but it's not fully done yet. See https://github.com/finos/perspective/pull/2458

**Comment by texodus** [comment]
#2625 migrates `perspective-python` to the [Python Stable ABI](https://docs.python.org/3/c-api/stable.html#stable-abi) which will support 3.12 and all future 3.x Python versions.

**Comment by Smrithishera** [comment]
This issue of installing python-perspective on Python 3.12 can be addressed by uploading pre-built wheels specifically designed for Python 3.12 to the Python Package Index (PyPI). 
(You can use https://pypi.org/project/wheel/ for reference) providing these wheels, users will benefit from a smoother installation process and improved compatibility with the latest Python version.

Advantages:
Simplified Installation: Users will no longer need to build from source, streamlining the installation process and reducing potential errors.
Enhanced Compatibility: Pre-built wheels ensure compatibility with Python 3.12, enabling users to leverage the latest features and improvements.

Implementation Details:
To upload Python 3.12 wheels to PyPI, the maintainers can follow these steps:

Build wheels for python-perspective specifically targeting Python 3.12.
Upload the generated wheels to PyPI using the twine package or another suitable tool.
Update the package metadata on PyPI to reflect the availability of Python 3.12 wheels.

**Comment by anoopg512** [comment]
If sticking with Python 3.12 is mandatory, using Docker or Conda can provide a more flexible environment to handle such dependencies.

**Comment by 0xg0nz0** [comment]
As part of this enhancement it would be very helpful to include aarch64 Linux as well as MacOS ARM64 wheels; I think I am not alone running Linux on MacOS X via Docker.

Note that I was able to build from source for Python 3.12, Ubuntu 24.04 on aarch64 by installing `libboost-all-dev` so there is a workaround for now.

**Comment by Ubaidullah2023** [comment]
yes
**Steps to Include aarch64 Linux and MacOS ARM64 Wheels:**

**1. Set Up Cross-Compilation Environments:**

Use cross-compilation tools to build the wheels for different architectures without requiring physical hardware for each architecture.

**2. Build aarch64 Linux Wheels:**

Docker Setup: Utilize Docker to create a consistent and isolated build environment. Use multi-stage builds to ensure a clean build process.

- **Build Command:**
docker build -t myproject-wheel.
docker run --rm -v $(pwd)/dist:/dist myproject-wheel

**3. Build MacOS ARM64 Wheels:**
Using GitHub Actions: Set up GitHub Actions to build MacOS ARM64 wheels. GitHub Actions provides MacOS runners that can be used for building ARM64 wheels.
**GitHub Actions Workflow Example:**

**4. Publish the Wheels:**

- Once the wheels are built, they can be uploaded to PyPI using twine.
- Upload Command:
twine upload dist/*.whl
