### ISSUE TITLE
Support Split Over

### ISSUE THREAD

**Issue by brettsaunders21** [finos/perspective#2638]
### Description of Problem:

Currently it isn't possible to render a table like this
<img width="650" alt="image" src="https://github.com/finos/perspective/assets/32368716/deccda2c-909a-474f-b704-6885352aa979">

### Potential Solutions:

If the inital data was:
<img width="555" alt="image" src="https://github.com/finos/perspective/assets/32368716/c3dccd02-3f78-4b0e-aea2-71b7fe02e516">

You could add a split over property to support this. For example:

```json
{
"by": [
            "date"
          ],
          "over": [
            "rev",
            "pro"
          ],
}
```

**Comment by timkpaine** [comment]
We support `split_by`, in your example it would be `split_by: ['date']`. This will split the dataset out, i don't think partially splitting the dataset into only certain columns is planned, but I'm almost certain one could do this with expressions
