### ISSUE TITLE
The "not in" filter function lacks an autocomplete list

### ISSUE THREAD

**Issue by brianblakely** [finos/perspective#2641]
### Steps to Reproduce:
 1. Go to Superstore: https://perspective.finos.org/blocks/superstore/index.html
 2. Switch left-hand pane to `untitled` viewer
 3. Open config panel for the viewer
 4. Add `State` to `Where` field
 5. Change filter function to `not in`
 6. Begin typing `California` in the filter value field

### Expected Result:
Autocomplete list should appear, as it does for the `in` filter function.

### Actual Result:
No autocomplete is visible right now.

### Environment:
Perspective v2.10.0

**Comment by texodus** [comment]
This was already fixed in #2615
