### ISSUE TITLE
Cannot install dependencies/build on redhat or any non-ubuntu linux, and install requires root access

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#2675]
```raw
│ > @2.10.1 postinstall:playwright /perspective
│ > npx playwright install --with-deps
│ BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
│ Installing dependencies...
│ Switching to root user to install dependencies...
│ Sorry, user <user> is not allowed to execute '/usr/bin/sh -c apt-get update&& apt-get install -y --no-install-recommends fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libegl1 libgbm1 libglib2.0-0 libgtk-3-0 libnsp…
│ Failed to install browsers
│ Error: Installation process exited with code: 1
```

**Comment by texodus** [comment]
This works as intended, the repo dev environment requires _many_ steps that require elevated privileges. You _do not_ need elevated privileges to install the npm package, wheels, python sdist or crates.

For Playwright specifically, you can install the repo dev dependencies with `pnpm install --ignore-scripts` and then [follow the instructions here](https://github.com/microsoft/playwright/issues/12227) if you are absolutely determined to run the integration tests on an unprivileged system.
