### ISSUE TITLE
X/Y Scatter - Make gridlines at 0 thicker

### ISSUE THREAD

**Issue by fibinger** [finos/perspective#2696]
### Description of Problem:
When displaying X/Y Scatter I would like to gridlines at 0 to stand out.

![image](https://github.com/user-attachments/assets/1a0bd16a-7e44-4748-abf9-a5f416848e2e)

### Potential Solutions:

I would assume this feature could be enabled by default.

**Comment by texodus** [comment]
Fixed in #2698
