### ISSUE TITLE
Multiple aggregates on same column

### ISSUE THREAD

**Issue by akansal1** [finos/perspective#272]
I am trying to have more than one aggregate on same column, is it possible? I am unable find it in documentation.

My case is, if I am aggregating of Profit, I am want Minimum and Avg of the same data key ( For example a timeseries stock data, with price per time interval can generate OHLC data, based on grouping)

**Comment by akansal1** [comment]
I am looking for something like:

```javascript
aggregate: [{op: 'sum',column: ["age","salary"]}]
```
OR
```javascript
aggregate: [ op: ["mean","median"],column: "age"}]
```

**Comment by nmichaud** [comment]
This will work:
aggregate: [ {name: "sum(age)", op: "sum", column: "age"}, {name: "avg(age)", op: "mean", column: "age"}]

Because of a current bug, aggregates on the same column need to be given different names.

**Comment by nmichaud** [comment]
Ah @texodus is correct, it wasn't clear from your question whether you are trying with just the perspective engine or using the perspective-viewer attributes

**Comment by LucasLeandro1204** [comment]
this is not working anymore, anyone has a clue on how to do it??

**Comment by LucasLeandro1204** [comment]
for now I'm loop through my dataset, adding a new property with same value as my target column and aggregating it, something like:

```js
const data = [
    {
        foo: 10,
    },
    {
        foo: 30,
    },
];

const mapped = data.map((row) => ({
    ...row,
    'sum(foo)': row.foo,
    'count(foo)': row.foo,
}))

// ....

const view = await table.view({
    columns: [
        'foo', 'count(foo)', 'sum(foo)',
    ],

    aggregate: {
        'sum(foo)': 'sum',
        'count(foo)': 'count',
    },
});
```

**Comment by LucasLeandro1204** [comment]
@texodus any ideas?

**Comment by sc1f** [comment]
The API around this has changed significantly in the 2 years since this issue. Since `perspective` and the API is optimized for the `perspective-viewer` use case, there is no way at the moment to apply multiple aggregates to the same column.

**Comment by nmichaud** [comment]
Is there still no way to do multiple aggregates on the same column?

**Comment by sc1f** [comment]
It got removed around 0.3, I think.

**Comment by texodus** [comment]
`<perspective-viewer>` now supports multiple aggregates on the same column via ExprTK `expressions` API:

```javascript
await viewer.restore({
    columns: ["sum(Sales)", "avg(Sales)"],
    expressions: ['//sum(Sales)\n"Sales"', '//avg(Sales)\n"Sales"'],
    aggregates: {"sum(Sales)": "sum", "avg(Sales)": "avg"},
    row_pivots: ["State"],
});
```

... and via the UI

![multiple_aggregates](https://user-images.githubusercontent.com/60666/127268738-50a4630a-de21-495c-a38c-f4db60472414.gif)
