### ISSUE TITLE
Remove required dependency on ipywidgets, defer import of ipywidgets/PerspectiveWidget

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#2728]
Ideally we shouldn't really need a top level dependency on `ipywidgets`:

https://github.com/finos/perspective/blob/768ca4068c79a2c2243aa24fd3a073f09c6dc97d/rust/perspective-python/pyproject.toml#L36

Perhaps we should move the import out of the top level `__init__.py`, forcing users to use `perspective.widget.PerspectiveWidget`, but saving on import time and also potentially a dependency.

**Comment by tomjakubowski** [comment]
I did some work towards this when adding pytest-pyodide tests for our emscripten wheel. My approach adds try/except around the top-level re-exports of the widget and viewer modules

https://github.com/finos/perspective/pull/2739/commits/d1100bddf5aee41c5bba0b33d965dbb79624b72d

**Comment by timkpaine** [comment]
This allows for it to be missing but still incurs an import cost if it is present but unused. That may not be worth resolving if these are very light imports

**Comment by texodus** [comment]
Fixed in #2754, released in v3.1.0
