### ISSUE TITLE
Re-add method of get_row_expanded in View

### ISSUE THREAD

**Issue by yuj2i0** [finos/perspective#2745]
Following the upgrade of Perspective 3, the method has been removed from the View class in Javascript

Please can this be added back in, as it helps for building out other components that may not use perspective-viewer

https://github.com/finos/perspective/blob/4e0350790b5b330ac368db6a7b64a5a267ceb243/cpp/perspective/src/cpp/view.cpp#L1277

**Comment by texodus** [comment]
@yuj2i0 Please use the feature template and re-open.

I am down to add this back but some context on what we're adding it for will help - e.g. do you actually care about individual row expansion state, or are you iterating over all rows to serialize the entire state? Are you mapping from a physical dataset coordinate (row id as in the old method), or did you first look this up from the column `index`?
