### ISSUE TITLE
Not able to find `PerspectiveWidget, Table, Aggregate, Sort, Plugin`

### ISSUE THREAD

**Issue by adambouras** [finos/perspective#2769]
### Steps to Reproduce:
 1. created a poetry project with following specs:
```
[tool.poetry.dependencies]
python = "^3.12"
perspective = "^1.0.3"
perspective-python = "^3.1.0"
pandas = "^2.2.3"
jupyterlab = "^4.2.5"
ipykernel = "^6.29.5"
bokeh = "^3.5.2"
```

### Expected Result:
```from perspective import PerspectiveWidget, Table``` should work properly in jupyter lab

### Actual Result:
see screenshot

### Environment:
```python3.12`

### Additional Context:
![image](https://github.com/user-attachments/assets/7ae3bb33-9db4-47f6-8a00-59671c72c68a)

Please advise!

Thank you

**Comment by timkpaine** [comment]
The widget is moved to `perspective.widget` and the other types have been removed.
