### ISSUE TITLE
HTML Export - Print to PDF

### ISSUE THREAD

**Issue by bradleygore** [finos/perspective#2772]
### Description of Problem:
When viewing an HTML Exported report, I'd like to be able to print the page to PDF and show the full set of rows.

By default, the `perspective-viewer-datagrid` virtualizes the rows and scrolling.

### Potential Solutions:

I dug into some of the custom components at play and found a solution that I think will work. However, it's quite hacky 😅 and it uses some things I don't find documentation for. I'd like to know if there's a better way I'm just blatantly overlooking, or if this approach seems reasonable.

```js
// can paste all this in dev tools console on an HTML export of https://perspective.finos.org/block/?example=editable in DataGrid format
// recommend first reducing rows to only a couple k for performance of rendering so much

async function makePrintable() {
  // Wait for the `regular-table` custom element to be defined so we can query it 
  // and interact with the instance.
  // Awaiting this one as once this one is registered the other custom ones would be as well.
  await customElements.whenDefined('regular-table');
	
  const pvGrid = document.querySelector('perspective-viewer-datagrid')
  const regTable = pvGrid.shadowRoot.querySelector('regular-table')

  // HACK: I don't really find this documented anywhere, but stumbled across:
  // https://github.com/finos/perspective/blob/28a3101b58773374458fef59de08d179407fa177/packages/perspective-viewer-datagrid/src/js/model/create.js#L163-L167
  regTable._virtual_mode = 'none'; // remove virtualization of rows
  await regTable.draw(); // redraw now that virtual mode disabled - all rows now in DOM
	
  regTable.style = 'overflow:visible;' // show everything, which hides their custom scroll bar

  // virtualPanel seems to be a panel whose job it is to calculate the actual height needed if
  // all rows rendered, so that the custom scrolling positions can be calculated against the whole	
  const virtualPanel = regTable.shadowRoot.querySelector('.rt-virtual-panel');
  // here's how big containers actually need to be for all rows 
  // to show up when printing page to PDF
  const realHeight = virtualPanel.style.height;

  // tableClipper seems to be a container that clips the inner table to the specific bounds
  // need to make its overflow visible and make it grow the needed height	
  const tableClipper = regTable.shadowRoot.querySelector('.rt-scroll-table-clip');
  tableClipper.style = `height:${realHeight};position:relative;overflow:visible;`;

  // top-level viewer now also needs to grow to the needed height	
  const pViewer = document.querySelector('perspective-viewer');
  pViewer.style.height = realHeight;
}

await makePrintable()
```

**Comment by texodus** [comment]
I'm not sure what you think this code does, but it doesn't come close to either rendering a PDF or interacting with Perspective'e export feature.

**Comment by oleksify** [comment]
I recently added this functionality into our product. It's not very difficult, but requires a bit of code to be written and could be specific to your use case. I can't publish the code, but it's pretty simple in general:

- get current view data as with `view.to_columns()`

**Comment by bradleygore** [comment]
@texodus that was an incredibly dismissive comment. I did not claim that this code either renders a PDF or interacts with the export feature.

What it does allow me to do is specifically what it states - print the HTML page to PDF. There's this nifty feature in the browser where I can hit `cmd+p` and it brings up the baked-in Print dialog. From there, I can choose to print to PDF. In case this is new functionality to you, here is a screenshot of what this looks like when I press `cmd+p` (these are keyboard keys, I'm on a Mac) on this very page:

<img width="1099" alt="Screenshot 2024-09-27 at 8 41 24 AM" src="https://github.com/user-attachments/assets/3b8b9763-9b3f-4577-9718-15a3a27968c9">

**Comment by texodus** [comment]
I am getting _extremely_ tired of this.

This is not Facebook. It _is_ a log of the work we intend to do as a project. I don't care if you think it's _rude_ that we won't work on your issue, or you don't like me personally - keep it off of GitHub.
