### ISSUE TITLE
[v3 + windows 10 > regular crashes on demos] "invalid string value: data is not UTF-8 encoded",

### ISSUE THREAD

**Issue by dotgreg** [finos/perspective#2789]
## Bug Report
Thanks first for that amazing tool, I am using it every day and loving it so far! Such a great work you did.

On the new 3.0 version, it seems perspective is crashing now quite often.
I am using on other projects and I saw that behaviors several times with the new version.
I managed to reproduce it on one of the demo examples

### Steps to Reproduce:
 1. go to https://perspective.finos.org/block/?example=movies
 2. use the global filter panel on the right, filter 4-5 times the graph by modifying the filter

### Expected Result:
It crashes with the following log:
<html>
<body>
<div tabindex="-1" class="console-message-wrapper console-from-api console-error-level console-selected" role="log" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: column; margin: 4px; border-radius: 5px; --console-color-black: #000; --console-color-red: #a00; --console-color-green: #0a0; --console-color-yellow: #a50; --console-color-blue: #00a; --console-color-magenta: #a0a; --console-color-cyan: #0aa; --console-color-gray: #aaa; --console-color-darkgray: #555; --console-color-lightred: #f55; --console-color-lightgreen: #5f5; --console-color-lightyellow: #ff5; --console-color-lightblue: #55f; --console-color-ightmagenta: #f5f; --console-color-lightcyan: #5ff; --console-color-white: #fff; background-color: var(--sys-color-surface-error); --message-corner-rounder-background: var(--sys-color-surface-error); color: rgb(31, 31, 31); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-row-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start; margin-top: -1px;"><div class="console-message-stack-trace-wrapper" aria-label="e08e6245-f0ec-4996-b2bc-1eddb31c2485:1 WARNING: All log messages before absl::InitializeLog() is called are written to STDERR Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="blob:https://perspective.finos.org/e08e6245-f0ec-4996-b2bc-1eddb31c2485:1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">e08e6245-f0ec-4996-b2bc-1eddb31c2485:1</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">WARNING: All log messages before absl::InitializeLog() is called are written to STDERR</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace stack-preview-container" style="display: inline-block; width: 2483.33px; --monospace-font-size: 12px; --monospace-font-family: consolas,lucida console,courier new,monospace; --source-code-font-size: 12px; --source-code-font-family: consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | fd_write | @ | e08e6245-f0ec-4996-b2bc-1eddb31c2485:1
-- | -- | -- | --

</span></div></div></div></div></div></div><div tabindex="-1" class="console-message-wrapper console-error-level" role="log" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: column; margin: 4px; border-radius: 5px; --console-color-black: #000; --console-color-red: #a00; --console-color-green: #0a0; --console-color-yellow: #a50; --console-color-blue: #00a; --console-color-magenta: #a0a; --console-color-cyan: #0aa; --console-color-gray: #aaa; --console-color-darkgray: #555; --console-color-lightred: #f55; --console-color-lightgreen: #5f5; --console-color-lightyellow: #ff5; --console-color-lightblue: #55f; --console-color-ightmagenta: #f5f; --console-color-lightcyan: #5ff; --console-color-white: #fff; background-color: var(--sys-color-surface-error); --message-corner-rounder-background: var(--sys-color-surface-error); color: rgb(31, 31, 31); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-row-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><devtools-icon role="presentation" name="cross-circle-filled" class="message-level-icon" aria-label="Error" style="flex: 1 1 auto; display: inline-block; width: 14px; height: 14px; color: var(--icon-error); vertical-align: sub; position: absolute; box-sizing: border-box; min-width: 0px; min-height: 0px; left: -17px; top: 2px; user-select: none;"><span style="display: block; width: 14px; height: 14px; background-color: currentcolor; mask: var(--icon-url) center /contain no-repeat; --icon-url: var(--image-file-cross-circle-filled);"></span></devtools-icon><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; flex: 1 1 auto; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link invalid-link" tabindex="-1" title="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer@3.0.0/dist/pkg/perspective-viewer.js:1864" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--text-disabled); text-decoration: none; outline-offset: 2px;">perspective-viewer.js:1864</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: Undecipherable server message DecodeError { description: "invalid string value: data is not UTF-8 encoded", stack: [("Scalar", "scalar"), ("Filter", "value"), ("ViewConfig", "filter"), ("ViewGetConfigResp", "config"), ("Response", "client_resp")] }
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at J.t.wbg.__wbindgen_error_new (<span class="devtools-link" role="link" tabindex="-1" title="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer@3.0.0/dist/pkg/perspective-viewer.js:1864:21" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">perspective-viewer.js:1864:21</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="wasm://wasm/0094fcea:0x12d955" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">0094fcea:0x12d955</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="wasm://wasm/0094fcea:0x15eb99" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">0094fcea:0x15eb99</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="wasm://wasm/0094fcea:0x4f262" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">0094fcea:0x4f262</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="wasm://wasm/0094fcea:0xb4aee" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">0094fcea:0xb4aee</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="wasm://wasm/0094fcea:0x184f67" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">0094fcea:0x184f67</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at we (<span class="devtools-link" role="link" tabindex="-1" title="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer@3.0.0/dist/pkg/perspective-viewer.js:301:10" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">perspective-viewer.js:301:10</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at c (<span class="devtools-link" role="link" tabindex="-1" title="https://cdn.jsdelivr.net/npm/@finos/perspective-viewer@3.0.0/dist/pkg/perspective-viewer.js:224:20" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">perspective-viewer.js:224:20</span>)</span></span></span></span></span></div></div></div>
</body>
</html>

### Actual Result:
It should not crash :)

### Environment:
windows 10.0.19045

### Additional Context:
 
on windows 10 firefox
![image](https://github.com/user-attachments/assets/71d52a62-4f3e-4de8-98c8-5a13430d303d)

on windows 10 chrome and brave
![image](https://github.com/user-attachments/assets/08a66cc6-4f51-4b7f-bfa3-f0330460db21)

**Comment by texodus** [comment]
Duplicate #2781 #2784
