### ISSUE TITLE
Failed to import the widget in JupyterLab

### ISSUE THREAD

**Issue by gioxc88** [finos/perspective#2820]
When I try to load the widget in Jupyter lab it fails with an error saying 

importlib has no attribute metadata 

Perspective version 3.1.3
JupyterLab version 4.2.5 
Python version 3.19

**Comment by texodus** [comment]
Closing, please follow the [Github Issue template](https://github.com/finos/perspective/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) in the future.

This does not look related to Perspective but rather your Python installation. [Details on this API module](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata). Regardless of cause, I cannot repro this (again, see the Issue template).

[We build and test the JupyterLab widget on all platforms we build wheels for during CI](https://github.com/finos/perspective/actions/runs/11615664173), for future reference this is a good place to sanity check before opening an issue.

**Comment by texodus** [comment]
@timkpaine seems to think this is an addressable issue and has a PR open that may resolve this #2841 

This PR will be in 3.2.0 which may coincidentally also be the first release where we add official Conda support.
