### ISSUE TITLE
PerspectiveWidget doesn't work after change view type

### ISSUE THREAD

**Issue by ruoyu0088** [finos/perspective#2827]
run the following code in jupyterlab:

```python
import pandas as pd
import perspective

data = pd.DataFrame(dict(
    x=[1.0, 2.0, 3.0],
    y=[1.0, 3.0, 2.0]
))

w = perspective.widget.PerspectiveWidget(data)
w
```

the widget is shown correctly:

![image](https://github.com/user-attachments/assets/6fc6029e-cbd1-402c-89a4-4d4f744c0630)

switch view type to X/Y line also works:

![image](https://github.com/user-attachments/assets/c0ad5be3-0021-4bfc-8a01-34116e3eec47)

then switch back to DataGrid, it doesn't work, there is a bottle icon on the left top corner:

![image](https://github.com/user-attachments/assets/f82e0b1c-46d3-44fc-9ec2-7b333b87512c)

and here is the output of the console:

```
Uncaught TypeError: Cannot read properties of null (reading 'setSelection')
    at Vp.qX (253.0ce9cb0d4f76016e411c.js?v=0ce9cb0d4f76016e411c:18:58281)
    at Vp.RX (253.0ce9cb0d4f76016e411c.js?v=0ce9cb0d4f76016e411c:18:59274)
    at Vp.restore (253.0ce9cb0d4f76016e411c.js?v=0ce9cb0d4f76016e411c:18:62217)
    at QT.e.wbg.__wbg_restore_ecfb5129680ce27e (253.0ce9cb0d4f76016e411c.js?v=0ce9cb0d4f76016e411c:2:1157381)
    at 00960502:0x145e29
    at 00960502:0x5a42a
    at 00960502:0x407b5
    at 00960502:0x15f464
    at 00960502:0x91045
    at 00960502:0x9ec36
```

versions:

* python: 3.13.0
* ipywidgets: 8.1.5
* jupyterlab: 4.3.0
* perspective: 3.1.3
* finos-perspective-jupyterlab: 3.1.3

**Comment by ptomecek** [comment]
I also have the same issue. Switching the plugin type also doesn't seem to work properly in 2.10.1.
