### ISSUE TITLE
Odd Error that hangs the UI

### ISSUE THREAD

**Issue by yuj2i0** [finos/perspective#2868]
![image](https://github.com/user-attachments/assets/a388849f-c828-4316-bcef-270236b4a881)

Copy and paste the JSON Config below to the Editable Perspective Example

`{
  "version": "3.1.3",
  "plugin": "Datagrid",
  "plugin_config": {
    "columns": {},
    "edit_mode": "EDIT",
    "scroll_lock": false
  },
  "columns_config": {},
  "settings": true,
  "theme": "Pro Light",
  "title": null,
  "group_by": [
    "Country",
    "State",
    "City",
    "Category"
  ],
  "split_by": [],
  "columns": [
    "Profit",
    "Sales"
  ],
  "filter": [
    [
      "Customer Name",
      "in",
      "Aaron Bergman"
    ],
    [
      "Product Name",
      "in",
      [
        "\"\"While you Were Out\"\" Message Book",
        "One Form per Page"
      ]
    ],
    [
      "Region",
      "==",
      "East"
    ],
    [
      "Category",
      "==",
      ""
    ]
  ],
  "sort": [],
  "expressions": {},
  "aggregates": {}
}`

https://[perspective.finos.org/blocks/editable/index.html](https://perspective.finos.org/blocks/editable/index.html)

Choose Category as Furniture
Then backspace so it's empty, the UI hangs
![image](https://github.com/user-attachments/assets/f4dc433e-3fb1-4db5-bcf1-1e39c824272b)

**Comment by texodus** [comment]
Locking as the comments have devolved. We are aware there is a serialization issue with filter strings in some cases.
