### ISSUE TITLE
node_modules does not exist

### ISSUE THREAD

**Issue by eric-suptime** [finos/perspective#2878]
https://github.com/finos/perspective/blob/master/examples/python-tornado-streaming/server.py#L112
^ the example references `../../node_modules` which - eliding the issue with the relative paths where a `Path(__file__).parent.parent.as_posix()` would be safer - does not exist.

If I could go so far as to make a suggestion, it might be helpful to automate some testing of the examples if they are expected to work as-is.

**Comment by eric-suptime** [comment]
Worth noting that this issue applies to the axum rust example as well.

I don't think... any of the examples work with 3.x?

**Comment by texodus** [comment]
The examples are structured to run in-place in the source tree after build as a [`pnpm` workspace](https://pnpm.io/workspaces), so you will need to start them from the workspace root, [as described in the `DEVELOPMENT.md` docs](https://github.com/finos/perspective/blob/master/DEVELOPMENT.md):

```
pnpm start python-tornado
```
