### ISSUE TITLE
don't support Decimal Type for arrow 

### ISSUE THREAD

**Issue by dknfeiov** [finos/perspective#333]
when i convert data from database to arrow , the  Oracle database has the field  type decimal, which is automatically converted by Java arrow api
It doesn't support by perspective , i view the code 
![image](https://user-images.githubusercontent.com/8175516/49350067-76c0ea00-f6e8-11e8-84e2-8e89d5bb497e.png)
is it yet to be realized ?

**Comment by dknfeiov** [comment]
Converting Decimal type to Float at the data source is a solution

**Comment by texodus** [comment]
Thanks for the report - this is a real issue, born out of lazy implementation.  Only real impediment to adding this is the PITA of generating a new Arrow with the proper types for testing ...

**Comment by texodus** [comment]
I'd like to keep this open if you don't mind - as a reminder that this is not implemented and we need to fix it.

**Comment by texodus** [comment]
ThIs has been implemented in `0.4.0-rc.4`
