### ISSUE TITLE
Feature request: parquet data files support

### ISSUE THREAD

**Issue by RandomFractals** [finos/perspective#342]
how hard would it be to add parquet data files support to the perspective viewer?

in relation to this vsscode ext. I've decided to work on utilizing your lib:

https://github.com/RandomFractals/vscode-data-preview

I belive it can be done in JS with this lib I found:

https://github.com/ZJONSSON/parquetjs

most likely just a matter of providing proper data read interfaces for perspective viewer to consume and display that data

**Comment by mhkeller** [comment]
I'm also curious if perspective could be pointed to a parquet file. I was looking into using [duckdb to export database queries as parquet files](https://duckdb.org/docs/guides/import/parquet_export.html) and then pointing perspective at that file to load the results.

**Comment by texodus** [comment]
This feature is out-of-scope for Perspective. For the Python side, `pyarrow` and friends already support this (we would just recompile this support into Perspective anyway). For JavaScript, Perspective is designed to be used as a component, not a platform, preferring small size and performance to coming bundled with every possible format.

If you're looking for a turn-key platform approach to BI that incorporates a wide variety of data adapters, analytics, persistence and discovery features, check out our [enterprise platform](https://prospective.co/).

**Comment by mhkeller** [comment]
For anyone looking to try this, here's a script that will read in a parquet file and give you back the buffer representation of an arrow file: https://gist.github.com/mhkeller/855ca5c0a6582e4ead7d36e6f8169fdd

There is likely a better way to do this and I'm not taking this approach, but sharing this here in case it helps someone.

Related discussion: https://github.com/finos/perspective/issues/1157
