### ISSUE TITLE
Suggested improvements to the build

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/perspective#376]
I understand that the build for this project is a little complex (as pointed out by the documentation), however, I think it can be simplified :-)

I think there are a lot of people who would potentially contribute to the JavaScript packages, however, at the moment they are faced with the complexity of Emscripten / Docker etc ...!

Ideally someone working on one of the plugins should be able to iterate on that codebase without having to tackle the complexity of building the C++ perspective codebase.

I think the current monorepo structure makes a lot of sense, as does the use of Lerna, however, I don't think it is being used effectively.

One of the core features of lerna is the [bootstrap](https://github.com/lerna/lerna/tree/master/commands/bootstrap#readme) command which forms symlinks between the sub-packages. Perspective currently doesn't use this. As a result, the build infrastructure is all within the root of the repo.

I'm pretty sure that with the bootstrap process it is possible to make a sub-package reference the npm distribution of a particular dependency. As a result, it should be possible to run the build in such a way that the JavaScript packages simply reference the distribution wasm files for perspective.

Anyhow, just thought I'd raise this issue to give you a heads-up that I'm taking a look at this!

Let me know if you have any questions / comments or concerns?

**Comment by ColinEberhardt** [comment]
Thanks for the additional information - I’ve not seen yarn workspaces before ... I’ll take a look and see whether that can be used to make it easier to iterate on the JavaScript packages.

**Comment by ColinEberhardt** [comment]
I've had a bit of a read about yarn workspaces, so from my understanding perspective uses workspaces for package linkage, and lerna as a script runner and for releases? If that is correct, I'll update the documentation.

If I run a focus install build within `perspective-viewer`, I can see that it fetches the Perspective dependencies from npm. However `yarn run build` fails as follows:

```
[...]
Time: 115ms
                  Asset     Size  Chunks             Chunk Names
    perspective.view.js  1.69 kB       0  [emitted]  main
perspective.view.js.map  7.41 kB       0  [emitted]  main
   [0] ./src/js/viewer.js 353 bytes {0} [built] [failed] [1 error]

ERROR in ./src/js/viewer.js
Module parse failed: Unexpected character '@' (36:0)
```

I think the issue here is that the various components of the custom build, including the babel configuration, are locates within `packages/perspective/webpack-plugin.js`. This isn't part of the bundle uploaded to npm (as expected).

When creating a focus install, the build cannot locate the webpack configuration.

I think the build related scripts should probably all be in the project root?

**Comment by texodus** [comment]
@ColinEberhardt Yes, this is exactly how we are using lerna and webpack; but no, the [webpack plugin](https://unpkg.com/@jpmorganchase/perspective@0.2.12/webpack-plugin.js) and [babel config](https://unpkg.com/@jpmorganchase/perspective@0.2.12/babel.config.js) are indeed part of the bundle uploaded to NPM.  Furthermore, the error you pasted is not from the NPM package, it is from the local `@jpmorganchase/perspective-viewer` package you are trying to build, which also has [its own babel config](https://unpkg.com/@jpmorganchase/perspective-viewer@0.2.12/babel.config.js).  This certainly does not have to do with missing or mislocated configs, at least not in the repository itself.

I have tested this locally on a completely clean checkout of master and it works just fine in all packages except `@jpmorganchase/perspective-jupyterlab`, which fails for expected Jupyterlab dependencies.  Any chance you want to double check this is on a clean checkout and verify that this does not work?  Either way I need more information to help.
