### ISSUE TITLE
Feature request: Column Name aliasing

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#433]
As a user, I want to be able to load a column from my web server call `myColumn`, but configure the javascript to display the column name as something else, say `My Fancy Column`. I don't want to do this on the backend because other services consume my API, and I don't want them to have to think about spaces in the name.

**Comment by texodus** [comment]
Column aliasing can be achieved via the  `<perspective-viewer>` API:

```javascript
await viewer.restore({
    columns: ["My Alias Column"],
    expressions: ['//My Alias Column\n"Original Column"']
});
```

... and via the UI:

![alias](https://user-images.githubusercontent.com/60666/127268242-a66f3fab-b320-4a84-b20c-984009027598.gif)
