### ISSUE TITLE
Provide human-readable dates (optionally?) from Perspective `to_csv()` method

### ISSUE THREAD

**Issue by texodus** [finos/perspective#524]
Currently these are returned as POSIX time - which unfortunately for the download/copy buttons in `<perspective-viewer>`, is not particularly readable.

**Comment by RandomFractals** [comment]
I suggest you guys change it to UTC date format for date/time columns/fields since those show up properly in most CSV/Excel viewers and are loaded as dates in perspective viewer, i.e `2019-07-12T18:00:00`: https://www.w3.org/TR/NOTE-datetime

**Comment by RandomFractals** [comment]
@texodus I could really use this fix. Can you grab and merge that PR? Otherwise, dates are really borked in csv and arrow :(

**Comment by texodus** [comment]
This has been addressed in #524 and #1281
