### ISSUE TITLE
Copy (ctrl + c) and (ctrl + v) Paste data from Perspective Grid (Excel like functionality) by selecting the cells directly from the grid.

### ISSUE THREAD

**Issue by mcdemjp** [finos/perspective#535]
Similar functionality available in hypergrid which allows uses to select a range of cells in a grid and copy it by ctrl + c and paste it in excel.

**Comment by erolosty** [comment]
this would be really good. Any tips for a noobie?

**Comment by robambalu** [comment]
Did this get anywhere?  Is it possible to copy just a single cell?

**Comment by texodus** [comment]
This was implemented in #2618
