### ISSUE TITLE
Long column names make Hypergrid view unreadable

### ISSUE THREAD

**Issue by texodus** [finos/perspective#554]
Because columns are autosized to the longest of either their content rows or header name, integer columns with long names can make extremely wide columns that make grids somewhat unreadable.  We should probably add a few fixes -
* Make column names support wrapping
* Make defaults smart enough to cut off long columns on e.g. integer columns that have a roughly bounded print row length.
* Support global meta configs for column defaults

**Comment by timkpaine** [comment]
@texodus should this be closed now that regular-table is the primary?

**Comment by texodus** [comment]
Yes - this issues still exists in `regular-table` but the fix really belongs with that repo.
