### ISSUE TITLE
Port Perspective js examples to Observable js notebooks for dataViz devs to experiment with

### ISSUE THREAD

**Issue by RandomFractals** [finos/perspective#560]
## Feature Request

You have great examples and I recently discovered this set ported to blocks:

https://bl.ocks.org/JHawk

![perspectivejs-blocks](https://user-images.githubusercontent.com/656833/57032671-906f4a80-6c10-11e9-9dc0-f9d3bce5dfef.png)

### Description of Problem:

I believe your library could get even more traction if we ported your examples to Observable JS notebooks. 

### Potential Solutions:

I sort of started on that last year and would be willing to give you a hand with it

https://observablehq.com/@randomfractals/perspective

Ideally, I think you should create https://observablehq.com/@perspective dev team handle on @observablehq and share it with @mbostock. He is usually good with sharing good javascript libraries and dataViz examples collections like yours.

Alternative solution: I can create and beef up a #perspective collection for js notebooks on @observablehq under my current handle there, and you guys can fork, suggest or take what you want from it when you get to it.

P.S.: also, why is your github @perspective handle pointing to? https://github.com/perspective :)

**Comment by Ro4052** [comment]
The reason that handle is pointing to the wrong place is that Perspective is the name of the repo rather than a handle. 🙂

**Comment by RandomFractals** [comment]
I must be doing something wrong here. Could use @timkpaine or other core perspective js lib devs help to help me show that grid :) 

https://observablehq.com/@randomfractals/data-inspector

**Comment by RandomFractals** [comment]
I had better luck with this in vscode. still need to talk to you how you gen. that hypergrid plugin js for imports...

see here for now: https://github.com/fin-hypergrid/core/issues/804#issuecomment-493700624

**Comment by RandomFractals** [comment]
somewhat related: https://github.com/RandomFractals/vscode-data-preview

![vscode-data-preview-dark](https://user-images.githubusercontent.com/656833/58372333-490f6d80-7ee1-11e9-83f2-8bf46644a5eb.png)

Probably the best demo app in public domain using your lib aside from the new demo site you just put out at https://perspective.finos.org/

Feel free to include that Data Preview ext. in your Powered By/Used By wiki/docs page on your new site or in this repo when you get to it. It's an OSS repo with some nifty perspectivejs lib and vscode api usage I bet devs would have fun exploring.

Cheers!

**Comment by RandomFractals** [comment]
@texodus  feel free to close this ticket. Devs can use your d3 blocks if you are not buying @observablehq :)
