### ISSUE TITLE
View appears twice in docs

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#569]
https://github.com/finos/perspective/tree/master/packages/perspective-viewer
<img width="346" alt="Screen Shot 2019-05-07 at 11 47 30 PM" src="https://user-images.githubusercontent.com/3105306/57348035-912d4280-7122-11e9-988b-27aaf902add7.png">

**Comment by texodus** [comment]
Thanks for the report!

This was actually 2 properties - the `perspective.table.view` object, and the string enum for the currently selected plugin.  The latter has been renamed `plugin` in #639
