### ISSUE TITLE
Document arrow data types to perspective data schema load init mapping

### ISSUE THREAD

**Issue by RandomFractals** [finos/perspective#601]
## Support Question

I had to do this fine dance after looking at your `utils.js` and `perspective.js#ArrowColumnLoader` to figure out how to inject arrow data types schema and translations into perspective.js from arrow data schema in my `config.ts`: https://github.com/RandomFractals/vscode-data-preview/blob/master/src/config.ts

```js
// arrow to data view type mappings
// see: https://github.com/finos/perspective/blob/master/packages/perspective/src/js/utils.js
// and https://github.com/finos/perspective/blob/master/packages/perspective/src/js/perspective.js#ArrowColumnLoader
export const dataTypes = { 
  "Binary": "string",
  "Bool": "boolean",
  "Date": "date",
  "Dictionary": "string",
  "Float32": "float",
  "Float64": "float",
  "Int8": "integer",
  "Int16": "integer",
  "Int32": "integer",
  "Int64": "integer",
  "Timestamp": "datetime",
  "Utf8": "string",
};
```

after hours of code browsing, I found that your `load({object, object}` method lets me set data schema and `utils.js#get_column_types()` helped me infer what your corresponding arrow data types are.

Could use better enum or docs on this.

I ended up doing this in my `data.preview.ts` for arrow data types mapping:

```js
    // remap arrow data schema to columns for data viewer
    this._schema = {};
    dataTable.schema.fields.map(field => {
      let fieldType: string = field.type.toString();
      const typesIndex: number = fieldType.indexOf('<');
      if (typesIndex > 0) {
        fieldType = fieldType.substring(0, typesIndex);
      }
      this._schema[field.name] = config.dataTypes[fieldType];
    });
```
and then this tricky biz in `data.preview.html`:

```js
            viewer.restore(viewConfig);
            if (data.schema !== undefined && Object.keys(data.schema).length > 0) {
              // viewer.columns = viewConfig['columns'];
              viewer.load(data.schema);
              viewer.update(tableData);
            }
            else {
              viewer.load(tableData);
            }
```
It worked! I just wish I did not have to spend hours to figure it out. Thx! 

BTW, your arrow data support is awesome! Check out mine too! :)

**Comment by RandomFractals** [comment]
@texodus & @timkpaine any updates on this?

**Comment by texodus** [comment]
No update;  this is a valid issue, but not in my immediate dev plan.  For now, perspective supports well only the base types supported by Javascript:  32bit signed int, double, string, bool, datetime.  PRs welcome, as always.

**Comment by RandomFractals** [comment]
you keep saying that yet dates still could use some work :( 

Can you at least address this 1 pesky issue with dates in your next v0.37 rc release?

https://github.com/finos/perspective/issues/524

Thx in advance!

**Comment by RandomFractals** [comment]
you can close this ticket. I can find my ways around your repo :)
