### ISSUE TITLE
Add support for rollup bundler

### ISSUE THREAD

**Issue by zemeolotu** [finos/perspective#605]
I'd like to be able to use perspective in my project that's bundled with [rollup](https://github.com/rollup/rollup)

**Comment by texodus** [comment]
I made an attempt at porting `@finos/perspective-viewer` and `@finos/perspective-viewer-d3fc` to rollup and eventually got them ~95% working, but I'm uncertain the results merit continued development.
* The bundles are approximately the same size as Webpack's.
* There doesn't appear to be any discernable load time differences, with the caveat that the bundles from both bundlers are large.
* `rollup` has lots of points in its favor in terms of design and features, but ~1/3 dependencies  are an adventure to get working or not possible, as opposed to Webpack. (Both `d3fc` and `@apache/arrow` have unresovlable issues, so far).

Branch is [here](https://github.com/finos/perspective/tree/rollup-test) .  We could pursue a hybrid approach, using `rollup` for CJS builds and `webpack4` for unpkg builds, but given the lack of measurable impact of `rollup`'s bundling approach it I'm in favor of juat changing the CJS exports to be from `webpack4`.  This would still allow us to remove the LESS/HTML loaders from the `@finos/perspective-webpack-plugin`.

**Comment by texodus** [comment]
After some more research, this doesn't seem like it offers a clear advantage over webpack at this time, so closing.
