### ISSUE TITLE
Request to Feature perspective on Docusaurus users page

### ISSUE THREAD

**Issue by ericbuss** [finos/perspective#613]
Hello, we would like to feature your project to the Docusaurus [users](https://docusaurus.io/en/users) page.

If you are okay with it, are you able to provide a logo we can use? Additional information can be found [here](https://github.com/facebook/Docusaurus/issues/1437)

**Comment by timkpaine** [comment]
@ericbuss we're in the process of modifying our branding, will let you know when we update.

**Comment by texodus** [comment]
@ericbuss Apologies for the delay.  We are OK with it, and Perspective now has a logo!  Feel free to mark us down as happy users of Docusaurus.


![Perspective](https://perspective.finos.org/img/logo_inverted.png)

![Perspective](https://perspective.finos.org/img/logo_inverted_small.png)

![Perspective](https://perspective.finos.org/img/logo_inverted_tiny.png)

**Comment by timkpaine** [comment]
@ericbuss closing, feel free to add our logo to the page
