### ISSUE TITLE
Jupyter: Export static image so pdf conversion works

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#617]
https://github.com/plotly/plotly.py/pull/1623

**Comment by texodus** [comment]
This is a bit tricky for the core lib as we still rely heavily on SVG for both the Highcharts and D3FC plugins.  We could try rendering the SVG to canvas via [canvg](https://github.com/canvg/canvg) or similar but should probably restrict its inclusion to the Jupyterlab plugin as it is a quite large lib.

**Comment by RandomFractals** [comment]
saving svg and converting to png doesn't require canvas g. start here :) https://stackoverflow.com/questions/20207924/how-can-i-convert-an-svg-node-to-png-and-download-it-to-the-user

**Comment by RandomFractals** [comment]
related: https://github.com/finos/perspective/issues/646#issuecomment-511141066

**Comment by timkpaine** [comment]
closing as this is out of scope for now, we can revisit in the future. Given that perspective-python now supports going to and from dataframe/arrow, in the context of NBConvert it is relatively easy to just swap out perspective's grid and plotting for pandas native rendering and matplotlib, respectively.
