### ISSUE TITLE
Feature request: Add virtual column pairs to show or search

### ISSUE THREAD

**Issue by akan** [finos/perspective#645]
now column name is transferred in table data, not in metaData.
I mean table data is like:
[
{"column1":value1,"column2":value2 .....}
{"column1":value1,"column2":value2 .....}
...
]
or like:
[
[value1,value2...]
[value1,value2...]
...
]
a virtual column pairs is like:
{"aaa":"column1", "bbb":"column2",...}
then the table is showing:
-----------------
aaa       | bbb
-----------------
value1  |  value2
value1  |  value2
-----------------

**Comment by texodus** [comment]
Thanks for the report!  Unfortunately I have no idea what you're asking - you can't name your columns "aaa" and "bbb"?

**Comment by texodus** [comment]
If you come up with some details, feel free to open a new issue.
