### ISSUE TITLE
D3FC charting options

### ISSUE THREAD

**Issue by akansal1** [finos/perspective#646]
@DevAndyLee,  I want to reuse D3FC chart in my app without editing options but, with that I would also like to update charting options like title etc, that D3FC allows.
Is there a way, where I can reference D3FC object to pass those custom charting options/settings ?

**Comment by RandomFractals** [comment]
likewise for export SVG or png from charting libraries used by perspective viewer plugins.

see a brief usage scenario here: https://github.com/RandomFractals/vscode-data-preview/issues/10

**Comment by RandomFractals** [comment]
related: https://github.com/d3fc/d3fc/issues/1290

**Comment by texodus** [comment]
Thanks for the feature request!

While this sounds like a powerful feature, this is a bit out-of-scope for Perspective development today.  Returning the D3FC object itself will necessarily introduce tight coupling to how `@finos/perspective-viewer-d3fc` generates this object, so probably not a good fit;  A better approach might be to use the currently D3FC implementation as a reference to build your own chart on Perspective's [plugin API](https://blog.scottlogic.com/2019/04/23/perspective-plugin-api-how-to-build-a-new-plugin.html).

That being said, perspective will continue to add new customization features as they are available in the UI/UX of `@finos/perspective-viewer`, and this may include e.g. titles, axis labels etc., so feel free to open new requests for specific visualization features.
