### ISSUE TITLE
Heatmap Customizing Thresholds

### ISSUE THREAD

**Issue by canselcik** [finos/perspective#647]
I am using the heatmap view in the Perspective Viewer and everything is working well but I am looking to customize the color thresholds. Any way to achieve this through attributes or via Javascript?

**Comment by texodus** [comment]
Though not documented yet, you can [override the color range used by the heatmap via CSS](https://github.com/finos/perspective/blob/master/packages/perspective-viewer/src/themes/material.dark.less#L76)

```css
perspective-viewer {
    --d3fc-gradient-full: linear-gradient(
        #feeb65 0%,
        #e4521b 22.5%,
        #4d342f 42.5%,
        #222222 50%,
        #1a237e 57.5%,
        #42b3d5 67.5%,
        #dcedc8 100%
    );
}
```

You will [need the `is="custom-style"`](https://polymer-library.polymer-project.org/2.0/docs/devguide/style-shadow-dom#custom-style) attribute depending on your browser's support for custom elements.

```html
<link rel='stylesheet' href="material.css" is="custom-style">
```
