### ISSUE TITLE
Website: shows blank perspecitve viewers in FF v68 (64-bit) Quantum

### ISSUE THREAD

**Issue by RandomFractals** [finos/perspective#656]
might be related to your most recent web site update and new release v0.3.4

![perspective-website-blank-grids](https://user-images.githubusercontent.com/656833/61171728-6526a700-a541-11e9-9c32-82f94a333bca.png)

**Comment by RandomFractals** [comment]
console log:

![perspective-site-console-log](https://user-images.githubusercontent.com/656833/61171900-7ffa1b00-a543-11e9-8eb3-596f22b86982.png)

**Comment by RandomFractals** [comment]
chrome console log: (note: diff. wasm worker path, which works!) I hope this helps you to resolve it for FF:

![perspective-site-chrome-console-log](https://user-images.githubusercontent.com/656833/61171981-67d6cb80-a544-11e9-8f89-bb6f39bd073d.png)

**Comment by texodus** [comment]
Thanks for the report.  This was just an issue with how CDN paths were referenced by the docs site - it's been fixed.
