### ISSUE TITLE
MissingDependencyError: perspecitveJS packaging & bundling issues ...

### ISSUE THREAD

**Issue by RandomFractals** [finos/perspective#658]
see: https://bundlephobia.com/result?p=@finos/perspective & https://bundlephobia.com/result?p=@finos/perspective-viewer

somewhat related: #605 Add support for rollup bundling

![perspective-bundling-error](https://user-images.githubusercontent.com/656833/61174837-8b613c80-a56b-11e9-9633-3c43b1d5813a.png)

**Comment by texodus** [comment]
Thanks for the report, but please [see the issue template] for reporting an issue with Perspective.

I'm not sure what bundlephobia is meant to do - but perspective requires a plugin for `webpack`, even just to resolve the worker module itself.   Switching to rollup will not change this.

**Comment by RandomFractals** [comment]
@texodus  for the record, hre is an example for bundlephobia does for good libs that got their bundling and packing down and right: 

https://bundlephobia.com/result?p=superagent@5.1.0

I suggest you repopen this ticktet and spend a bit more time on this topic because your last v. pushes have been a bit sketchy and even side-loading changes to prior versions hosted on CDN's that make it questionable of how stable and reliable your release bundles are:

![perspective-bundling-superagent-info](https://user-images.githubusercontent.com/656833/61208718-a8a62000-a6bd-11e9-9e00-a9efb209e2da.png)
