### ISSUE TITLE
Types doesnt match, no test to check

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#674]
According to [this file](https://github.com/finos/perspective/blob/master/packages/perspective-viewer/index.d.ts#L20) there is a `view` attribute, but it does not exist. It is now called `plugin`. There needs to be a test to check that the types file matches the real thing.

**Comment by texodus** [comment]
If only there was a technology that verified that types accurately describe your code ...

**Comment by texodus** [comment]
Snarkiness aside - most of this file is just wrong anyways.  `<perspective-viewer>` is ultimately an HTML Element with some methods, and there's no native way to get an instance of a perspective-viewer in TypeScript, so my inclination is to remove this file and let TypeScript users write their own casts.

**Comment by timkpaine** [comment]
I support that

**Comment by RandomFractals** [comment]
what was the motivation for that view to plugin attribute change?

Do you expect every view type to have its own plugin? hmm...

Would it be more prudent to keep the view attribute and just introduce plugin attribute for the plugin config options instead? I see them as two different entities. For example, a charts plugin might provide different chart type views, yet have one plugin config option.

Also, I am sure this change breaks a lot of working examples online.

**Comment by RandomFractals** [comment]
I just love when @texodus closes random issues like this without any comments or intelligent followups. you do you! :)
