### ISSUE TITLE
Don't capture scroll over hypergrid whitespace

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#677]
Should be not capture scroll when theres a lot of whitespace? Alternatively, is there a CSS rule that can let the grid expand to the width of the component?  

![tmp](https://user-images.githubusercontent.com/3105306/62395801-511e0600-b53f-11e9-851a-fb5b57a88c89.gif)

**Comment by texodus** [comment]
We should capture scroll anywhere to the left of the scrollbar, and this should be sticky to the right of the `<perspective-viewer>` plugin boundary.  Excel, for example, behaves this way, and this is the behavior you want in app-like layouts.

For document-like layouts as in your GIF, you may want to consider moving the scrollbar, e.g. setting `width` or `max-width` as a `perspective-viewer` CSS rule.  I'm open to adding a CSS mode whereby horizontal space is conserved, if there's enough demand for it.

**Comment by timkpaine** [comment]
closing as this won't be relevant soon

**Comment by texodus** [comment]
Just FYI - `@finos/perspective-viewer-datagrid` has the same behavior, since it is just a scrollable `<div>`

**Comment by timkpaine** [comment]
@texodus yeah but the div is more easily style-able with vanilla css versus the canvas. Determining the width of the cells in the canvas was impossible
