### ISSUE TITLE
[D3FC] Canvas plots don't have tooltips with d3fc@14.0.44

### ISSUE THREAD

**Issue by quigleyj-mavenomics** [finos/perspective#678]
There's an issue with tooltips on canvas charts (eg, the Candlesticks and OHLC charts) where they [target an element `d3fc-svg svg`](https://github.com/finos/perspective/blob/8cbd0fd38e3711ff0f4a5b72b1e9469f4926d6c8/packages/perspective-viewer-d3fc/src/js/tooltip/nearbyTip.js#L55) instead of targeting the chart more generically. This worked previously, as D3FC apparently [created both a `<canvas>` element and an `<svg>` element](https://github.com/d3fc/d3fc/blob/170b25711ef1fedb3adbee5dbff94e66114b17ff/packages/d3fc-chart/src/cartesian.js#L22-L23) regardless of the chart's actual type.

However, as of [d3fc@14.0.44](https://github.com/d3fc/d3fc/commit/673a15ddb29262a6405ae7c9cdec78015864b161#diff-27a71f509681f99414d0edf418ab7229L22-R23), it now only instantiates one _or_ the other. As a result, charts that use SVGs work as expected, whereas charts that use Canvas elements don't get tooltips.

This was a patch update for D3FC, and in the Perspective repo's [yarn lockfile](https://github.com/finos/perspective/blob/8cbd0fd38e3711ff0f4a5b72b1e9469f4926d6c8/yarn.lock#L4468) it's pulling in d3fc@14.0.40. This version does not include the change and thus works as expected.

**Comment by texodus** [comment]
Thanks for the exceptionally well researched report, it is very helpful!  I'll get this fixed - in what environment are you seeing d3fc@14.0.44 ?

**Comment by quigleyj-mavenomics** [comment]
We started seeing it after we refreshed our yarn lockfile- [`@finos/perspective-viewer-d3fc` uses a caret pin](https://github.com/finos/perspective/blob/master/packages/perspective-viewer-d3fc/package.json#L73) so 14.0.44 is in-range. Our project doesn't have a direct dependency on d3fc, just Perspective and the Perspective D3FC plugin. Here's the relevant entry from our yarn lockfile:

```
d3fc@^14.0.34:
  version "14.0.44"
  resolved "https://registry.yarnpkg.com/d3fc/-/d3fc-14.0.44.tgz#34c7f87a57ceb5574ac04f9b59e468993004e82d"
  integrity sha512-ILL+u/tEQOlV+P8KNhaq14hnQGL2F1Oukk8MMV7C0Jk0crOSlaEsoe94oXZmJ7mwvio4S536G0d4hDPzSiM3xw==
```

The workaround is to use yarn resolutions, so that we can force 14.0.40 instead (which works):

```
d3fc@14.0.40, d3fc@^14.0.34:
  version "14.0.40"
  resolved "https://registry.yarnpkg.com/d3fc/-/d3fc-14.0.40.tgz#568098ca3e220fac132c7a154299a858abae26ef"
  integrity sha512-rThy0zNIEeWzmAkUshZJLU3ACNWvnP0o2qQyCuW/IXzAhRVuuLtGm4HnIA44+a4pFYbgGS6OSiZf5bCK/uVnUA==
```
