### ISSUE TITLE
No dist

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#681]
https://unpkg.com/browse/@finos/perspective-jupyterlab@0.3.6/

**Comment by texodus** [comment]
This was already [fixed by you](https://github.com/finos/perspective/pull/673/files#diff-fd1b93510fc4ebc977a5db2fffbd66b1L58), no?

**Comment by timkpaine** [comment]
Ah has there not been a release? I expected there to be something in this folder but I guess my fix should resolve this anyway
