### ISSUE TITLE
Hook perspective into ipywidgets

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#694]
`if (this.pWidget) { this.pWidget.add(this.psp); }`
@vidartf

**Comment by vidartf** [comment]
There is also the pattern used in `controls`: https://github.com/jupyter-widgets/ipywidgets/blob/48b2d815b200a28e1267c7a877d89e6457e5696f/packages/controls/src/widget_selectioncontainer.ts#L104-L110
