### ISSUE TITLE
Make Filter Fields accept text with auto-suggest for Column selections

### ISSUE THREAD

**Issue by RandomFractals** [finos/perspective#704]
similar to how aggregate and filter operands function now.

### Description of Problem:
I would like to type a column name to filter on or group by without dragging it from the Columns left side panel for quickly setting up viewer data filtering, sorting & grouping config/settings.

**Comment by jdb78** [comment]
This would be a real big improvement!

**Comment by oogetyboogety** [comment]
Definitely was thinking it would be nice if it was more intuitive. You have to thoroughly read that doc page at least twice which describes the column expressions

**Comment by texodus** [comment]
Implemented in `v2.0.0`
