### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by NMinhNguyen** [finos/perspective#709]
### Steps to Reproduce:
1. Navigate to https://unpkg.com/browse/@finos/perspective@0.3.8/dist/esm/perspective.parallel.js
2. Notice how it uses `const`, `class` etc.

### Expected Result:
I would expect to see `var` and `function` instead so that IE11 is supported.

### Actual Result:
ES2015+ doesn't appear to be transpiled.

### Environment:
IE11

### Additional Context:
https://github.com/finos/perspective/blob/aa32e7cc87fafdcbd1b530f534a5bb5ccb592cba/packages/perspective/babel.config.js#L6-L12 doesn't appear to specify IE11 as a target browser. There are other packages in addition to `@finos/perspective` that seem to have non-IE11 code, but as a workaround, I'm just running all of `@finos/perspective` via Babel loader for webpack to ensure no ES2015+ syntax. This seems to also match e.g. `@finos/perspective-foo` which works as a catch-all.

**Comment by texodus** [comment]
Thanks for the report!

We've unfortunately deprecated support for Internet Explorer, as this browser will never support WebAssembly, and Emscripten is moving away from support for asm.js as a compile target.  This change was made as part of the 0.3.0 release - version 0.2.x still supports asm.js.

**Comment by NMinhNguyen** [comment]
Ah thanks, didn't realise that was the case.
