### ISSUE TITLE
Expose toggleConfig in widget

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#714]
moved from https://github.com/timkpaine/perspective-python/issues/66

**Comment by dhirschfeld** [comment]
I've been trying to figure out how to hide the config panel from Python with no luck so far. This issue is closed - does that mean it *is* possible to call `toggleConfig` from Python?

**Comment by akarve** [comment]
Same question. How to `toggleConfig()` from Python? The linked Issue doesn't seem relevant, therefore maybe this was closed by mistake?

**Comment by dhirschfeld** [comment]
@akarve - you can add a :+1: to #1499 which is requesting this feature
