### ISSUE TITLE
Create config json schema for the viewer and plugins for documentation and config json validation

### ISSUE THREAD

**Issue by RandomFractals** [finos/perspective#746]
## Feature Request

This data viewer library requires a config to save and load filter/sort/group and display data settings.

### Description of Problem:

It would help if there was a json schema created for the viewer that documents all available general viewer config properties and customizations for plugins such as grid and charts.

### Potential Solutions:

See sample config json schema I've created for Data Preview to get started :) 

https://www.npoint.io/docs/0f5875b79bedf11e039a

**Comment by texodus** [comment]
Use `save()` and `restore()` to serialize and deserialize a viewer's settings, [as per docs](https://perspective.finos.org/docs/md/usage.html#setting-reading-viewer-configuration-via-attributes).

**Comment by RandomFractals** [comment]
this is not the same. Save and restore provide viewer config which is great.

What I am suggesting is create a valid [JSON schema](http://json-schema.org/) for the viewer config, grid and charts plugins.
