### ISSUE TITLE
Feature request: Add abs sum as an aggregator

### ISSUE THREAD

**Issue by jeffreyvt** [finos/perspective#750]
Hey team,

Currently we only have sum(abs(x)) and sum(x) available, where x is an array of floats.
As a user, I would like to have abs(sum(x)) available as an aggregator.

i.e. x = [5,-10, 2]

sum(abs(x)) = 17   <- feature already exists
sum(x) = -3            <-  feature already exists
abs(sum(x)) = 3     <- feature requested.

Thanks,
Jeff

**Comment by texodus** [comment]
This issue has progressed, but isn't quite done!  Details in #1031 - needs tests and wiring into `@finos/perspective-viewer`

**Comment by harsh-jindal** [comment]
I'll make a PR for the points mentioned in #1031
