### ISSUE TITLE
Datetime conversion in Python can overflow non-deterministically

### ISSUE THREAD

**Issue by sc1f** [finos/perspective#754]
When we convert datetimes to Unix timestamps, at non-deterministic times overflows may happen - the attached screenshot caused an overflow error at ~9:57:30-9:58:15PM, but did not error again when run at ~9:58:30PM.

<img width="839" alt="Screen Shot 2019-10-05 at 9 58 46 PM" src="https://user-images.githubusercontent.com/13220267/66263128-85ba7200-e7bb-11e9-8db5-22b2d66ea1a9.png">

**Comment by texodus** [comment]
In lieu of a repro, going to go ahead and close this issue, as our date/datetime processing has matured quite a bit since reporting.
