### ISSUE TITLE
Phosphor workspace doesn't resize when embedded in other phosphor widgets

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#808]

**Comment by texodus** [comment]
Thanks for the report!

This is not the case however.  [This line](https://github.com/timkpaine/crowdsource/blob/master/src/ts/main.ts#L136) call `resize()` on `workspace` instead of the container actually attached to the DOM, `main`.

**Comment by timkpaine** [comment]
I have a workspace embedded in a split panel and it does not work
