### ISSUE TITLE
Readd pip install and sdist test

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#816]
https://github.com/finos/perspective/commit/966d533f8f56a3829cb24b07f530a0b437285154#diff-b23a161aa71df80df5c594015a1cdb7b

**Comment by timkpaine** [comment]
the pip install and the sdist command are to ensure the source build works. in deleting them (and the commits that went along with it) we have broken the source dist and pip install.

**Comment by texodus** [comment]
Please track these in [projects](https://github.com/finos/perspective/projects).
