### ISSUE TITLE
How to delete a hosted table?

### ISSUE THREAD

**Issue by andyferris** [finos/perspective#841]
## Support Question

I am trying to `delete` a table hosted by a `WebSocketServer` in NodeJS, and I get the error `Table still has contexts - refusing to delete.`. In my case, we seek to dynamically create and destroy tables of different names on the server. Later on, a new table with the same name might appear (with a different schema).

As far as I can tell (I'm new here...) a view is created here which can never be deleted: https://github.com/finos/perspective/blob/a912c9f23f1cab3e6ce97cdf65c6fe48f9ae9756/packages/perspective/src/js/perspective.node.js#L266

However... the view isn't returned so I'm not sure how to handle this case. The class doesn't seem to have an `unhost_table` method.

Is there anything better than using `clear` on the table and leaving it hosted in the server under that name?

**Comment by texodus** [comment]
Yes - that empty `view` is preventing the `table` from being deleted.  This was originally implemented to prevent the remotely-connected `<perspective-viewer>` from calling `delete()` on the remote `table` when it is itself `delete()`-ed - but I think maybe a better solution is to just not call `delete()` if a `table` is supplied to `load()` in the first place.

There is an `on_delete()` callback already on `table`, so with this change it should be easy to make `table` automatically un-host itself when it is deleted, but we should probably add an explicit `unhost_*` method pair anyway.  I will take a look at implementing this.

**Comment by andyferris** [comment]
Ok - that makes sense. Thank you, @texodus
