### ISSUE TITLE
python-perspective from pypi

### ISSUE THREAD

**Issue by adpoint72** [finos/perspective#856]
Tried following your example for python from https://perspective.finos.org/docs/md/python.html
pip install perspective-python installs version 0.1.11 from https://pypi.org/.
in that version there is no Table  in perspective 

In [1]: import perspective

In [2]: import pandas as pd

In [3]: data = pd.DataFrame({})

In [4]: table = perspective.Table(data)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-7adc3a7cbe18> in <module>
----> 1 table = perspective.Table(data)

AttributeError: module 'perspective' has no attribute 'Table'

**Comment by timkpaine** [comment]
That is correct, the C++ table hasn't been released yet. It was introduced in 0.4.0rc1
