### ISSUE TITLE
Using Perspective with Angular

### ISSUE THREAD

**Issue by nevi-me** [finos/perspective#860]
## Support Question

I'm trying to use perspective (and perspective-viewer) with Angular 8, but I'm getting import errors. The errors are below.

Is there some guidance for usage with Angular?
A part of the errors comes from requiring @apache-arrow/es5-esm`, but I saw in the PR for #850 that this is no longer a requirement (in master). I don't have WSL installed, so I wanted to ask if rebuilding from master is the only option, before I go down the WSL path.

```
Module not found: Error: Can't resolve '../../build/psp.async.wasm' in 'D:\angular8project\node_modules\@finos\perspective\dist\esm'
ERROR in ./node_modules/@finos/perspective/dist/esm/perspective.wasm.js
Module not found: Error: Can't resolve '../../obj/psp.async.js' in 'D:\angular8project\node_modules\@finos\perspective\dist\esm'
ERROR in ./node_modules/@finos/perspective/dist/esm/perspective.js
Module not found: Error: Can't resolve '@apache-arrow/es5-esm/data' in 'D:\angular8project\node_modules\@finos\perspective\dist\esm'                                                                                                                                                      st\esm'
ERROR in ./node_modules/@finos/perspective/dist/esm/perspective.js
Module not found: Error: Can't resolve '@apache-arrow/es5-esm/table' in 'D:\angular8project\node_modules\@finos\perspective\dsm'ist\esm'
ERROR in ./node_modules/@finos/perspective/dist/esm/perspective.js                                                                                           st\esm'
Module not found: Error: Can't resolve '@apache-arrow/es5-esm/type' in 'D:\angular8project\node_modules\@finos\perspective\dist\esm'                                                                                                                                                      ist\esm'
ERROR in ./node_modules/@finos/perspective/dist/esm/perspective.js
Module not found: Error: Can't resolve '@apache-arrow/es5-esm/vector' in 'D:\angular8project\node_modules\@finos\perspective\st\esm'dist\esm'
```

**Comment by texodus** [comment]
Doesn't look like you're using [`@finos/perspective-webpack-plugin`](https://perspective.finos.org/docs/md/installation.html#-an-important-note-about-hosting) - this is needed to dist the `psp.async.wasm` and `perspective.wasm.worker.js` files.  If you're not using webpack, you'll need to copy these files from your `node_modules/@finos/perspective/dist/umd` manually (both of which are covered in the docs linked above).

If this is not your issue, I'll need some more details about your webpack setup.

**Comment by texodus** [comment]
As of #870, `@finos/perspective-webpack-plugin` is now optional, so going to go ahead and close this issue.  If you're still having problems, feel free to re-open with your projects details/repro.
