### ISSUE TITLE
Source maps for webpack-plugin

### ISSUE THREAD

**Issue by stevenvachon** [finos/perspective#861]
### Description of Problem:
Prior to using _perspective-webpack-plugin_, an `output.js.map` file was generated. After, not.

### Potential Solutions:
?

**Comment by texodus** [comment]
Thanks for the bug report!

I can't really answer this question as posed, but I can offer as a starting point [`examples/webpack`](https://github.com/finos/perspective/tree/master/examples/webpack) and [`examples/phosphor`](https://github.com/finos/perspective/tree/master/examples/phosphor), both of which use `@finos/perspective-webpack-plugin` and generate source-maps for themselves and perspective itself, as determined by their respective [`devtools` params](https://github.com/finos/perspective/blob/master/examples/phosphor/webpack.config.js#L45).  If you can start with these and build up to your break to provide a repro, please re-open with some details of the breaking config.
