### ISSUE TITLE
React and TypeScript TS2740

### ISSUE THREAD

**Issue by stevenvachon** [finos/perspective#865]
## Support Question
I'm getting this error:
```
ERROR in /component.tsx(6,10)

TS2740: Type '{ ref: RefObject<PerspectiveViewer>; }' is missing the following properties from type 'PerspectiveViewer': load, update, notifyResize, delete, and 249 more. 
```
---
types.ts:
```ts
import { /*DOMElement, */Ref } from 'react';
import { PerspectiveViewer as PerspectiveViewerOriginal } from '@finos/perspective-viewer';

export interface PerspectiveViewer extends PerspectiveViewerOriginal {
  ref: Ref<PerspectiveViewerOriginal | null>;
}

//export interface PerspectiveViewer extends PerspectiveViewerOriginal, DOMElement<any, any> {}

declare global {
  namespace JSX {
    interface IntrinsicElements {
      'perspective-viewer': PerspectiveViewer;
    }
  }
}
```

component.tsx:
```tsx
import { PerspectiveViewer } from 'types';
import React, { createRef, PureComponent } from 'react';
import '@finos/perspective-viewer';

export class PerspectivePanel extends PureComponent {
  perspectiveViewer = createRef<PerspectiveViewer | HTMLElement | null>();

  render() {
    return (<perspective-viewer ref={this.perspectiveViewer} />);
  }
}
```

**Comment by texodus** [comment]
Thanks for the bug report!

We've updated the `perspective-viewer` typings and added an [example Typescript + React application]() to the `/examples` package.  These changes will be released in 0.4.1.  If you're still having issues, please feel free to re-open.

**Comment by stevenvachon** [comment]
@texodus This is a big improvement, thank you. I've run into an issue with it, however:
```tsx
<perspective-viewer
  className="perspective-viewer-material-dense-dark"
  ref={this.viewer}
/>
```
produces
```html
<div classname="perspective-viewer-material-dense-dark">
...
```
Using `class` as an attribute instead of `className` results in:
```
TS2322: Type '{ class: string; ref: RefObject<HTMLPerspectiveViewerElement>; style: { height: number; width: number; position: "relative"; zIndex: number; }; }' is not assignable to type 'DetailedHTMLProps<ReactPerspectiveViewerHTMLAttributes<HTMLPerspectiveViewerElement>, HTMLPerspectiveViewerElement>'.
    Property 'class' does not exist on type 'DetailedHTMLProps<ReactPerspectiveViewerHTMLAttributes<HTMLPerspectiveViewerElement>, HTMLPerspectiveViewerElement>'.
```

**Comment by zemeolotu** [comment]
@stevenvachon Doesn't look like the react typings have `class` as an html attribute, just [`className` ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1698)

**Comment by texodus** [comment]
According to the [React docs](https://reactjs.org/docs/dom-elements.html#classname), `class` is supposed to be correct here.

It looks like [`class` comes from React.HTMLElement](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/global.d.ts#L32), but in our `index.d.ts` we are defining the base `HTMLPerspectiveViewerElement` as extending `React.HTMLAttributes<T>`  instead.  This is one level too deep, `DetailedHTMLProps< ... >` is a `React.HTMLAttributes< ... >` (e.g. where `ref` comes from), and `T` is a _native_ DOM element so it should not also inherit `HTMLAttributes< ... >`.  I've opened #885 which fixes this and allows `class` to be used in `exampled/react` test project without error.

**Comment by texodus** [comment]
#886 should resolve this issue for now via the `class` prop.  Let us know if you have further issues.

**Comment by stevenvachon** [comment]
Thanks, that fixes it. Would you publish a patch release, please?
