### ISSUE TITLE
clear() error for perspective-viewer

### ISSUE THREAD

**Issue by stevenvachon** [finos/perspective#878]
### Steps to Reproduce:
```js
const viewer = document.querySelector('perspective-viewer');

viewer.clear(); // throws
viewer.update([]);
```

### Expected Result:
No error thrown.

### Actual Result:
```
TypeError: Cannot read property 'clear' of undefined
    at HTMLElement.clear (some-file.js:1)
```

Probably caused by an inner `this.table.clear()` (or similar) when the table had not been instantiated.

### Environment:
* `"@finos/perspective-viewer": "^0.4.0-rc.4"`
* Node.js v12.14.1
* macOS 10.15.2

**Comment by texodus** [comment]
Yes, this is precisely right - `clear()` requires a an existing table.  We should sanitize for these cases in `perspective-viewer`.
