### ISSUE TITLE
CSS theme issues

### ISSUE THREAD

**Issue by stevenvachon** [finos/perspective#882]
Per https://perspective.finos.org/docs/md/js.html#theming:

* `*.css` files are not in `themes/` but actually `dist/umd/`
* `dist/umd/all-themes.css` does not contain an `@import` of other `*.css` files

### Environment:
* `"@finos/perspective-viewer": "^0.4.1"`
* Node.js 12.14.1
* macOS 10.15.2

## Hmm
The `themes/` path does work when compiling, though; perhaps because of the webpack plugin?

**Comment by zemeolotu** [comment]
The `/themes` path works because we leverage the `browser` field in the package.json (see [here](https://github.com/defunctzombie/package-browser-field-spec#replace-specific-files---advanced)).

`all-themes.css` exposes all available themes as css class selectors. If you're using just one theme in your app, I'll recommend you import the specific css for that theme.

**Comment by stevenvachon** [comment]
I get this when I import themes individually:
```
ERROR in ../node_modules/@finos/perspective-viewer/dist/umd/material-dense.dark.css (../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/postcss-loader/src??ref--6-2!../node_modules/style-loader!../node_modules/css-loader/dist/cjs.js??ref--8-1!../node_modules/postcss-loader/src??ref--8-2!../node_modules/sass-loader/lib/loader.js!../node_modules/@finos/perspective-viewer/dist/umd/material-dense.dark.css)
      Module build failed (from ../node_modules/postcss-loader/src/index.js):
      SyntaxError
      
      (2:1) Unknown word
      
        1 | 
      > 2 | var content = require("!!../../../../css-loader/dist/cjs.js??ref--8-1!../../../../postcss-loader/src/index.js??ref--8-2!../../../../sass-loader/lib/loader.js!./material-dense.dark.css");
          | ^
        3 | 
        4 | if(typeof content === 'string') content = [[module.id, content, '']];
```

**Comment by zemeolotu** [comment]
Yea, that's a strange one. Any chance you have a repro I could take a look at?

**Comment by stevenvachon** [comment]
I have a public repository, but it uses an overly complex build setup. I think we can revisit this when we simplify, as it could have nothing to do with your webpack plugin. My use of the perspective viewer is currently experimental, so it's fine to use `all-themes.css`.
