### ISSUE TITLE
Changing tables in viewer & unhandled exception server side

### ISSUE THREAD

**Issue by crambelsoupy** [finos/perspective#909]
We create an angular component that contains a perspective viewer, leveraging a remote connection using the perspective websocket.:

`this.websocket = (perspective as any).websocket(environment.PERSPECTIVE_URL);
this.viewer = document.getElementById("perspective-viewer-source") as any;`

Also, we have an array of tables that we want the user to be able to load into the viewer, so each time a different table is selected by the user, we run the following for our angular component that encapsulates the perspective viewer 

    const table = await this.websocket.open_table(“table_name”);
    if (table != null) {
      this.viewer.removeEventListener("perspective-config-update", async () => {
        await this.onSaveView()
      });
      await this.viewer.reset();
      await this.viewer.load(table);
      await this.viewer.restore(config);
      if (!this.viewer._show_config) {
        await this.viewer._toggle_config()
      }
      this.viewer.addEventListener("perspective-config-update", async () => {
        await this.onSaveView()
      });
    } else {
      console.log(`ERROR\tPerspectiveRemoteComponent.onUpdateView table ${table.name} doesn't exist on server`)
    }

We have noticed that when we do this, if the new table has different columns we get the following warning in the browser console: “No column ‘XXXXX’ found (specified in aggregates attribute)”, for every any column that isn’t in both the old table, and the new table.

The real issue we are experiencing is on the serverside in a node application that serves the perspective websocket, and we aren’t sure if it relates to the above. Often we see the following in our console “Abort(): Could not find column 'XXXX' in the schema.”, but aside from this and seemingly randomly (although maybe cause to large workloads with large tables and switching between them), perspective crashes with an unhandled exception: 

`Abort(): Could not find column `process` in the schema.
events.js:298
      throw er; // Unhandled 'error' event
      ^
Error: abort()
    at Xa (/app/node_modules/@finos/perspective/dist/umd/perspective.node.js:7:55939)
    at emscripten_asm_const_iii (/app/node_modules/@finos/perspective/dist/umd/perspective.node.js:7:87817)
    at wasm-function[1258]:0x5e3a9
    at wasm-function[1663]:0x98119
    at wasm-function[1299]:0x634d8
    at wasm-function[1654]:0x96abc
    at wasm-function[1799]:0xd1e12
    at wasm-function[1797]:0xcb946
    at wasm-function[1311]:0x68efe
    at wasm-function[1100]:0x47457
    at wasm-function[1101]:0x474af
    at wasm-function[2868]:0x13bef9
    at e.dynCall_vii (/app/node_modules/@finos/perspective/dist/umd/perspective.node.js:7:94947)
    at dynCall_vii_1077 (eval at X (/app/node_modules/@finos/perspective/dist/umd/perspective.node.js:1:1), <anonymous>:2:12)
    at t_pool$_process [as _process] (eval at oc (/app/node_modules/@finos/perspective/dist/umd/perspective.node.js:1:1), <anonymous>:6:1)
    at _call_process (/app/node_modules/@finos/perspective/dist/umd/perspective.node.js:7:109209)
    at Timeout._onTimeout (/app/node_modules/@finos/perspective/dist/umd/perspective.node.js:7:109691)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (internal/worker.js:204:10)`

Could the error be caused by the way that the tables are swapped out in the perspective viewer, and if so how should we deal with this?

**Comment by nevi-me** [comment]
Hi @crambelsoupy this is unrelated, but how were you able to wrap `<perspective-viewer>` around Angular? I'm currently struggling with that.

**Comment by crambelsoupy** [comment]
@nevi-me what problem are you having exactly? We have an example in a public [repos](https://github.com/elaraai/AngularPerspective). In particular if you diff at [this commit](https://github.com/elaraai/AngularPerspective/commit/a476f9ea65c7873d02d46fdb39a8897076a01366) you will see the steps taken to get it to work based on the fact that it's a webcomponent. I haven't run that repos in a little while though, but happy to answer questions.

**Comment by nevi-me** [comment]
Thanks @crambelsoupy, I'm able to load the perspective-viewer now. I'm struggling with figuring out how to load arrow data (both as a JavaScript-converted table and as an array buffer). I'll play around and see what I can do.

**Comment by sc1f** [comment]
@nevi-me We have an example of loading an arrow into Perspective using `fetch`: https://github.com/finos/perspective/blob/master/examples/simple/superstore-arrow.html

Perspective checks for the `ArrayBuffer` type to determine whether the dataset is an arrow - do you have a more specific repro of the issue you're seeing? Thanks!

**Comment by nevi-me** [comment]
Hi @sc1f, I didn't see this response. I've just opened an issue. Perhaps what's missing for me is the conversion to `arrayBuffer`, so let me check that out. Thanks

**Comment by sebinsua** [comment]
This does appear to be a bug to me but I'll reproduce so you can see what I mean.

**Comment by texodus** [comment]
Thanks all for the reports!  

@crambelsoupy @sebinsua @hediet The issue is - `<perspective-viewer>` is designed to reflect the _HTML Attribute_ settings on itself, unless they have not been set.  Once you have loaded a data set, attribute settings like `columns` are auto-populated with defaults from the `Table` you've loaded, and obviously these won't match when a new Arrow is loaded with a different Schema.  You want this behavior when e.g., you specifiy a `<perspective-viewer>` with attributes and then later call `load()` when data is downloaded.  The solution is to call [`reset()`](https://perspective.finos.org/docs/obj/perspective-viewer.html#perspectiveviewerreset) which will clear these attributes, or `restore()` if you have a specific configuration for the new `Table` in mind.  This can also be fixed live with the `Reset` button (right-click the config menu, 3rd icon).

Perspective could definitely use better error reporting in this case, both in the API and GUI, and more obvious placement of the e.g. `Reset` buttons.  I will open tickets for these.
