### ISSUE TITLE
Incorrect semver for front end assets causing issues with voila

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#921]
These versions are stale (they are not auto-incremented) which can cause issues with Voila loading the wrong version. 

https://github.com/finos/perspective/blob/master/python/perspective/perspective/widget/widget.py#L144

**Comment by texodus** [comment]
It also seems like the `bumpversion` script did not pick up `0.4.3` nor `0.4.2.post1`.

**Comment by timkpaine** [comment]
Since we have the package.json, can we just ship that and then read the version out of it?

**Comment by timkpaine** [comment]
Then lerna can manage all the versioning and we can delete bumpversion

**Comment by sc1f** [comment]
That sounds much nicer. I'll work it in.

**Comment by timkpaine** [comment]
It's generally a bad idea to load up random files at runtime, but we would be loading up the _version.py file anyway
