### ISSUE TITLE
As per documentation Flattening a view() into a table() is not working 

### ISSUE THREAD

**Issue by Madasamy26** [finos/perspective#933]
## Bug Report
In doc 
`// Create two WebWorkers.
const worker1 = perspective.worker();
const worker2 = perspective.worker();

// Create a `table and `view` on `worker1`.
const table = worker1.table(data);
const view = table.view({ filter: [["State", "==", "Texas"]] });

// Create a table from `view` in `worker2`
const table2 = worker2.table(view);
const view2 = table2.view({ filter: [["City", "==", "Austin"]] });

//  Both `view1` and `view2` are updated.
table.update([{ State: "Texas", City: "Austin" }]);

//  Only `view1` is updated.
table.update([{ State: "Texas", City: "San Antonio" `}]);`

Above code is in https://perspective.finos.org/docs/md/js.html#querying-data-with-view

As per doc I have try to create a table from view 
const table2 = worker2.table(view);

Above code showing error.

 In perspective source code we have signature as 
 table(data: TableData, options?: TableOptions): Table; )
 not at all having parameter for view in table method!

**Comment by sc1f** [comment]
What is the error you're getting? 

The examples are all in Javascript, not Typescript - the type declarations are out of date. You should be able to cast to `any` though.

**Comment by Madasamy26** [comment]
Its showing error as 

Argument of type 'View' is not assignable to parameter of type 'TableData'.
  Type 'View' is not assignable to type '{ [key: string]: string; }'.
    Property 'delete' is incompatible with index signature.
      Type '() => Promise<void>' is not assignable to type 'string'.

**Comment by sc1f** [comment]
Perspective is not a Typescript-first project; as we build new features the typings may fall out of sync with the Javascript implementation. We'd love a PR updating the type declarations–we will also fix them when we can.

In the meantime, cast the `View` to `any`, and the feature should work as it does in Javascript.

**Comment by Madasamy26** [comment]
Thanks for your reply @sc1f,
I have already fixed, the way you mentioned above.
