### ISSUE TITLE
mouseover error with some charts in perspective-viewer

### ISSUE THREAD

**Issue by stevenvachon** [finos/perspective#941]
### Steps to Reproduce:
 1. use `<perspective-viewer>`
 2. select a chart type
 3. move mouse cursor over the chart
 4. view error in console
 5. repeat steps 2–3 until step 4 occurs

```
module.js:1 Uncaught TypeError: Cannot read property 'sourceEvent' of null
    at e.a (module.js:1)
    at Module.e.a (mouse.js:6)
    at HTMLElement.e (d3fc.js:6661)
    at HTMLElement.<anonymous> (on.js:27)
```

### Environment:
```
"@finos/perspective-viewer": "0.4.3",
"@finos/perspective-viewer-d3fc": "0.4.3",
"@finos/perspective-viewer-hypergrid": "0.4.3",
"@finos/perspective-webpack-plugin": "0.4.1",
```
Node.js: `12.16.1`
macOS `10.15.3`

### Additional Context:
~~This didn't happen with `0.4.1` (of all plugins). Reverting only `@finos/perspective-viewer-d3fc` to `0.4.1` does not solve the issue.~~

**Comment by texodus** [comment]
I can't repro this, so closing. If you (or anyone) has a better repro steps then "use charts until it breaks", please feel free to re-open.

In general, for external libraries we depend on like `d3fc`, while I'm not pleased they can be log noisy, we also need to know that it causes an actual runtime error to have a plan to fix it. I would presume a hover effect of some sort is not displayed?
