### ISSUE TITLE
Enable using Perspective in Panel similarly to using Perspective in Jupyter

### ISSUE THREAD

**Issue by MarcSkovMadsen** [finos/perspective#942]
#### My Pain

I (try to) develop awesome analytics apps in Python for traders at work and for fun and to share knowledge in my spare time. One of the python frameworks I enjoy using is [Panel](https://panel.holoviz.org/). See also [awesome-panel.org](https://awesome-panel.org) that I'm developing.

I would really like to use Perspective in Panel and I also would like to that others have the opportunity as well.

But currently this is not supported.

#### Solution

Add a Perspective widget to Panel or alternatively add support for Panel to Perspective.

#### Additional info

- Panel normally runs on top of the Bokeh Server but can also run on top of other Servers like Flask, Django and Voila.
- To enable support in Panel you would start building a Bokeh model of Perspective
    - Normally the Bokeh model on the server and in the client is kept in sync by Bokeh serialization and communication. Here we would have to consider whether the Perspective communication based on Arrow could be used instead to speed up thing.

- An alternative to a custom implementation for Panel is just to use the Perspective Jupyter version. Because soon all IPyWidgets can be used directly in Panel. But this is not as performant and powerfull (I believe) as a "native" Panel implementation.

- There is already a feature request for Perspective in the Panel repo https://github.com/holoviz/panel/issues/1107

I added a feature request in the Perspective project because maybe there is some interest in this community and some of you might want to contribute interest, ideas, knowledge, support or actual code. Furthermore I just wanted to share the progress from Panel if any. I have a hope to be able to contribute something my self.

**Comment by MarcSkovMadsen** [comment]
To put the expected effort into perspective :-) I co-contributed a widget for DeckGl to Panel. I had never tried it before. I needed to learn something Bokeh Models and how they are implemented using TypeScript. Then I implemented the first version of the DeckGL widget. I took me ~10hours. The Philipp (BDFL of Panel) helped get all the details right and he worked very hard for a day or two I also co-contributed two reference example notebooks to illustrate how the widget was used. Spend maybe 5 hours on this.

https://panel.holoviz.org/gallery/param/deck_gl_global_power_plants.html#param-gallery-deck-gl-global-power-plants

![image](https://user-images.githubusercontent.com/42288570/75087532-d996df00-5541-11ea-8d4f-49d08d68bd3d.png)

**Comment by timkpaine** [comment]
@MarcSkovMadsen this has always been on our radar as @ceball and I work on the same team at JP Morgan. We will discuss priorities and respond here next week

**Comment by MarcSkovMadsen** [comment]
FYI.

I've started adding support for the `perspective-viewer` web component to Panel. Only.

For more information see https://github.com/holoviz/panel/pull/1122#issuecomment-596169367

**Comment by MarcSkovMadsen** [comment]
Just for the record. The basic functionality for the `perspective-viewer` web component (not python package) has been implemented and is working well. The things that I would expect not working are streaming and getting selected rows back. But the rest I would expect to work just fine.

It would support my use case for now. 

But I hope someone would take it to a higher level implementing this as a true Panel pane that supports all the functionality of the Perspective python package and fast data transfer including streaming.

![perspective](https://user-images.githubusercontent.com/42288570/77223084-ab64e900-6b59-11ea-91ca-facb7c79f76d.gif)

**Comment by MarcSkovMadsen** [comment]
FYI. I've added an example to the gallery at awesome-panel.org

![test_perspective](https://user-images.githubusercontent.com/42288570/82760061-83ac2e80-9df1-11ea-844b-86bf40caf21b.gif)

**Comment by MarcSkovMadsen** [comment]
Panel has been available in Panel for a long time now. And its awesome. See https://panel.holoviz.org/reference/panes/Perspective.html

I will close this one.
