### ISSUE TITLE
Smoothen python installation process (on windows)

### ISSUE THREAD

**Issue by MarcSkovMadsen** [finos/perspective#944]
#### My Pain

I'm trying to install perspective via `pip install perspective-python` on Windows 8.1. And I have now spent a couple of hours without luck. These days I seldom spend any time on installing pip packages so this is an unusual experience.

I will eventually get it installed I believe. But I would like to enable my analysts and traders to install this as well and it's simply too painfull for them to go through this.

### Solution

- Enable perspective to be `pip installed` without compilation.
- Enable perspective to be `conda installed` without compilation
- Improve the documentation https://perspective.finos.org/docs/md/installation.html
    - If TBB really needs to be installed as described at pypi them add this information and write something about why.
    - Add something about installation on Windows. For example if VS2017 compiler needs to be installed then describe this and provide a link to a guide you can follow.
    - If CMAKE needs to be installed seperately please describe this and tell the user not to `pip install cmake`
- Improve pypi documentation  https://pypi.org/project/perspective-python/
    - Make it more clear if TBB really needs to be installed and why.
     - Add something about installation on Windows. For example if VS2017 compiler needs to be installed then describe this and provide a link to a guide you can follow.
     - If CMAKE needs to be installed seperately please describe this and tell the user not to `pip install cmake`

**Comment by timkpaine** [comment]
#945 for docs

We already make wheels for other platforms, waiting for #943 to make wheels for windows

Conda forge is already inflight https://github.com/conda-forge/staged-recipes/pull/10884

**Comment by MarcSkovMadsen** [comment]
Thanks for taking a look @timkpaine . Issue 945 points to "Deal with np.int_ on Windows, handle missing __INDEX__". I can't see the connection to the Docs. Is this a wrong link?
