### ISSUE TITLE
How to enable dark theme in perspective viewer 

### ISSUE THREAD

**Issue by Madasamy26** [finos/perspective#950]
Hi, 

I am using perspective viewer, I want enable dark theme in perspective and hyper-grid plugin and d3fc-plugin as well.

so how to enable all dark theme in perspective-viewer?

**Comment by timkpaine** [comment]
https://perspective.finos.org/docs/md/styles.html

**Comment by timkpaine** [comment]
https://bl.ocks.org/texodus/e6ac62e3e113c6595e762cfce96cfab0

**Comment by Madasamy26** [comment]
Thanks @timkpaine
