### ISSUE TITLE
How to Set schema for perspective table

### ISSUE THREAD

**Issue by Madasamy26** [finos/perspective#951]
Hi,

How  to set the schema for perspective viewer while loading table ?

Is there possibility?

**Comment by timkpaine** [comment]
Read the docs

**Comment by Madasamy26** [comment]
That I have read ...
The problem is while loading scheme, How perspective identify schema from data.
Assume that...

```
schema = [{a:"integer"}]
data = [{a:"value"}]

const table = worker.table(schema)
table.schema().then((value:any) =>{ console.log('schema',value)} )
worker.table(data)
```
So how perspective will differentiate schema from data...

because of I have Initiated with schema but perspective has assumed that as data...

Output from the above console
schema {a:string}
but expected output
schema {a:integer}

????.

**Comment by timkpaine** [comment]
schema should be an object, not an array. When you call `load(schema_or_data)` you can pass one or the other. if you pass schema it will initialize the table with no data, if you pass data it will infer the scheme from the data. So you have several options:

```
viewer.load({a: "integer"})
viewer.update([{a: 1}])
```

Or

```
viewer.load([{a: 1}])
```

**Comment by timkpaine** [comment]
The relevant docs are:
Table API: https://perspective.finos.org/docs/md/js.html#loading-data-with-table
PerspectiveViewer API: https://perspective.finos.org/docs/obj/perspective-viewer.html#module_perspective-viewer..PerspectiveViewer+load

Notice the following line:
- data any - The data to load. Works with the same input types supported by perspective.table.
