### ISSUE TITLE
Update data on remote WebSocketServer

### ISSUE THREAD

**Issue by alexeykulakov** [finos/perspective#960]
I'm trying to figure out how to update data on a remote server.
I register the data table object as in the documentation.

```
const { WebSocketServer, table } = require("@finos/perspective");
const host = new WebSocketServer({ assets: [__dirname], port: 8080 });
const fs = require("fs");
const arr = fs.readFileSync(__dirname + "/superstore.arrow");
const tbl = table(arr);
host.host_table("table_one", tbl);
```

What should I do to update "table_one" object - to load another dataset?
If I try `host.host_table("table_one", another_dataset)`  then get the error:
> Error: "table_one" already exists

Can't find any api docs for WebSocketServer class.
Could you give me some example or links?
Thanks

**Comment by texodus** [comment]
You should just be able to call `update()` on the `tbl` object itself.  A `Table` object in Perspective is synonymous to a database table handle.

You may find the [`remote` example project](https://github.com/finos/perspective/tree/master/examples/remote) helpful;  [this](https://github.com/finos/perspective/blob/master/examples/remote/server.js#L101) is where updates are applied.

**Comment by texodus** [comment]
Closing - if this does not answer your question, please feel free to re-open with more details about your example.
