### ISSUE TITLE
Configuring the date format

### ISSUE THREAD

**Issue by nevi-me** [finos/perspective#962]
## Support Question

How can I change the date format on the perspective viewer? It's currently showing as `MM/DD/YYYY`, but I'm in a locale that uses `DD/MM/YYYY`.

I'm using version 0.4.2

**Comment by texodus** [comment]
Perspective uses the browser's built-in `Intl`, covered in the documentation [here](https://perspective.finos.org/docs/md/js.html#customizing-behavior-with-perspectiveconfigjs).  

[`Intl.DateTimeFormat` on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat)

**Comment by Crashillo** [comment]
I didn't figure out how make this work. You're saying the dates are formatted by the browser, aren't they?
So, does that mean the demo datagrid at https://perspective.finos.org/ should display the dates in my locale? Because, it isn't.
