### ISSUE TITLE
Is there any way to get event type in perspective

### ISSUE THREAD

**Issue by Madasamy26** [finos/perspective#968]
Hi,

I am using custom plugin in perspective-viewer,

So, If we are applying sort (or) groupby (or) filter in perspective that will invoke by create method in plugin config.

```
{
create:drawView(entryPoint)
}
```
so, Is there any way to identify in custom plugin, that what event has occurred in perspective ?

**Comment by texodus** [comment]
Perspective does not have a concept of incremental transforms as you describe - changing `sort` or `filter` in the UI is a completely new query to the engine regardless of what structure it shared with the previous query, and there is no guarantee that each call to `create()` will only pertain to a single "type" of transform being applied in sequence.  You can read the current state of the view from [the Persistence API](https://perspective.finos.org/docs/md/js.html#setting--reading-perspective-viewer-configuration-via-attributes) or [via `view.get_config()`](https://perspective.finos.org/docs/obj/perspective.html#module_perspective..view+get_config).

I could offer a better suggestion with more details about your use case, so feel free to re-open with more specifics about what it is you're trying to achieve if this does not answer your question.
