### ISSUE TITLE
Custom sorting order

### ISSUE THREAD

**Issue by rmdort** [finos/perspective#996]
## Support Question

Hi, I searched through, couldnt find anything about custom sort order.

Lets say i want to display my rows of currencies in a particular order, Anyway to accomplish this in perspective? In a Pivoted view ofcos

````
['USD', 'AUD', 'CAD']
````

**Comment by texodus** [comment]
Thanks for the report!

This is an area we are actively working on.  You can only achieve this currently by creating another column e.g. "currency order" with integer sort weights, and sorting by that column instead.  Note it is not required for the new column to be visible for it to be a sort column, but if you are planning to then pivot by "currency" (for example to get a tree view of currencies), you may wish to set "currency order" aggregate to something like `{"currency order": "unique"}` (or `any` or `dominant`) so it is not sorted by `sum` of "currency order".

Future work on the back of #983 will allow simple specification for an enumerated "currency order" column ad-hoc in the UI or persistence API (so far this lacks support for scalars and var args/vectors).

**Comment by rmdort** [comment]
Got it. Excited about computed/lambda columns.  Thanks
